inasafe/inasafe

safe/test/utilities.py, scripts/jenkins-linux.sh
* Enable using inasafe_data for now
* Update jenkins-linux.sh for jenkins job.
=> Update Jenkins Script.

metadata.txt, safe_qgis/report/map.py, safe_qgis/report/test/test_map.py, safe_qgis/tools/batch/batch_dialog.py, safe_qgis/tools/batch/scenario_runner.py
Since QGIS 2.6, we must use the new legend model (QgsLegendModelV2())
=> [Backport] Fix Legend Issue in QGIS > 2.6 and Batch Dialog in Master.

run-env-realtime.sh
=> Use default QGIS installed prefix path for realtime.

safe/postprocessors/road_type_postprocessor.py
This is to address https://github.com/AIFDR/inasafe/issues/1494
=> Import tr function from safe.utilities.i18n.

run-env-realtime.sh, scripts/realtime/make-latest-shakemap.sh
=> [Realtime] Pass shakemaps dir as argument for make-latest-shakemap.sh

scripts/realtime/make-public.sh
=> [Realtime] Pass shakemaps extract dir and web dir to make-public.sh 

safe/gui/widgets/dock.py, safe/utilities/analysis_handler.py
This is to address https://github.com/AIFDR/inasafe/issues/1505
=> Catch the unhandled case when user wants to print nonexistent template.

metadata.txt, safe_qgis/report/test/test_map.py, scripts/release.sh
=> Hotfix for #1500 - maximum version in metadata causes error on debian

safe/impact_functions/impact_function_manager.py, safe/impact_functions/impact_function_metadata.py, safe/impact_functions/inundation/flood_building_impact_qgis.py, safe/impact_functions/inundation/flood_polygon_roads.py, safe/impact_functions/inundation/flood_population_evacuation_polygon_hazard.py, safe/impact_functions/test/test_impact_function_metadata.py
This PR is adding checking validity of IF's metadata, for preventing human's mistake when writing IF.
=> Add is_valid for checking IF's metadata's validity.

safe/gui/widgets/dock.py
This commit is for fixing uncaught exception that @mahardika founds. See below:
=> Add uncaught exception in dock.py

safe/report/impact_report.py, safe/report/template_composition.py
* QgsMapSettings and QgsLayerTreeGroup was added in QGIS 2.4
=> Support QGIS < 2.4 for printing routines.

safe/gui/tools/test/test_save_scenario.py, safe/impact_functions/generic/classified_hazard_population.py, safe/impact_functions/generic/continuous_hazard_population.py, safe/impact_functions/generic/test/test_categorical_hazard_population.py
* Hazard of the Classified Hazard on Population IF is recognised by its layertype=='raster' and data_type=='classified'.
* Hazard of the Continuous Hazard on Population IF is recognised by its layertype=='raster' and data_type=='continuous'
=> Update Classified and Continuous IF docstrings so that dock can recognise it

safe/gui/widgets/dock.py, safe/gui/widgets/message_viewer.py
Don't merge this first. Though this will fix the test, it will reopen https://github.com/AIFDR/inasafe/issues/1488. I will fix 1488 with another approach first
=> Fix to test_layer_changed

safe/impact_functions/generic/continuous_hazard_population.py, safe/impact_functions/test/test_impact_function_manager.py, safe/impact_functions/test/test_impact_function_metadata.py
=> Remove unit_continuous from Wizard.

safe/impact_functions/utilities.py
Return the python file instead the pyc file.
=> Fix duplicate if

.travis.yml, Makefile, metadata.txt, safe/gis/qgis_interface.py, safe/gui/tools/batch/scenario_runner.py, safe/gui/tools/rectangle_map_tool.py, safe/gui/tools/test/test_wizard_dialog.py, safe/gui/tools/test/test_wizard_dialog_locale.py, safe/impact_functions/core.py, safe/impact_functions/utilities.py, safe/impact_statistics/aggregator.py, safe/test/test_plugin.py, safe/test/utilities.py, safe/utilities/extent.py
@ismailsunni can you please backport to master except for the changes to metadata.txt? Thanks!
=> Pylint and pep8 fixes for pylint 1.4.1 and pep8 1.6.1

.gitattributes
add more binaries files to .gitattribute
=> add more binaries files to .gitattribute

safe/utilities/qgis_utilities.py
Fix 1650 : add new methods to display informations through QgsMessageBar and QMessageBox
=> Fix 1650 : add new methods to display informations through QgsMessageBar and QMessageBox

safe/utilities/test/test_utilities.py, safe/utilities/utilities.py
add function to replace accentuated characters
=> add function to replace accentuated characters

safe/gui/tools/test/test_wizard_dialog.py, safe/impact_functions/earthquake/earthquake_building_impact.py, safe/impact_functions/test/test_impact_function_manager.py, safe/impact_functions/test/test_impact_function_metadata.py
* The IF should only work for continuous raster hazard
=> Fix Earthquake Building IF Issues #1686 in Develop

scripts/jenkins-linux.sh
=> Force locale to utf-8 for jenkins

safe/gui/tools/osm_downloader_dialog.py, safe/gui/tools/test/test_osm_downloader.py
fix #1721 add a locale flag in the url for osm downloader
=> fix #1721 add a locale flag in the url for osm downloader

safe/impact_functions/inundation/flood_population_evacuation_raster_hazard.py
It can handle multple thresholds.
=> Fix Flood IF Raster on Population.

safe/common/test/test_utilities.py, safe/common/utilities.py, safe/gui/tools/osm_downloader_dialog.py, safe/gui/tools/test/test_osm_downloader.py, safe/utilities/file_downloader.py
fix #1735 : improvements about the OSM downloader's progress dialog
=> fix #1735 : improvements about the OSM downloader's progress dialog

safe/gui/tools/osm_downloader_dialog.py
fix quoted strings, qmessagebox
=> fix quoted strings, qmessagebox

safe/gui/tools/wizard_dialog.py, safe/gui/widgets/dock.py, safe/messaging/item/text.py, safe/postprocessors/gender_postprocessor.py
Coding standards cleanups for gender postprocessor
=> Coding standards

safe/engine/core.py, safe/impact_statistics/zonal_stats.py, safe/storage/raster.py, safe/storage/vector.py
fix unicode in file path when saving to a specific directory
=> fix unicode in file path

safe/gui/tools/minimum_needs/needs_profile.py
- Fix minimum needs not loaded. We mustn't declare the type to get the value from QSettings anymore.
=> Tweak the behavior of Minimum Needs Profile

safe/gui/widgets/dock.py
Add file exist check and zero heights check that is causing Overflow Errors.
Organization Logo Path will be reset to its default path
=> Bugfix Issue #1784 : Add file exist and zero heights checks

safe/impact_functions/__init__.py, safe/impact_functions/test/test_registry.py, safe/impact_functions/volcanic/volcano_point_population/__init__.py, safe/impact_functions/volcanic/volcano_point_population/impact_function.py, safe/impact_functions/volcanic/volcano_point_population/metadata_definitions.py, safe/impact_functions/volcanic/volcano_point_population/parameter_definitions.py, safe/impact_functions/volcanic/volcano_point_population/test/__init__.py, safe/impact_functions/volcanic/volcano_point_population/test/test_volcano_point_population.py, safe/impact_functions/volcanic/volcano_polygon_building/impact_function.py, safe/test/data/exposure/roads.keywords, safe/test/data/exposure/roads.xml
=> Separate volcano IF on population between point and polygon hazard.

safe/common/version.py, safe/plugin.py
=> Don't enable load standard layers tool if it's not final release.

safe/gui/widgets/dock.py
=> Fix pep8 errors

safe/gui/ui/wizard_dialog_base.ui
=> [BACKPORT] Fix #1484

resources/minimum_needs/Philippine Minimum Needs_en.json, safe/gui/tools/minimum_needs/needs_manager_dialog.py
Removed duplicate entries in the minimum needs file. Changed the appearance of the options dialog from
to
fixes issue #1888
=> Clean resources

Dockerfile, Makefile
=> In progress work to support running tests under docker for a homogenous testing environment

safe/gui/tools/minimum_needs/needs_manager_dialog.py, safe/gui/ui/needs_manager_dialog_base.ui, safe_extras/parameters/qt_widgets/qt4_parameter_factory.py, safe_extras/parameters/qt_widgets/text_parameter_widget.py, safe_extras/parameters/text_parameter.py
Minimum needs bug fixes:
* Needs Manager resize
* Dropdown list populates with correct minimum needs profile
* More space for Readable Sentence
=> this closes #1926 #1930 1933

safe/gui/tools/minimum_needs/needs_calculator_dialog.py, safe/gui/ui/needs_calculator_dialog_base.ui, safe/plugin.py, safe/storage/vector.py
There were this weird bug when using a model-less dialog (the dialog is shown using show method), suddenly the combo box currentIndexChanged signal and several signal like button_box clicked signal becomes can't be triggered.
The workaround is however making the dialog a modal dialog. Sadly, I haven't found the reason why the bug appeared in the first place. After many hours searching for clues, I decided that it would be unproductive to continue looking for it.
=> Fix minimum needs calculator

safe/gui/tools/minimum_needs/needs_manager_dialog.py, safe/gui/ui/needs_manager_dialog_base.ui, safe_extras/parameters/qt_widgets/qt4_parameter_factory.py, safe_extras/parameters/qt_widgets/text_parameter_widget.py, safe_extras/parameters/text_parameter.py
fix #1944: allows a scrollbar so the user doesn't have to resize window when it exceeds the OS windows
I only add a vertical scrollbar for this commit.
=> Fix for minimum needs User Interface errors

safe/impact_functions/generic/classified_polygon_building/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_population/metadata_definitions.py
=> change generic IF metadata

safe/impact_functions/generic/classified_polygon_population/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_population/test/test_classified_polygon_population.py
* This IF works for population count.
=> Fix metadata for Classified Polygon on Population.

safe/gui/tools/test/test_wizard_dialog.py, safe/gui/tools/wizard_dialog.py, safe/gui/ui/wizard_dialog_base.ui
Update the wizard according to the recent diagram from the comments: https://github.com/AIFDR/inasafe/issues/1956#issuecomment-109292866
=> [Wizard] Update the keyword wizard

docs/api-docs/index.rst, docs/api-docs/realtime.rst, docs/api-docs/realtime/exceptions.rst, docs/api-docs/realtime/make_local_map.rst, docs/api-docs/realtime/make_map.rst, docs/api-docs/realtime/shake_data.rst, docs/api-docs/realtime/shake_event.rst, docs/api-docs/realtime/update_latest_report.rst, docs/api-docs/realtime/utilities.rst, docs/api-docs/safe.rst, scripts/create_api_docs.py, scripts/create_impact_function_docs.py
=> Added api docs scripts from docs repo

safe/gui/tools/osm_downloader_dialog.py
fix space and comma in the OSM downloader
=> fix space and comma in the OSM downloader

safe/gui/tools/test/test_osm_downloader.py
=> fix test osm downloader

safe/definitions.py
=> In progress updated for #1975

safe/gui/ui/extent_selector_dialog_base.ui, safe/gui/ui/options_dialog_base.ui
We don't user resources_rc anymore. And it will raise error in my computer if not removed.
=> Remove resources_rc from UI files.

safe/definitions.py, safe/gui/tools/test/test_osm_downloader.py
=> Remove default hazard class

safe/utilities/test/test_osm_downloader.py
=> Fix pylint

safe/definitions.py
=> minor updates to definitions.py

safe/impact_functions/volcanic/volcano_point_building/metadata_definitions.py, safe/impact_functions/volcanic/volcano_point_building/test/test_volcano_point_building.py, safe/impact_functions/volcanic/volcano_point_population/metadata_definitions.py, safe/impact_functions/volcanic/volcano_point_population/test/test_volcano_point_population.py
- Remove hazard_keywords volcano_vector_hazard_classes in Volcano point for fixing #2091
=> Fix 2091 volcano

safe/definitions.py, safe/impact_functions/unit_definitions.py
Make all the definitions in one place.
=> Refactor unit definitions

realtime/shake_event.py, run-env-realtime-test.sh, scripts/realtime/make-all-shakemaps.sh, scripts/realtime/make-latest-shakemap.sh, scripts/realtime/make-list-shakes.sh, scripts/realtime/make-shakemap-local.sh, scripts/realtime/make-shakemap.sh
- Add source env for realtime testing in pycharm
=> Make realtime package more tests friendly

safe/impact_functions/generic/continuous_hazard_population/impact_function.py
Probably I will add more tweaks here so no need to merge quite yet...
=> Better docstring for continouse generic IF

safe/gui/tools/minimum_needs/needs_profile.py, safe/gui/tools/minimum_needs/test/test_minimum_needs_qsettings.py, safe/impact_functions/inundation/flood_vector_building_impact/parameter_definitions.py
Fix #2132 - traceback on parsing custom minimum needs file
=> Fix #2132 - traceback on parsing custom minimum needs file

safe/gui/tools/extent_selector_dialog.py
=> fix sqlite error in master

metadata.txt, safe/impact_functions/generic/classified_polygon_building/metadata_definitions.py, safe/postprocessors/building_type_postprocessor.py, safe/postprocessors/test/test_building_type_postprocessor.py
-> Added building type postprocessor to Volcanic Ash impact function (Generic Impact function) Fixes #2105
-> Building total function corrected. Fixes #2144
=> Volcano sprint/2105

metadata.txt, safe/engine/interpolation.py, safe/engine/test/test_engine.py, safe/impact_functions/generic/classified_polygon_building/metadata_definitions.py, safe/impact_functions/volcanic/volcano_point_building/impact_function.py, safe/impact_functions/volcanic/volcano_point_building/metadata_definitions.py, safe/impact_functions/volcanic/volcano_polygon_building/metadata_definitions.py, safe/impact_statistics/postprocessor_manager.py, safe/postprocessors/building_type_postprocessor.py, safe/postprocessors/test/test_building_type_postprocessor.py
Cherry picked changes to go into master.
=> Master - Volcano Sprint

safe/definitions.py, safe/gui/tools/wizard_dialog.py
=> Bug fixing

safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/test/test_itb_earthquake_fatality_model.py, safe/impact_functions/earthquake/pager_earthquake_fatality_model/test/test_pager_earthquake_fatality_model.py
I have a question regarding population rounding function in the core.py. What's the logic behind the function?
=> changed the test code to reflect the change in the impact function

safe/plugin.py
=> Adjusted menus to have spacers - fix #1820

realtime/shake_event.py, realtime/test/test_shake_event.py, safe/storage/safe_layer.py
- Fix errors in realtime where hazard name is read as int instead of str
- Fix some errors in realtime tests
=> Realtime fix:

resources/qgis-composer-templates/landscape-a3.qpt, resources/qgis-composer-templates/portrait-a3.qpt
=> Added new templates from Iwan - see #1314

safe/gui/tools/wizard_dialog.py, safe/gui/tools/wizard_strings.py, safe/gui/ui/wizard_dialog_base.ui
Still a work in progress - not ready to merge
=> In progress sizing tweaks for wizard - see #2207

safe/impact_functions/inundation/flood_polygon_roads/impact_function.py, safe/impact_functions/inundation/flood_raster_road/impact_function.py, safe/impact_reports/road_exposure_report_mixin.py, safe/impact_reports/test/test_road_exposure_report_mixin.py
=> Roads report mixin

safe/impact_functions/inundation/flood_raster_osm_building_impact/impact_function.py
fixes #2240 
due to bad merge at 9fc87d8cfe8d83cb3d965f018bc9a2dfaee6a233
=> Bugfix 2240: fixing inundation problem 

safe/gui/tools/test/test_wizard_dialog.py, safe/impact_functions/earthquake/earthquake_building/metadata_definitions.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/earthquake/pager_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_building/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_population/metadata_definitions.py, safe/impact_functions/generic/classified_raster_building/metadata_definitions.py, safe/impact_functions/generic/classified_raster_population/metadata_definitions.py, safe/impact_functions/inundation/flood_polygon_population/metadata_definitions.py, safe/impact_functions/inundation/flood_polygon_roads/impact_function.py, safe/impact_functions/inundation/flood_polygon_roads/metadata_definitions.py, safe/impact_functions/inundation/flood_raster_osm_building_impact/metadata_definitions.py, safe/impact_functions/inundation/flood_raster_population/metadata_definitions.py, safe/impact_functions/inundation/flood_raster_road/impact_function.py, safe/impact_functions/inundation/flood_raster_road/metadata_definitions.py, safe/impact_functions/inundation/flood_vector_building_impact/metadata_definitions.py, safe/impact_functions/inundation/tsunami_population_evacuation_raster/metadata_definitions.py, safe/impact_functions/test/test_impact_function_manager.py, safe/impact_functions/test/test_impact_function_metadata.py, safe/impact_functions/volcanic/volcano_polygon_building/metadata_definitions.py, safe/impact_functions/volcanic/volcano_polygon_population/metadata_definitions.py
This PR will set all IF to have multiple event and single event. It will needed if we addressing #2217
=> Set all hazard categories

safe/gui/ui/about_dialog_base.ui
=> fix #2242 - squashed skippy in about box

safe/gui/ui/dock_base.ui
fix #2267 - too much padding at top of dock
=> fix #2267 - too much padding at top of dock

safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py
fixes #2235 
population count issue introduced in c6d83eedba7852fd84a85f4392395cc65766f43a
=> Bugfix 2235: Fixing earthquake count issue

safe/gui/widgets/dock.py
fix #2268 - use nicer table formatting for keywords in dock
=> fix inasafe-2268 - use nicer table formatting for keywords in dock

safe/impact_functions/inundation/flood_polygon_population/impact_function.py
=> Bugfix #2228: Population on vector flood fails to run.

safe/defaults.py, safe/gui/tools/wizard_dialog.py, safe/gui/widgets/dock.py
=> Typo and PEP8

resources/qgis-composer-templates/portrait-a3.qpt, safe/gui/widgets/dock.py, safe/impact_functions/__init__.py, safe/impact_functions/inundation/flood_polygon_roads/impact_function.py, safe/impact_functions/inundation/flood_polygon_roads/test/test_flood_polygon_roads.py, safe/impact_functions/inundation/flood_vector_building_impact/impact_function.py, safe/impact_functions/test/test_impact_function_metadata.py, safe/storage/vector.py, safe/utilities/analysis.py
See #2288 
This PR also fixes #2221
=> Gracefully handle cases where zero impact occurs for flood polygons on buildings.

README.md
=> Updated README to include thank you to pycharm

safe/gui/tools/wizard_dialog.py, safe/gui/ui/wizard_dialog_base.ui
Remove the Single/Multiple Scenario radiobuttons
=> [IFCW] Fix #2217

safe/gui/tools/wizard_dialog.py, safe/gui/tools/wizard_strings.py
Minor typo fix and change words in wizard dialog.
Somehow this includes @borysiasty work too 
@borysiasty please review
=> Minor text tweak and typo fix - merge with caution

realtime/grid_finder.py
Small utility for @Charlotte-Morgan to extract all grid.xml files for historical quakes into a single folder
=> Added sorter for grid.xml files

safe/definitions.py, safe/gui/tools/test/test_wizard_dialog.py
=> Fixes for broken wizard tests in PR #2333 in  Charlottes branch

realtime/grid_finder.py, realtime/push_shake.py, safe/gui/tools/minimum_needs/needs_calculator_dialog.py, safe/gui/tools/test/test_extent_selector.py, safe/messaging/item/brand.py, safe/messaging/item/table.py, safe/metadata/property/base_property.py, safe/metadata/property/character_string_property.py, safe/metadata/property/date_property.py, safe/metadata/property/url_property.py, safe/metadata/provenance/provenance_step.py, safe/metadata/test/test_metadata.py, safe/plugin.py, safe/utilities/analysis.py
Some of the changes need reviews
=> fix_pylint: with some tentative modification

safe/gui/tools/test/test_wizard_dialog.py, safe/gui/tools/wizard_dialog.py, safe/impact_statistics/postprocessor_manager.py
@christian note the _ trick to mark vars as private / unused
=> Pep8 and pylint fixes

.travis.yml
Reduce use of sudo in preparation for migration to container-based infrastructure
=> Travis: Install packages via pip

safe/gis/qgis_interface.py, safe/gui/widgets/dock.py, safe/gui/widgets/test/test_dock.py, safe/storage/safe_layer.py, safe/utilities/gis.py, safe/utilities/qgis_utilities.py
Note I expect a couple of failed tests - will fix that in a follow up PR. In the mean time, it would be great if @adissadis and @samnawi could try this out and see if it works ok for you.
=> Fix for #2322 - ensure impact layer is added just above exposure layer

safe/gui/widgets/dock.py, safe/messaging/item/message_element.py, safe/postprocessors/abstract_postprocessor.py
Aggregation layer could be None if whole area aggregation is used...
=> fix #2367 - regression caused by #2322

README.md, safe/definitions.py, safe/messaging/item/bulleted_list.py, safe/messaging/item/cell.py, safe/utilities/keyword_io.py, safe/utilities/test/test_keyword_io.py
fix #2313 - Use sensible ordering for keywords in dock.
=> fix #2313 - Use sensible ordering for keywords in dock.

metadata.txt, resources/qgis-composer-templates/landscape-a3.qpt, resources/qgis-composer-templates/portrait-a3.qpt, safe/defaults.py, safe/gui/tools/impact_merge_dialog.py, safe/gui/tools/options_dialog.py, safe/gui/widgets/dock.py, safe/report/impact_report.py, safe/test/test_defaults.py, safe/utilities/analysis_handler.py, safe/utilities/utilities.py
Fix for #2265 - please see that issue for more details
=> fix for #2265 - improve map layout and fix inconsistencies

metadata.txt
@Charlotte-Morgan please review
=> Remove / update AIFDR references in metadata.txt

safe/impact_functions/inundation/flood_polygon_roads/impact_function.py, safe/impact_functions/inundation/flood_raster_road/impact_function.py
=> Fix 2388 2389

realtime/utilities.py, safe/common/custom_logging.py
Just updating sentry dsn for InaSAFE Desktop and Realtime.
This commit will use the new sentry server in sentry.kartoza.com
=> Update sentry dsn for InaSAFE desktop and Realtime

safe/impact_functions/test/test_impact_function_metadata.py
This PR only update unit test related to additional keywords for IF. To make sure that the problem is not in IF manager for problem #2485
=> Update unit test for additional keywords

README.md, metadata.txt
- Add changelog for new IF
- Fix image and travis link
=> Changelog 3.2.4

safe/gui/tools/osm_downloader_dialog.py, safe/gui/tools/test/test_osm_downloader_dialog.py, safe/gui/ui/osm_downloader_dialog_base.ui
=> replace "potential IDP" by "evacuation center"

safe/utilities/file_downloader.py
About the ``ContentNotFoundError``, this error shoudn't happen because it means than osm-reporter is not running the latest version.
Only the first two errors might happen in production.
=> inform the user about the network status in the OSM downloader

REQUIREMENTS.txt, extras/system_tools.py, metadata.txt, safe/gui/tools/batch/batch_dialog.py, safe/gui/tools/extent_selector_dialog.py, safe/gui/tools/minimum_needs/needs_calculator_dialog.py, safe/gui/tools/save_scenario.py, safe/gui/widgets/dock.py, safe/gui/widgets/message_viewer.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py, safe/impact_functions/inundation/flood_polygon_roads/impact_function.py, safe/impact_statistics/test/test_postprocessor_manager.py, safe/plugin.py, safe/postprocessors/gender_postprocessor.py, safe/report/test/test_impact_report.py, safe/utilities/keyword_io.py, safe/utilities/memory_checker.py, safe_extras/raven/base.py
This PR comments out a bunch of debugging logging stuff so that travis doesn't have such long logs.
=> Less noisy logs

safe/impact_reports/building_exposure_report_mixin.py, safe/impact_reports/population_exposure_report_mixin.py, safe/impact_reports/road_exposure_report_mixin.py
Updated actions supplied by @fredychandra based on sphere standard http://www.spherehandbook.org/
=> update default action lists #2389

safe/impact_reports/building_exposure_report_mixin.py, safe/impact_reports/population_exposure_report_mixin.py, safe/impact_reports/road_exposure_report_mixin.py, safe/impact_reports/test/test_building_exposure_report_mixin.py, safe/impact_reports/test/test_population_exposure_report_mixin.py
Updating @Charlotte-Morgan 's PR #2513 for issue #2389
=> Charlotte morgan develop

safe/engine/core.py, safe/gui/tools/test/test_wizard_dialog.py, safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/impact_function.py, safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/test/test_itb_bayesian_earthquake_fatality_model.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py, safe/impact_functions/volcanic/volcano_point_building/impact_function.py, safe/impact_functions/volcanic/volcano_point_building/metadata_definitions.py, safe/impact_functions/volcanic/volcano_point_building/parameter_definitions.py, safe/impact_functions/volcanic/volcano_point_building/test/test_volcano_point_building.py, safe/impact_functions/volcanic/volcano_point_population/impact_function.py, safe/impact_functions/volcanic/volcano_point_population/parameter_definitions.py, safe/impact_reports/population_exposure_report_mixin.py, safe/impact_reports/test/test_building_exposure_report_mixin.py
=> Fix 2425 if volcano unit

scripts/release.sh
@ismailsunni please back port to develop
=> Fixes for packaging in master

scripts/release.sh
=> Backport from master 2547

safe/common/signals.py, safe/gui/widgets/dock.py, safe/impact_statistics/aggregator.py, safe/messaging/utilities.py, safe/utilities/analysis.py, safe/utilities/analysis_handler.py, safe/utilities/memory_checker.py
This is smaller PR about #2528.
- use tr() method from safe.utilities.i18n
- refactors signals in  safe/common/signals.py
- add docstrings
@timlinux @ismailsunni
=> Refactoring signals and tr

safe/impact_reports/population_exposure_report_mixin.py
=> Reorder impact report in population IF

safe/common/test/test_utilities.py, safe/impact_reports/population_exposure_report_mixin.py
For @Charlotte-Morgan :)
I also added some coding style things
=> Fix apostrof

safe/impact_reports/population_exposure_report_mixin.py
=> Format number of pop in action list.

bin/inasafe, safe/gui/widgets/dock.py, safe/storage/safe_layer.py, safe/utilities/analysis.py, safe/utilities/analysis_handler.py
- Use SafeLayer in Analysis
- Remove keywords when we setup the analysis as the keywords will be read by SafeLayer : 
- command line
- dock
- analysis_handler
=> Use SafeLayer in Analysis

safe/test/data/hazard/volcano_point.xml, safe/utilities/keyword_io.py, safe/utilities/test/test_keyword_io.py
Fixing #2569 
cc @Charlotte-Morgan please review :)
=> Fix URL extra 'code' in keyword in dock.

safe/impact_functions/inundation/flood_polygon_population/impact_function.py
For #2530 
Please review @adissadis @harrymahar @samnawi
=> Add unaffected population in report in IF Flood polygon poppulation

safe/gui/ui/wizard_dialog_base.ui, safe/utilities/keyword_io.py
=> Fix 2585 qdate

safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py, safe/impact_functions/generic/classified_polygon_population/impact_function.py, safe/impact_functions/generic/classified_raster_population/impact_function.py, safe/impact_functions/generic/continuous_hazard_population/impact_function.py, safe/impact_functions/inundation/flood_polygon_population/impact_function.py, safe/impact_functions/inundation/flood_raster_population/impact_function.py, safe/impact_functions/inundation/tsunami_population_evacuation_raster/impact_function.py, safe/impact_functions/volcanic/volcano_point_population/impact_function.py, safe/impact_functions/volcanic/volcano_polygon_population/impact_function.py, safe/test/data/other/issue126.qml, safe/utilities/analysis.py, safe/utilities/styling.py, safe/utilities/test/test_styling.py
Fix #2529. It will replace my PR in #2567
=> Set transparent for raster value = 0. Per #2529.

safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/test/test_itb_earthquake_fatality_model.py
Please check this @samnawi @adissadis
=> Fix 2235 huge difference

safe/impact_reports/building_exposure_report_mixin.py
Addressing #2410 
Result:
See that closed hospital and closed school is equals to the total affected, not the total building.
Please check, @Charlotte-Morgan or @samnawi
=> Better building usage count. Add categories as parameter.

safe/impact_functions/inundation/tsunami_raster_building/impact_function.py, safe/impact_functions/inundation/tsunami_raster_building/parameter_definitions.py
=> Fix failing test

CHANGELOG, Makefile, metadata.txt, safe/test/data/boundaries/district_osm_jakarta.qml, safe/test/data/exposure/building-points.qml, safe/test/data/exposure/buildings.qml, safe/test/data/exposure/pop_binary_raster_20_20.qml, safe/test/data/exposure/roads.qml, safe/test/data/exposure/roads_osm_4326.qml, safe/test/data/hazard/classified_flood_20_20.qml, safe/test/data/hazard/continuous_flood_20_20.qml, safe/test/data/hazard/flood_multipart_polygons.qml, safe/test/data/hazard/floods.qml, safe/test/data/hazard/generic_continuous_flood.qml, safe/test/data/hazard/jakarta_flood_design.qml, safe/test/data/hazard/volcano_krb.qml, safe/test/data/impact/buildings_inundated_district_jakarta.qml, safe/test/data/impact/buildings_inundated_entire_area.qml, safe/test/data/impact/flood_on_population.qml, safe/test/data/impact/polygons_for_styling.qml, safe/test/data/impact/population_affected_district_jakarta.qml, safe/test/data/impact/population_affected_entire_area.qml, safe/test/data/other/ten_by_ten_raster_as_polys.qml, safe/test/data/other/tenbytenraster.qml, safe/test/data/other/zonal_polygons.qml
Also updates changelog. Don't merge yet
=> Standardise style version in all qmls

bin/inasafe.py, realtime/earthquake/push_shake.py, realtime/flood/peta_jakarta_api.py, realtime/flood/test/test_flood_realtime.py, realtime/tasks/earthquake.py, realtime/test/test_shake_event.py, realtime/test/test_shakemap_monitoring.py, safe/impact_functions/inundation/tsunami_raster_building/impact_function.py
=> Fix 2609 target field

resources/minimum_needs/BNPB_en.json, resources/minimum_needs/BNPB_id.json, resources/minimum_needs/Tanzania.json, safe/impact_functions/inundation/tsunami_raster_building/impact_function.py
=> Fix 2612 and 2610

safe/impact_functions/inundation/tsunami_raster_building/impact_function.py
=> Fix legend to use greater number than preious range.

safe/gui/widgets/dock.py, safe/utilities/analysis.py, safe/utilities/analysis_handler.py
Fix https://github.com/inasafe/inasafe/issues/2604
=> fix #2604 check if the user_extent is well defined

safe/metadata/base_metadata.py, safe/metadata/encoder.py, safe/metadata/impact_layer_metadata.py, safe/metadata/property/date_property.py, safe/metadata/test/data/existing_impact.json, safe/metadata/test/data/existing_impact.xml, safe/metadata/test/test_impact_metadata.py
=> Fix 2623 json seriazible

safe/utilities/analysis_handler.py
=> fix #2663 in master

resources/petajakarta/flood-style.qml
=> Fix PetaJakarta flood style to be consistent with PJ website

safe/impact_functions/inundation/tsunami_raster_road/metadata_definitions.py, safe/impact_statistics/postprocessor_manager.py, safe/postprocessors/road_type_postprocessor.py
=> Fix unit in the road report issue #2691

safe/routing/gui/routing_dialog.py, safe/routing/models/inasafe_network.model
Updating the model with some Processing changes
=> fix routing analysis

safe/test/data/exposure/people_allow_resampling_true.xml, safe/test/data/hazard/continuous_flood_unaligned_big_size.xml, safe/test/data/hazard/landcover_hazard.xml, safe/test/data/impact/buildings_inundated_district_jakarta.xml, safe/test/data/impact/buildings_inundated_entire_area.xml, safe/test/data/impact/population_affected_district_jakarta.xml, safe/test/data/impact/population_affected_entire_area.xml, safe/test/data/other/issue126.qml
These are automatic changes to files after tests are run
=> Update metadata of test files

safe/impact_functions/inundation/tsunami_raster_road/metadata_definitions.py
Fix for issue #2720 
Problem:
Wrong IF metadata.
=> Fix issue #2720

safe/utilities/file_downloader.py
Need to backport to develop.
CC : @timlinux can you review and release 3.3.2 ?
=> manage a timeout error from the overpass in the OSM Downloader

safe/gui/tools/test/test_wizard_dialog.py, safe/gui/tools/wizard_dialog.py, safe/gui/tools/wizard_metadata.py, safe/gui/tools/wizard_strings.py, safe/metadata/exposure_layer_metadata.py, safe/utilities/keyword_io.py
This PR replaces #2719 and solves #2673
=> Add road and structure mapping

realtime/flood/flood_event.py, realtime/flood/peta_jakarta_api.py, safe/gui/tools/osm_downloader_dialog.py, safe/gui/ui/osm_downloader_dialog_base.ui, safe/gui/widgets/dock.py, safe/impact_functions/generic/continuous_hazard_population/test/test_continuous_hazard_population.py, safe/utilities/extent.py, safe/utilities/file_downloader.py, safe/utilities/gis.py
=> pep8, remove deprecated methods, small UI changes in the OSM downloader

safe/test/debug_helper.py
I might become lazy, but I like debugging geometries by displaying them in the canvas.
This PR just brings simple functions to display a QgsGeometry for instance.
=> add debug helper functions

safe/engine/test/test_engine.py, safe/impact_functions/base.py
=> merge analysis_workflow in calculate_impact

metadata.txt, safe/gui/widgets/dock.py
[BACKPORT] fix #2759. Apologies @ismailsunni and @gustry but there is a small string change - can you update the translations? Please also backport these changes to develop. @ismailsunni please also see the original ticket as I think we need a fix for the underlying keywords migration issue.
=> Fix keyword error

safe/gis/gdal_ogr_tools.py, safe/gis/reclassify_gdal.py, safe/gis/test/test_gdal_ogr_tools.py, safe/gis/test/test_reclassify.py
This PR brings 3 new functions : 
* reclassify
* polygonize_band
* reclassify_polygonize (the mix of these 2)
For the reclassify, I found an algorithm here : https://github.com/chiatt/gdal_reclassify
I have copy/paste the code for now. @timlinux Do you want me to re-write it ? The code seems working for now. I wrote some unit tests.
I would like to continue this PR for the landcover and maybe change every IF using a raster (except earthquake).
=> Classify and polygonize a raster

metadata.txt
Sorry, forget to update the changelog.
=> Update metadata's changelog.

metadata.txt, safe/impact_statistics/aggregator.py
Merge fix for #2724 to develop.
=> Fix #2724.

safe/definitions.py, safe/gui/tools/wizard/step_kw40_classify.py
These strings are capitalized in the python code
=> remove capital letters and add the main class to the default strings

safe/definitions.py
Wizard text being reviewed (in progress
fix #2674
Changed some grammar, wording and "\n" to "<p>" (I assumed that the intention of \n was to create a new line)
@timlinux
@Charlotte-Morgan
=> Update to Wizard text 

safe/common/signals.py, safe/gui/widgets/dock.py, safe/gui/widgets/message_viewer.py, safe/messaging/message.py, safe/messaging/utilities.py, safe/utilities/analysis_handler.py, safe/utilities/keyword_io.py
=> Add better exception for a better error handling.

safe/impact_functions/inundation/tsunami_raster_building/impact_function.py, safe/impact_reports/building_exposure_report_mixin.py, safe/postprocessors/abstract_building_road_type_postprocessor.py, safe/postprocessors/building_type_postprocessor.py, safe/postprocessors/road_type_postprocessor.py
=> Fix how we count features for buildings, reordering columns in the report

safe/gui/tools/help/dock_help.py, safe/gui/tools/help/osm_downloader_help.py, safe/impact_statistics/postprocessor_manager.py, safe/impact_template/road_report_template.py
CC @ismailsunni 
Some question for this:
- What happened when we 'tr' a dynamic text? Does the base string is generated?
- Alternative way is to extract the specially formatted strings that needs to be translated manually. (Put the generated text manually to transifex?)
=> Translation 3.4

safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/impact_function.py
The problem in issue #2812 is bad path manipulation. No wonder it only fails on Windows.
Fix #2812
=> Fix bad path manipulation on windows.

safe/definitions.py, safe/impact_functions/generic/classified_polygon_landcover/impact_function.py, safe/impact_functions/inundation/tsunami_raster_building/impact_function.py, safe/impact_functions/inundation/tsunami_raster_landcover/impact_function.py, safe/impact_functions/inundation/tsunami_raster_road/impact_function.py
New definitions, new order.
#2721
=> Modify structure class mapping. 

safe/impact_functions/inundation/tsunami_population_evacuation_raster/metadata_definitions.py, safe/impact_functions/inundation/tsunami_raster_building/metadata_definitions.py, safe/impact_functions/inundation/tsunami_raster_landcover/metadata_definitions.py
part fix #1251
citations added
=> Tsunami citations

safe/definitions.py, safe/impact_functions/inundation/tsunami_population_evacuation_raster/metadata_definitions.py, safe/impact_functions/inundation/tsunami_raster_building/metadata_definitions.py, safe/impact_functions/inundation/tsunami_raster_landcover/metadata_definitions.py
update tsunami_raster_hazard_classes
this includes english definitions for 3 classes
Indonesian definitions are available in #1251
=> Tsunami hazard classes fix #1251

safe/gui/widgets/dock.py, safe/impact_functions/generic/classified_polygon_landcover/impact_function.py, safe/impact_functions/generic/classified_polygon_people/impact_function.py, safe/impact_statistics/aggregator.py, safe/postprocessors/age_postprocessor.py, safe/postprocessors/gender_postprocessor.py
For #2846 errors:
- `TypeError, QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'`
- Includes #2854
=> Fix 2846 none sym diff

safe/gui/widgets/dock.py, safe/impact_functions/generic/classified_polygon_landcover/impact_function.py, safe/impact_functions/generic/classified_polygon_people/impact_function.py
@Gustry or @timlinux can you give some comment? I am not sure what I did here actually, just removing None data.
Fixing #2853
=> Handle None geometry and remove too verbose log.

safe/impact_functions/generic/classified_polygon_building/test/test_classified_polygon_building.py, safe/storage/test/test_safe_layer.py, safe/test/data/exposure/buildings.qml, safe/test/data/exposure/buildings.xml
Related to https://github.com/inasafe/inasafe/issues/2915
Now, most of the tests are testing the impact layer only. I think it's not enough, the report should be covered a minimum in each IF.
With the JSON file, it's possible to test the impact summary and the impact table. Can we continue to add these tests to the other IF ? @ismailsunni 
The postprocessor table is not computed at that stage so we can't test it for now.
=> Update buildings keywords and style, add some tests

safe/gui/widgets/dock.py
=> fix legend order when the layer is None

safe/plugin.py, test_suite.py
=> select test package

resources/minimum_needs/SPHERE.json
See issue #1317 
Running on JK Flood ( @Charlotte-Morgan 's favourite! ) I get this:
Note I updated the provenance to be SPHERE not Perka
=> fix #1317 - add minimum needs for SPHERE

safe/gui/ui/options_dialog_base.ui
@NyakudyaA Can you review ? ;-)
See #2925
=> improve labels in settings about layer visible

.travis.yml, qgis_testrunner.sh, safe/gui/tools/test/test_impact_merge_dialog.py, safe/gui/tools/test/test_save_scenario.py, safe/gui/widgets/test/test_dock.py, safe/impact_statistics/test/test_aggregator.py, safe/impact_statistics/test/test_postprocessor_manager.py, safe/plugin.py, safe/utilities/test/test_clipper.py, safe/utilities/test/test_styling.py, test_suite.py
=> Docker in travis

safe/impact_functions/generic/classified_raster_building/impact_function.py
We should fix the "Not Affected" too I think.
=> fix translated legend and attribute table

safe/defaults.py, safe/impact_functions/earthquake/earthquake_building/impact_function.py, safe/impact_functions/generic/classified_polygon_building/impact_function.py, safe/impact_functions/generic/classified_polygon_building/test/test_classified_polygon_building.py, safe/impact_functions/generic/classified_raster_building/impact_function.py, safe/impact_functions/inundation/flood_raster_osm_building_impact/impact_function.py, safe/impact_functions/inundation/flood_vector_building_impact/impact_function.py, safe/impact_functions/inundation/tsunami_raster_building/impact_function.py, safe/impact_functions/volcanic/volcano_point_building/impact_function.py, safe/impact_functions/volcanic/volcano_polygon_building/impact_function.py, safe/impact_reports/building_exposure_report_mixin.py, safe/impact_reports/test/test_building_exposure_report_mixin.py
=> Remove the building threshold fix #2932

safe/impact_reports/road_exposure_report_mixin.py, safe/impact_reports/test/test_road_exposure_report_mixin.py, safe/impact_template/road_report_template.py, safe/impact_template/test/test_road_report_template.py
=> reverse the impact summary for roads report #2950

safe/gui/tools/minimum_needs/needs_manager_dialog.py, safe/gui/tools/minimum_needs/needs_profile.py
=> minimum needs : add a button to restore defaults

README.md
=> Update PyCharm logo

safe/gui/tools/options_dialog.py, safe/report/impact_report.py
[Number_of_people_affected_in_each_class.pdf](https://github.com/inasafe/inasafe/files/363410/Number_of_people_affected_in_each_class.pdf)
=> Fix #2966 - support more formats than just png for custom map north arrow and organsiation logo

safe/definitions.py, safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/earthquake/pager_earthquake_fatality_model/metadata_definitions.py
=> Libby definitions

safe/definitions.py, safe/impact_functions/ash/ash_raster_landcover/metadata_definitions.py, safe/impact_functions/ash/ash_raster_places/metadata_definitions.py, safe/impact_functions/ash/ash_raster_population/metadata_definitions.py, safe/impact_functions/earthquake/earthquake_building/metadata_definitions.py, safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/earthquake/pager_earthquake_fatality_model/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_building/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_landcover/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_people/metadata_definitions.py, safe/impact_functions/generic/classified_polygon_population/metadata_definitions.py, safe/impact_functions/generic/classified_raster_building/metadata_definitions.py, safe/impact_functions/generic/classified_raster_population/metadata_definitions.py, safe/impact_functions/generic/continuous_hazard_population/metadata_definitions.py, safe/impact_functions/inundation/flood_polygon_population/metadata_definitions.py, safe/impact_functions/inundation/flood_polygon_roads/metadata_definitions.py, safe/impact_functions/inundation/flood_raster_osm_building_impact/metadata_definitions.py, safe/impact_functions/inundation/flood_raster_population/metadata_definitions.py, safe/impact_functions/inundation/flood_raster_road/metadata_definitions.py, safe/impact_functions/inundation/flood_vector_building_impact/metadata_definitions.py, safe/impact_functions/inundation/tsunami_population_evacuation_raster/metadata_definitions.py, safe/impact_functions/inundation/tsunami_raster_building/metadata_definitions.py, safe/impact_functions/inundation/tsunami_raster_landcover/metadata_definitions.py, safe/impact_functions/inundation/tsunami_raster_road/metadata_definitions.py, safe/impact_functions/volcanic/volcano_point_building/metadata_definitions.py, safe/impact_functions/volcanic/volcano_point_population/metadata_definitions.py, safe/impact_functions/volcanic/volcano_polygon_building/metadata_definitions.py, safe/impact_functions/volcanic/volcano_polygon_population/metadata_definitions.py
Added formal citation structures to definitions and all impact function metadata. This is not exposed in any reports yet. Where citations do existing (in old citations form or as comments) they were added into the citations structure. defaults.py has not been addressed in this PR.
=> Let there be citations. 

safe/gui/tools/wizard/step_kw42_name_field.py, safe/gui/tools/wizard/step_kw43_population_field.py
@ivanbusthomi I made a fix for your problem about the value mapping
=> remove clear_further_steps in exposure places classify

safe/common/custom_logging.py
=> Fix plugin load error

safe/definitions.py
=> Revised definitions of 'count' and 'density' to provide more clarity for wizard users

safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/metadata_definitions.py
=> shortened description of ITB Bayesian EQ IF to fit into wizard window

safe/definitions.py
Replacement pull request for #3607 after that proliferated and became changes to definitions.py and reporting-standards. This pull request is for the insertion of the displace people and evacuated people definitions into definitions.py only.
=> Definitions partfix #2272 to replace #3067

safe/impact_functions/ash/ash_raster_places/impact_function.py, safe/impact_functions/generic/classified_polygon_population/impact_function.py, safe/impact_functions/generic/classified_raster_building/impact_function.py, safe/impact_functions/generic/classified_raster_population/impact_function.py, safe/impact_functions/generic/continuous_hazard_population/impact_function.py
replace areas with zones
fix capitalisation
replace moderate with medium
replace tsunami with ash in ash IF
=> Part fix #3090 #3091

docs/reporting-standards.md
=> Reporting standards

safe/definitions.py
=> Some notes for roads, volcano, tsunami and places

safe/definitions.py, safe/impact_functions/generic/classified_polygon_landcover/test/test_classified_polygon_landcover.py
added single and multi event notes for volcano - experiment for #3098 
other minor text tweaks
=> Minor text tweaks

safe/definitions.py
add general notes to each hazard
=> part fix #3057

safe/metadata/provenance/provenance_step.py
Add more accepted format for datetime parsing for #3076
=> Add more format for datetime per #3076

resources/css/InaSAFE.css, safe/impact_template/generic_report_template.py, safe/messaging/item/bulleted_list.py
Contents:
- Add custom bullet list style, you can add more of course
- Use tick bullet for action checklist.
Example:
=> Fix #2430 tick bullet

safe/impact_functions/base.py, safe/impact_functions/inundation/flood_polygon_population/impact_function.py, safe/impact_functions/inundation/flood_polygon_roads/impact_function.py, safe/impact_functions/inundation/flood_vector_building_impact/impact_function.py
- Add ZeroImpactException if there is no wet in value mapping.
- Add more explanation why there is no affected area
=> Add zero impact exception if no wet in value mapping. Fix #3108

safe/impact_functions/generic/classified_raster_population/impact_function.py, safe/impact_functions/generic/continuous_hazard_population/impact_function.py, safe/impact_functions/inundation/tsunami_population_evacuation_raster/impact_function.py
For #3089 
I have gone through all IF and added the formatting if needed.
Please check @felix-yew
=> Add thousands separator fix #3089.

safe/impact_statistics/aggregator.py
By pass if there is None geometry for #2798 
Please check @timlinux @Charlotte-Morgan @Gustry
=> Fix #2798 Attribute Error

safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/impact_function.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py, safe/impact_functions/earthquake/pager_earthquake_fatality_model/impact_function.py, safe/test/data/exposure/building-points.xml
=> Fix for #2998 - show correct attribution for each earthquake IF

safe/definitions.py, safe/impact_functions/base.py, safe/impact_functions/earthquake/earthquake_building/impact_function.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py, safe/impact_functions/earthquake/itb_earthquake_fatality_model/test/test_itb_earthquake_fatality_model.py, safe/storage/safe_layer.py, safe/test/data/exposure/buildings.xml
and remove duplication of content in definitions.py. fix #3109
CC @Charlotte-Morgan
=> Support more granular definition of notes 

safe/impact_template/generic_report_template.py
Contents:
- Check if it's Age, Gender, or MinimumNeeds. Skip the total.
cc @Charlotte-Morgan @felix-yew for testing
=> Do not show total if it is Age, Gender, or MinimumNeeds. Fix #3118

metadata.txt
Hi @timlinux 
This is my attempt to add changelog for 3.5. I went through all the closed ticket under 3.5 milestone. Check if it's bug or not, InaSAFE plugin or not, etc.
Perhaps you can add more things or remove some of them.
Please check if I missed some items @lucernae @Gustry
=> Add changelog for 3.5

metadata.txt, safe/gui/widgets/dock.py, safe/impact_functions/base.py, safe/messaging/item/text.py, safe/utilities/analysis_handler.py, safe/utilities/utilities.py
Contents:
- Add custom json writer for InaSAFE that handle NULL and use indent = 2
=> Fix #3153 null value

Makefile
Now, everyone can do translation tasks :)
=> Add make command to run translation tasks via docker.

.travis.yml
See https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
=> Use travis container base. Fix #2150

realtime/earthquake/notify_new_shake.py
Add inotify watches flags for file renames. To accomodate btsync file rename mechanism for big file syncing.
=> Add more inotify watches flag

safe/common/exceptions.py, safe/datastore/datastore.py, safe/datastore/folder.py, safe/datastore/geopackage.py, safe/datastore/test/test_folder.py, safe/datastore/test/test_geopackage.py, safe/gis/gdal_ogr_tools.py
First implementation for the Folder datastore.
Ready to merge this first PR.
I'm going to add some child class to manage  PostGIS/GeoPackage.
We can write shapes and tiffs into a folder and get the list of layers in the datastore.
=> implement Folder datastore

safe/gisv4/raster/reproject.py, safe/gisv4/raster/test/test_reproject.py, safe/gisv4/vector/reproject.py, safe/gisv4/vector/test/test_reproject.py, safe/gisv4/vector/tools.py, safe/utilities/keyword_io.py
- Reproject a vector layer
To fix : 
- Reproject a raster layer
- Keep and update keywords (Memory layer)
If we want to transfer keywords along the processing workflow, this PR assumes we use monkey patching for keywords. We can review this.
=> add reprojection in gis v4

safe/definitionsv4/fields.py, safe/gisv4/vector/buffering.py, safe/gisv4/vector/test/test_buffering.py, safe/gisv4/vector/tools.py, safe/test/debug_helper.py
Can you review it @ismailsunni for the keywords ? Thanks
=> Add hazard class name in the buffering

safe/definitionsv4/processing.py, safe/gisv4/vector/prepare_vector_layer.py, safe/gisv4/vector/test/test_prepare_vector_layer.py, safe/impact_function_v4/test/test_impact_function.py, safe/test/data/exposure/building-points.xml
=> add algorithm to prepare a vector layer

realtime/flood/fixtures/flood_data_classified_state.qml, realtime/flood/flood_event.py, realtime/flood/make_map.py
Just smallfix for:
- Change hazard class style to mimic PetaJakarta.org scheme
- Separate folder for i18n
=> Fix for flood realtime reporting

.travis.yml, qgis_testrunner.sh
This reverts commit 454dfe34aa7d92ec83781c0f9f42b621619cb0c3.
=> Revert "update travis to the latest QGIS 2.14 with boundlessgeo"

safe/definitionsv4/hazard_classifications.py
@ismailsunni @timlinux What do you think ?
=> new hazard classification

safe/definitionsv4/hazard.py, safe/impact_function_v4/impact_function.py
Introduce hazard_classifications to hazard defintions
=> Add hazard_classfications in hazard. PEP8.

safe/definitionsv4/exposure.py, safe/definitionsv4/hazard.py, safe/definitionsv4/layer_purposes.py, safe/definitionsv4/utilities.py
Based on meeting on 18 October 2016.
=> Refactor layer_geometry with allowed_geometries

safe/gui/widgets/dock.py
Note this is a WIP and not ready to merge yet.
@Gustry currently it fails from:
CC @ismailsunni
=> First work to support new impact functions from dock

safe/metadata/base_metadata.py, safe/metadata/test/data/existing_generic.json, safe/metadata/test/data/existing_impact.json, safe/metadata/test/data/existing_impact.xml
Add inasafe_default_values in metadata.
=> Inasafe default value

safe/gui/tools/wizard/step_kw40_classify.py, safe/gui/tools/wizard/wizard_dialog.py
=> Fix if there is no string_default.

safe/definitionsv4/caveats.py, safe/definitionsv4/colors.py, safe/definitionsv4/exposure.py, safe/definitionsv4/hazard.py, safe/definitionsv4/post_processors.py, safe/impact_functions/earthquake/earthquake_building/test/test_earthquake_building.py
=> Updates to definitions and caveats

safe/gisv4/vector/assign_highest_value.py, safe/gisv4/vector/clip.py, safe/gisv4/vector/intersection.py, safe/gisv4/vector/smart_clip.py, safe/gisv4/vector/tools.py, safe/gisv4/vector/union.py, safe/impact_function_v4/impact_function.py, safe/test/data/control/files/test-profiling-logs.txt, safe/utilities/profiling.py
We can improve latter the display for the tree
=> Improve profiling

realtime/ash/ash_event.py, realtime/ash/fixtures/realtime-ash.qpt
=> Update Realtime Ash report

realtime/flood/flood_event.py
Cherry-pick commit from develop
=> Pusdalops new address

safe/definitionsv4/exposure.py, safe/definitionsv4/hazard.py
add caveats for analysis extent and incomplete data
=> Update definitions to use caveats

safe/definitionsv4/exposure.py, safe/definitionsv4/fields.py, safe/definitionsv4/hazard.py, safe/definitionsv4/layer_purposes.py, safe/definitionsv4/test/test_utilities.py, safe/definitionsv4/utilities.py, safe/gui/tools/wizard/step_kw45_inasafe_fields.py, safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py, safe/gui/tools/wizard/test/test_keyword_wizard.py, safe/gui/tools/wizard/wizard_dialog.py, safe/test/utilities.py
=> Compulsory Fields

.checkignore, safe/gui/tools/wizard/step_kw00_purpose.py, safe/gui/tools/wizard/step_kw05_subcategory.py, safe/gui/tools/wizard/step_kw10_hazard_category.py, safe/gui/tools/wizard/step_kw15_layermode.py, safe/gui/tools/wizard/step_kw20_unit.py, safe/gui/tools/wizard/step_kw25_classification.py, safe/gui/tools/wizard/step_kw30_field.py, safe/gui/tools/wizard/step_kw35_resample.py, safe/gui/tools/wizard/step_kw40_classify.py, safe/gui/tools/wizard/step_kw45_inasafe_fields.py, safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py, safe/gui/tools/wizard/step_kw55_source.py, safe/gui/tools/wizard/step_kw60_title.py, safe/gui/tools/wizard/step_kw65_summary.py, safe/gui/tools/wizard/test/test_keyword_wizard.py, safe/gui/tools/wizard/wizard_strings.py, safe/test/data/hazard/classified_flood_20_20.xml
=> Fix 3383 kw wizard classified raster

safe/gui/tools/wizard/step_kw15_layermode.py, safe/gui/tools/wizard/step_kw20_unit.py, safe/gui/tools/wizard/step_kw25_classification.py, safe/gui/tools/wizard/step_kw30_field.py, safe/gui/tools/wizard/step_kw40_classify.py, safe/gui/tools/wizard/step_kw43_threshold.py, safe/gui/tools/wizard/step_kw45_inasafe_fields.py, safe/gui/tools/wizard/test/test_keyword_wizard.py, safe/gui/tools/wizard/wizard_dialog.py, safe/gui/ui/wizard/step_kw43_threshold.ui
Fix issue in wizard flow to match with https://github.com/inasafe/inasafe/issues/3385#issuecomment-259002875
=> Fix issue in wizard flow

safe/definitionsv4/exposure.py, safe/definitionsv4/hazard_classifications.py, safe/definitionsv4/test/test_utilities.py, safe/gui/tools/wizard/step_kw00_purpose.py, safe/gui/tools/wizard/step_kw25_classification.py, safe/gui/tools/wizard/step_kw40_classify.py, safe/gui/tools/wizard/step_kw43_threshold.py, safe/gui/tools/wizard/test/test_keyword_wizard.py, safe/gui/tools/wizard/wizard_dialog.py, safe/gui/ui/wizard/step_kw43_threshold.ui, safe/metadata/hazard_layer_metadata.py, safe/metadata/test/test_hazard_metadata.py, safe/test/data/exposure/census.xml, safe/test/data/gisv4/aggregation/small_grid.xml, safe/test/data/hazard/classified_flood_20_20.xml, safe/test/data/hazard/continuous_flood_20_20.xml, safe/test/data/hazard/continuous_vector.xml, safe/test/data/hazard/volcano_krb.xml, safe/utilities/keyword_io.py
=> Continuous layer wizard

safe/gui/tools/wizard/step_kw20_unit.py, safe/gui/tools/wizard/step_kw35_resample.py, safe/gui/tools/wizard/test/test_keyword_wizard.py
=> Fix allow resample step in kw wizard.

safe/definitionsv4/colors.py, safe/definitionsv4/constants.py, safe/definitionsv4/fields.py, safe/definitionsv4/hazard_classifications.py, safe/gisv4/raster/polygonize.py, safe/gisv4/raster/reclassify.py, safe/gisv4/vector/summary_3_analysis.py, safe/gui/widgets/dock.py, safe/impact_function_v4/create_extra_layers.py, safe/impact_function_v4/impact_function.py, safe/impact_function_v4/test/test_impact_function.py, safe/test/data/scenario/polygon_classified_hazard_on_line_exposure.json, safe/test/data/scenario/polygon_classified_hazard_on_point_exposure.json, safe/test/data/scenario/polygon_classified_hazard_on_vector_population_exposure.json, safe/test/data/scenario/polygon_continuous_hazard_on_line_exposure.json, safe/test/data/scenario/raster_classified_hazard_on_classified_raster.json, safe/test/data/scenario/raster_classified_hazard_on_indivisible_polygons_exposure_grid_aggregation.json, safe/test/data/scenario/raster_classified_hazard_on_line_exposure_grid_aggregation.json, safe/test/data/scenario/raster_continuous_hazard_on_divisible_polygons_exposure_grid_aggregation.json, safe/test/data/scenario/raster_continuous_hazard_on_line_exposure.json, safe/test/data/scenario/raster_continuous_hazard_on_raster_population_exposure.json, safe/test/utilities.py
* Manage no data value
* Rename output
* Add groups in the legend
=> manage no data value when we reclassify and polygonize a raster

safe/impact_function_v4/impact_function.py, safe/impact_function_v4/style.py
It's not the best implementation. It's just to have a basic styling for the alpha release next week.
=> add hazard class legend

safe/reportv4/extractors/action_notes.py, safe/reportv4/extractors/analysis_detail.py, safe/reportv4/extractors/analysis_result.py, safe/reportv4/extractors/impact_table.py, safe/reportv4/extractors/util.py, safe/reportv4/impact_report.py, safe/reportv4/processors/default.py, safe/reportv4/report_metadata.py, safe/reportv4/test/fixtures/controls/impact-function-impact-report-output-1.html, safe/reportv4/test/fixtures/controls/impact-function-impact-report-output-2.html, safe/reportv4/test/test_impact_report.py
Cleanup code and fix impact function reference in impact_report
=> Refactor impact function reference

safe/impact_function_v4/create_extra_layers.py, safe/impact_function_v4/impact_function.py
@ismailsunni I would like to merge this PR when the wizard will generate some 4.0 keywords.
=> check if layer is 4.0 in the IF setup

scripts/inasafe-install, scripts/release.sh
=> Fix 3421 release script

safe/definitionsv4/hazard.py, safe/gui/tools/wizard/step_kw45_inasafe_fields.py, safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py
=> Fix kw wizard

safe/gisv4/vector/assign_highest_value.py, safe/gisv4/vector/test/test_assign_highest_value.py
from 800 seconds to 4 seconds :)
=> improve assign_highest_value by looping over the hazard layer first !"

safe/gisv4/raster/zonal_statistics.py, safe/gisv4/vector/assign_highest_value.py, safe/gisv4/vector/union.py, safe/impact_function_v4/test/test_impact_function.py, safe/metadata/impact_layer_metadata.py, safe/metadata/property/dictionary_property.py, safe/metadata/test/data/existing_impact.json, safe/metadata/test/data/existing_impact.xml
=> Fix 3399 add impact metadata

scripts/release.sh
I have added a notes in https://github.com/inasafe/inasafe/wiki/Preparing-a-release#generate-a-test-package
=> Use git-archive-all to archive submodule.

safe/definitionsv4/exposure.py, safe/definitionsv4/fields.py, safe/definitionsv4/post_processors.py, safe/impact_function_v4/test/test_postprocessors.py
=> Replace women with female.

metadata.txt, safe/impact_functions/earthquake/itb_earthquake_fatality_model/impact_function.py
See #3489
@Gustry Note we need to make sure any fixes in this PR are forward ported to 4.0 branch...
=> Fix problem with affected and displaced counts being incorrectly calculated in ITB EQ Function

metadata.txt, safe/storage/vector.py
No need to back port on this I think...
=> Fix issue when multipart to singlepart results in none geometries.

metadata.txt, safe/impact_functions/loader.py, safe/storage/vector.py
Fix #3497 
Please check @Charlotte-Morgan
=> Make ITB Bayesian IF as default. Fix #3497.

safe/gui/ui/batch_dialog_base.ui, safe/gui/ui/extent_selector_dialog_base.ui, safe/gui/ui/function_options_dialog_base.ui, safe/gui/ui/help_dialog_base.ui, safe/gui/ui/impact_merge_dialog_base.ui, safe/gui/ui/impact_report_dialog_base.ui, safe/gui/ui/needs_calculator_dialog_base.ui, safe/gui/ui/needs_manager_dialog_base.ui, safe/gui/ui/options_dialog_base.ui, safe/gui/ui/osm_downloader_dialog_base.ui, safe/gui/ui/peta_jakarta_dialog_base.ui, safe/gui/ui/raster_reclassify_dialog_base.ui, safe/gui/ui/shakemap_importer_dialog_base.ui, safe/gui/ui/wizard/step_kw65_summary.ui
shouldent this be like this?
I keep on getting error if I dint change
=> replace QtWebkitWidgets/QWebView to PyQt4.QtWebKit

resources/img/definitions/adult.svg, resources/img/definitions/definitions.lic, resources/img/definitions/elderly.svg, resources/img/definitions/female.svg, resources/img/definitions/people.svg, resources/img/definitions/youth.svg, safe/defaults.py, safe/definitionsv4/concepts.py, safe/impact_functions/earthquake/itb_bayesian_earthquake_fatality_model/test/test_itb_bayesian_earthquake_fatality_model.py, safe/test/test_defaults.py
=> Infographic icons

realtime/flood/flood_event.py
Related [comment](https://github.com/inasafe/inasafe/issues/3343#issuecomment-259032502).
=> [issues_3343] Fix truncated address

safe/definitionsv4/colors.py, safe/definitionsv4/font.py, safe/definitionsv4/hazard.py, safe/definitionsv4/test/test_utilities.py, safe/definitionsv4/utilities.py, safe/gui/tools/wizard/step_fc00_functions1.py, safe/gui/tools/wizard/step_fc05_functions2.py, safe/gui/tools/wizard/step_fc10_function.py, safe/gui/tools/wizard/step_fc15_hazlayer_origin.py, safe/gui/tools/wizard/step_fc20_hazlayer_from_canvas.py, safe/gui/tools/wizard/step_fc25_hazlayer_from_browser.py, safe/gui/tools/wizard/step_fc30_explayer_origin.py, safe/gui/tools/wizard/step_fc35_explayer_from_canvas.py, safe/gui/tools/wizard/step_fc40_explayer_from_browser.py, safe/gui/tools/wizard/step_fc45_disjoint_layers.py, safe/gui/tools/wizard/step_fc50_agglayer_origin.py, safe/gui/tools/wizard/step_fc55_agglayer_from_canvas.py, safe/gui/tools/wizard/step_fc60_agglayer_from_browser.py, safe/gui/tools/wizard/step_fc65_agglayer_disjoint.py, safe/gui/tools/wizard/step_fc70_extent.py, safe/gui/tools/wizard/step_fc75_extent_disjoint.py, safe/gui/tools/wizard/step_fc80_params.py, safe/gui/tools/wizard/step_fc85_summary.py, safe/gui/tools/wizard/step_fc90_analysis.py, safe/gui/tools/wizard/wizard_dialog.py, safe/gui/tools/wizard/wizard_step_browser.py, safe/utilities/resources.py
Previously it shows all geometries, now it's only show allowed geometries based on the exposure and hazard.
=> Fix 2nd step of the IFCW

safe/messaging/__init__.py, safe/metadata/__init__.py, safe/metadata/property/__init__.py
=> Fix more landscape suggestion.

safe/defaults.py, safe/definitionsv4/default_settings.py, safe/gui/tools/options_dialog.py, safe/gui/tools/test/test_options_dialog.py, safe/test/test_defaults.py
- Add default InaSAFE settings
- Fix bug that some setting is never stored
=> Fix various bugs in Option Dialog and Settings

safe/definitionsv4/default_settings.py, safe/gui/tools/options_dialog.py, safe/gui/tools/test/test_options_dialog.py
I can't resist to make it sooner. Still need to fix here and there, but I think it's much better than 3-4 days ago. I will continue working on this option dialog after provenance.
cc @lucernae
=> Use loop to set and restore option dialog.

safe/impact_function_v4/impact_function.py, safe/impact_function_v4/test/test_impact_function.py, safe/metadata/exposure_impacted_layer_metadata.py, safe/metadata/test/data/existing_impact.json, safe/metadata/test/data/existing_impact.xml
@lucernae please list the things that you need for reporting or anything. I will add in the provenance. Or you can add it easily.
=> Provenance

safe/gui/tools/wizard/step_kw25_classification.py
when using categorized data selected_unit is none
and we need to ignore it when choosing the correct categorisations
=> multi unit classifications for categorized data

safe/definitionsv4/hazard_classifications.py
replace cyclone with hurricane in NOAA NHC scale
=> Fix class names for hurricane scale

safe/impact_function/impact_function.py, safe/impact_function/test/test_impact_function.py
We need to know why we have this bug.
=> trying to check this random bug in the IF

safe/datastore/test/test_folder.py, safe/test/utilities.py
* We don't use the get_qgis_app, we use the iface provided by QGIS.
* We don't execute code before an import, it's gonna be good for landscape ;-)
=> try to use the mocked QGIS interface

safe/gui/tools/save_scenario.py
a small change to match changes in dock.extent in order to fix error in saving scenario for batchrunner.
=> update crs saving to match changes in dock.extent

safe/impact_function/style.py
=> add conditional formatting to the attribute table

safe/gisv4/raster/align.py, safe/gisv4/raster/rasterize.py, safe/gui/widgets/dock.py, safe/impact_function/impact_function.py
Support for damage curve analysis
=> Support for damage curve analysis

resources/report-templates/standard-template/jinja2/infographic-layout.html, resources/report-templates/standard-template/jinja2/population-infographic.html, safe/gui/analysis_utilities.py, safe/gui/widgets/dock.py, safe/report/extractors/aggregate_postprocessors.py, safe/report/extractors/aggregate_result.py, safe/report/extractors/analysis_detail.py, safe/report/extractors/analysis_result.py, safe/report/extractors/impact_table.py, safe/report/extractors/infographics.py, safe/report/extractors/minimum_needs.py, safe/report/extractors/util.py, safe/report/impact_report.py, safe/report/report_metadata.py, safe/report/test/test_impact_report.py
Papercut fixes for impact report
=> Papercut fixes

docs/reporting-standards.md
=> Update reporting and mapping standards

safe/definitions/exposure.py, safe/gisv4/vector/prepare_vector_layer.py, safe/gisv4/vector/summary_1_aggregate_hazard.py, safe/gisv4/vector/test/test_prepare_vector_layer.py, safe/impact_function/test/test_impact_function.py, safe/report/test/test_impact_report.py, safe/test/data/exposure/building-points.xml, safe/test/data/gisv4/exposure/building-points.xml, safe/test/data/gisv4/exposure/buildings.xml, safe/test/data/scenario/polygon_classified_on_point.json
Removing population, female, age ratio and count field from exposure.
Question: should I remove also population count from exposure place?
cc @timlinux @Charlotte-Morgan
=> Remove population ratio and count from exposure.

safe/common/minimum_needs.py, safe/definitions/minimum_needs.py, safe/definitions/post_processors.py, safe/gui/analysis_utilities.py, safe/gui/widgets/dock.py, safe/report/extractors/aggregate_postprocessors.py, safe/report/extractors/composer.py, safe/report/impact_report.py, safe/report/processors/default.py, safe/report/report_metadata.py, safe/test/data/scenario/polygon_classified_on_vector_population.json, safe/test/data/scenario/raster_continuous_on_raster_population.json
- Add female hygiene and additional rice minimum needs
- Add error handler in report generations
- Fix map title
=> Add female hygiene and rice minimum needs calculations

resources/report-templates/standard-template/definitions, resources/report-templates/standard-template/jinja2/aggregation-postprocessors.html, resources/report-templates/standard-template/qgis-composer, safe/definitions/fields.py, safe/definitions/minimum_needs.py, safe/definitions/post_processors.py, safe/definitions/report.py, safe/impact_function/postprocessors.py, safe/report/extractors/aggregate_postprocessors.py
- Move hygiene packs and additional rice as postprocessors
=> Move hygiene packs and additional rice as postprocessors

safe/definitions/exposure.py, safe/definitions/hazard.py, safe/gui/tools/wizard/step_fc00_functions1.py, safe/gui/tools/wizard/test/test_keyword_wizard.py, safe/gui/tools/wizard/wizard_dialog.py
=> Fix 3637 wizard dev mode

Makefile, scripts/missing_translations.py
Use docker to make the translations command.
=> Update command for translation.

safe/definitions/exposure.py, safe/impact_function/impact_function.py, safe/impact_function/provenance_utilities.py, safe/impact_function/test/test_impact_function.py, safe/impact_function/test/test_provenance_utilities.py
=> Map question

resources/report-templates/standard-template/jinja2/population-infographic.html, safe/report/extractors/infographics.py
Fix for report generation error in issue #3615 and #3617
=> Fix infographic error when vulnerability not found

safe/common/exceptions.py, safe/gui/tools/options_dialog.py, safe/gui/ui/options_dialog_base.ui, safe/impact_function/earthquake.py, safe/impact_function/impact_function.py
* Default EQ set to ITB bayesian #3654 
* Rename function according to #3654 and #3497
=> change the EQ output raster to displaced people

safe/definitions/exposure.py, safe/definitions/units.py, safe/gis/raster/rasterize.py, safe/impact_function/earthquake.py, safe/impact_function/impact_function.py, safe/impact_function/style.py, safe/report/extractors/aggregate_postprocessors.py, safe/report/extractors/aggregate_result.py, safe/report/extractors/analysis_detail.py, safe/report/extractors/analysis_result.py, safe/report/extractors/infographics.py, safe/report/extractors/minimum_needs.py, safe/report/extractors/util.py, safe/utilities/rounding.py
* The legend : 
* The report :
@lucernae : 
* We need to check why we don't get the same rounding. Numbers should match between the legend and the report.
* You need to add a new row I think for not exposed according to the new diagram :
=> Update the map legend

safe/gis/vector/clip.py, safe/gis/vector/intersection.py, safe/gis/vector/union.py
This is the backport from @wonder-sk in QGIS.
This is not my code. I think we can just merge it.
=> fix union algo from https://github.com/qgis/QGIS/pull/4037

safe/gis/vector/prepare_vector_layer.py, safe/gui/tools/minimum_needs/needs_calculator_dialog.py, safe/gui/tools/minimum_needs/test/test_minimum_needs_tool.py, safe/gui/ui/needs_calculator_dialog_base.ui
- use Qgis combo box object
- use the new post processor
=> fix minimum needs calculator to use the new post-processor

safe/definitions/caveats.py, safe/definitions/concepts.py, safe/definitions/exposure.py, safe/report/test/test_impact_report.py
=> revised population exposure concepts

safe/datastore/datastore.py, safe/datastore/folder.py, safe/datastore/geopackage.py
=> add method the get URI of the datastore as a string

safe/definitions/colors.py, safe/impact_function/impact_function.py, safe/impact_function/style.py
Before : 
After : 
I think I still need some time to improve it. But let's merge this one first.
CC : @felix-yew
=> add labels according to standards in the legend

resources/img/icons/show-multi-buffer.svg, safe/definitions/fields.py, safe/gis/vector/multi_buffering.py, safe/gis/vector/test/test_multi_buffering.py, safe/gui/tools/help/definitions_help.py, safe/gui/tools/help/multi_buffer_help.py, safe/gui/tools/multi_buffer_dialog.py, safe/gui/tools/test/test_multi_buffer.py, safe/gui/ui/multi_buffer_dialog_base.ui, safe/plugin.py
Ready to hear any comments :smiley:
=> add new tool: multi-buffer

safe/definitions/constants.py, safe/definitions/minimum_needs.py, safe/gis/vector/summary_1_aggregate_hazard.py
This is more about absolute values.
Ticket : https://github.com/inasafe/inasafe/issues/3759
First I'm checking which tests are failing. (cc @ismailsunni )
=> Fix minimum needs calculation in the waterfall

safe/gui/tools/options_dialog.py, safe/gui/ui/options_dialog_base.ui
=> add button for restore default ratio

safe/common/parameters/default_select_parameter_widget.py, safe/common/parameters/default_value_parameter_widget.py, safe/common/parameters/test/test_default_select_parameter_widget.py, safe/common/parameters/test/test_default_value_parameter_widget.py, safe/common/parameters/test/test_resource_parameter_widget.py, safe/gui/tools/wizard/step_kw45_inasafe_fields.py
=> Update from parameters package.

safe/gis/vector/clean_geometry.py
Issue #3783 from @ivanbusthomi
=> remove features if the geometry is None

safe/gui/tools/minimum_needs/needs_manager_dialog.py
=> remove useless code about IF function combobox in minimumneeds dialog

safe/definitions/hazard.py, safe/definitions/test/test_utilities.py, safe/gui/tools/wizard/step_kw30_field.py, safe/gui/tools/wizard/wizard_strings.py, safe/test/data/gisv4/hazard/classified_vector.xml
=> Fix 3619 missing constant

safe/definitions/fields.py, safe/definitions/post_processors.py, safe/impact_function/impact_function.py, safe/impact_function/test/test_postprocessors.py
We need to check that.
@lucernae Is it linked to https://github.com/inasafe/inasafe/issues/3664 ?
=> review strings displaced/affected in postprocessors

safe/gui/tools/help_dialog.py, safe/gui/ui/help_dialog_base.ui
Note that the non-modal behavior was already there for me. Added minimize/maximize buttons. See #3780
=> Make help non-modal and minimazable / maximizable

safe/gui/widgets/dock.py, safe/impact_function/impact_function.py
=> check if the hazard can run on the exposure

safe/utilities/keyword_io.py
=> Fix 3791 keyword in dock

AUTHORS.rst, safe/definitions/hazard.py, safe/definitions/hazard_classifications.py, safe/definitions/units.py
=> cyclone fixes

safe/gui/tools/wizard/step_fc90_analysis.py, safe/gui/tools/wizard/test/test_keyword_wizard.py
=> Fix IFCW extent error 

safe/gui/tools/wizard/step_kw33_multi_classifications.py, safe/gui/tools/wizard/test/test_keyword_wizard.py, safe/utilities/keyword_io.py
- Show current value maps
- Disable next button when there is no classification selected
- Disable next button when still in editing mode
- Directly open edit panel after changing the combobox
- Disable load button
=> WIP Fix 3789 multi classification wizard

safe/gis/vector/summary_3_analysis.py, safe/gis/vector/summary_4_exposure_breakdown.py
Ticket #3812 
Can you check @samnawi ?  Thanks
=> disable sanity check in summary calculation

resources/petajakarta/flood-keywords.xml, safe/gui/tools/peta_jakarta_dialog.py
- upgrade keywords template
- fix url
=> fix issue #3752: fix url for PetaBencana.id

safe/definitions/post_processors.py, safe/definitions/report.py, safe/gui/widgets/dock.py, safe/report/extractors/aggregate_postprocessors.py, safe/report/extractors/infographics.py, safe/report/test/test_impact_report.py
- Zero rows should not be displayed in aggregation table
- fix issue #3792: Value Error when generating infographic
- make analysis exited if report generation encountered an error
=> fix issue #3787: zero rows should not be displayed

safe/gui/analysis_utilities.py, safe/gui/tools/minimum_needs/test/test_minimum_needs_tool.py, safe/gui/tools/wizard/step_fc90_analysis.py, safe/gui/widgets/dock.py, safe/impact_function/impact_function.py, safe/report/test/test_impact_report.py
=> avoid adding default ratios to a raster exposure layer

safe/definitions/exposure.py, safe/definitions/fields.py, safe/definitions/post_processors.py, safe/gui/tools/wizard/test/test_keyword_wizard.py
=> disable size_rate postprocessor

safe/definitions/default_settings.py, safe/gui/tools/options_dialog.py, safe/gui/ui/options_dialog_base.ui, safe/impact_function/style.py
* Description : Remove option about conditional formating.
The attribute table has never been aligned.
It's Christmas again :
=> remove options about conditional styling

safe/common/parameters/default_select_parameter_widget.py, safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py, safe/gui/tools/wizard/test/test_keyword_wizard.py
=> fix radio button behaviour on inasafe default step

safe/definitions/hazard.py
* Ticket #3823 
- More filter according to the ticket.
=> Fix 3823 filter ifcw

safe/gui/tools/wizard/step_fc55_agglayer_from_canvas.py, safe/gui/tools/wizard/step_fc60_agglayer_from_browser.py
* Ticket #3827 
* Description : Change IF wizard step to the summary step after aggregation layer is selected by the user
=> skip extent selector if aggregation layer is selected

safe/gui/tools/batch/batch_dialog.py, safe/gui/ui/batch_dialog_base.ui
Fix batchrunner map pdf not showing proper layer due to some strange bug where loaded layer is not recognised by InaSAFE or QGIS
=> Fix batchrunner

safe/impact_function/provenance_utilities.py, safe/report/extractors/analysis_result.py
* Ticket #3743 
* Description : Fix some unicode problems
=> fix some unicode in French

safe/gui/tools/wizard/step_kw33_multi_classifications.py, safe/gui/tools/wizard/step_kw43_threshold.py, safe/gui/tools/wizard/wizard_strings.py
* Ticket #3846 
- Fix bug in thresholds
- Update min and max label
- Use True minimum value in raster data (no longer -99999)
=> Fix bug in thresholds classification.

safe/definitions/styles.py, safe/gis/raster/reclassify.py, safe/gis/vector/reclassify.py
* Ticket #3849
* Description : It should fix minimum and maximum in the GIS overlay analysis.
=> fix minimum and maximum thresholds

safe/gui/tools/peta_jakarta_dialog.py
* Ticket #3834 
* Description : replace import with FileDownloader
=> use FileDownloader instead of python's import

safe/gui/tools/minimum_needs/needs_profile.py
=> change min needs profile path to ~/.qgis2/inasafe/minimum_needs

safe/report/extractors/aggregate_result.py, safe/report/test/test_impact_report.py
* Ticket #3861
* Description : handle big numbers in aggregation.
=> fix issue #3861: Flood on buildings with no aggregation fails

safe/gui/widgets/dock.py, safe/report/extractors/util.py
* Ticket #3743 
* Description : Open HTML in UTF8
I've done some landscape quick review
=> open HTML in UTF8

safe/definitions/post_processors.py, safe/gui/ui/needs_calculator_dialog_base.ui, safe/impact_function/impact_function.py
* Description : Some typos in English
=> fix some english strings

.github/ISSUE_TEMPLATE.md
* Description : improve ticket template
=> improve ticket template

.github/PULL_REQUEST_TEMPLATE.md, safe/impact_function/impact_function.py
* Ticket None
* Description : Improve PR template
=> add funded by in PR template

safe/datastore/datastore.py, safe/datastore/folder.py, safe/definitions/post_processors.py, safe/gis/sanity_check.py, safe/gis/vector/intersection.py, safe/gis/vector/prepare_vector_layer.py, safe/gis/vector/test/test_intersection.py, safe/gui/widgets/dock.py, safe/impact_function/impact_function.py, safe/impact_function/test/test_impact_function.py
* Ticket #3812 
* Funded by : DFAT/WB
* Description : Add more sanity check along the IF
=> Checking why some layers wrong

safe/gui/tools/minimum_needs/needs_profile.py
* Ticket #3810 
* Description : # Ignore empty root_directory to avoid load min needs profile to test directory when test is running.
=> needs profile patch. ignore empty root_directory

safe/gui/widgets/dock.py, safe/impact_function/impact_function.py
* Description : Fix dock behaviour when the impact function is None for reporting
=> fix impact function is None in Dock for reporting

safe/common/parameters/default_select_parameter.py, safe/common/parameters/default_select_parameter_widget.py, safe/definitions/fields.py, safe/gui/tools/options_dialog.py, safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py
* Ticket #3579 #3749 
- Swap between help_text and descriptions in wizard (#3749)
- Add min max in custom value in InaSAFE field (#3579)
- Always set first tab in InaSAFE option to be opened.
=> Parameter and Wizard polishing

safe/definitions/fields.py, safe/definitions/hazard.py, safe/definitions/hazard_classifications.py, safe/definitions/test/test_utilities.py, safe/gis/vector/union.py, safe/gui/tools/wizard/step_kw33_multi_classifications.py
@charlotte-morgan PetaJakarta doesnt give class names for the different thresholds - I have used high/medium/low for now - feel free to suggest better names and also any tweaks to the descriptions you may like.
=> Fix #3667 - add petaJakarta flood thresholds

safe/gui/tools/save_scenario.py
* Ticket #3700 
* Description : Currently batch runner cannot read relative path, for now we need the save scenario tool to give absolute path.
=> change relative path to absolute path

safe/definitions/concepts.py, safe/definitions/constants.py, safe/definitions/hazard_classifications.py
* Ticket #3849 
- We no longer need small number as hacky number. We prefer to use > or < operator in the calculation.
=> Remove small number hacky fix.

safe/gui/tools/wizard/step_kw33_multi_classifications.py, safe/gui/tools/wizard/step_kw43_threshold.py
* Description : Avoid using QgsMapLayer.source() and use the QGIS API instead.
=> avoid using QgsMapLayer.source() and use QGIS api instead

safe/definitions/reports/components.py, safe/report/extractors/action_notes.py, safe/report/test/test_impact_report.py
* Ticket #3877
* Description : Add generic template of displacement rates description in the notes
=> fix issue #3877: Add displacement rates description in the notes

safe/gui/analysis_utilities.py, safe/gui/tools/options_dialog.py
* Ticket #3880
* Description : Link InaSAFE option to standard map report
=> fix issue #3880: Making InaSAFE option linked with map report

safe/gui/tools/help/needs_calculator_help.py, safe/gui/ui/needs_calculator_dialog_base.ui
* Ticket #3645 
* Description : UI patch to PR #3645
=> fix needs calculator ui

resources/report-templates/standard-template/jinja2/aggregation-postprocessors.html, resources/report-templates/standard-template/jinja2/aggregation-result.html, resources/report-templates/standard-template/jinja2/analysis-detail.html, resources/report-templates/standard-template/jinja2/analysis-result.html, resources/report-templates/standard-template/jinja2/bullet-list-section.html, resources/report-templates/standard-template/jinja2/minimum-needs.html, resources/report-templates/standard-template/jinja2/population-infographic.html, safe/definitions/reports/components.py, safe/definitions/styles.py, safe/definitions/units.py, safe/report/extractors/analysis_detail.py, safe/report/extractors/analysis_result.py, safe/report/test/test_impact_report.py
* Tickets:
- #2691
- #3898
- fix issue #2691
- add separate background highlight in detailed report
- capitalize headers
=> Improve report table

safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py, safe/gui/tools/wizard/wizard_dialog.py, safe/test/data/aggregation/district_osm_jakarta.xml
* Ticket #3579 
- Make sure the sum of ratio is 1
=> make sure sum of the ratio is 1.

safe/report/extractors/action_notes.py
* Ticket #: No ticket number
* Description : Small fix for possible key error.
=> fix notes failing when there is no displacement

safe/gis/vector/tools.py, safe/impact_function/create_extra_layers.py, safe/impact_function/impact_function.py, safe/impact_function/test/test_impact_function.py
* Ticket #3713 
* Description : Fix geometries on the fly for the the aggregation layer
=> fix geometries on the fly for the aggregation layer

safe/definitions/hazard.py, safe/definitions/hazard_classifications.py
Volcanic ash exposure
* Ticket #3781
Update volcanic ash with exposures, displacement rates and notes from…
=> Volcanic Ash exposures, displacement and notes

safe/gis/vector/tools.py, safe/gui/tools/minimum_needs/needs_calculator_dialog.py
=> handle none geometry

safe/gui/tools/minimum_needs/needs_profile.py
=> fix min needs manager not showing min needs profile

safe/gis/vector/multi_buffering.py, safe/gui/tools/help/multi_buffer_help.py, safe/gui/tools/multi_buffer_dialog.py, safe/gui/tools/test/test_multi_buffer.py, safe/gui/ui/multi_buffer_dialog_base.ui, safe/plugin.py
* Ticket #3893 
* Description : add keywords to the output, ordered distance input
=> Multi buffer patch

safe/gis/vector/default_values.py, safe/gui/tools/peta_bencana_dialog.py, safe/gui/tools/wizard/step_kw30_field.py, safe/gui/tools/wizard/step_kw33_multi_classifications.py, safe/gui/tools/wizard/test/test_keyword_wizard.py, safe/impact_function/provenance_utilities.py, safe/utilities/keyword_io.py
* Ticket : No ticket number. Reported by @Charlotte-Morgan 
- Use MMI Scale for Earthquake on Population classification
- Fix translation issue
=> Fix default eq raster population

safe/gui/tools/wizard/wizard_utils.py
* Ticket #3846 
* Description : fix clear_layout function
=> fix scrambling wizard

safe/definitions/concepts.py, safe/definitions/default_settings.py, safe/definitions/layer_purposes.py, safe/gui/tools/help/dock_help.py, safe/gui/ui/dock_base.ui, safe/gui/widgets/dock.py
* Ticket #3933
* Update question area if the aggregation has some selected features
* Make selected features True by default
* Fix dock not showing report at the end of an IF
=> improvements in dock

safe/definitions/hazard_classifications.py
* Description : Improve the value mapping by adding some default values.
@ismailsunni Do we check these strings by making values in attribute value lowercase ? Do we also check if a translation is available ?
=> add some default values into the hazard classifications

safe/gui/tools/save_scenario.py
* Ticket #3895 
* Description : Fix when we save a scenario with a user_extent
=> fix save scenario

resources/report-templates/standard-template/jinja2/impact-report-layout.html, resources/report-templates/standard-template/jinja2/mmi-detail.html, safe/definitions/reports/components.py, safe/report/extractors/impact_table.py, safe/report/extractors/mmi_detail.py, safe/report/extractors/population_chart.py, safe/report/test/test_earthquake_report.py
* Ticket #3666 
- add fatalities and displaced rows in analysis results
- add MMI Section to show exposed, displaced, and fatalities
=> additional customization for earthquake report

safe/definitions/fields.py
* Ticket #3678 
* Funded by : World Bank
* Description : Remove string concatenation, these strings are missing on transifex.
=> remove strings concatenation, they are missing in transifex

safe/test/debug_helper.py
* Ticket #
* Description : improve some debug helpers if the CRS is not in 4326
=> improve some debug helpers if the CRS is not in 4326

safe/definitions/fields.py, safe/definitions/post_processors.py, safe/impact_function/test/test_postprocessors.py, safe/test/data/scenario/polygon_classified_on_vector_population.json, safe/test/data/scenario/raster_continuous_on_raster_population.json
* Description : add displacement ratio to the attribute table
=> add displacement ratio to the attribute table

safe/gis/raster/reclassify.py, safe/gui/tools/shake_grid/shake_grid.py, safe/gui/tools/shake_grid/shakemap_converter_dialog.py, safe/utilities/styling.py
* Ticket #3874 
* Description : half decimal on either side of the mmi level get assigned eg. 0.5 - 1.5 get reclassed as 1
=> Shakemap importer (reclassify raster)

safe/gui/tools/wizard/step_kw33_multi_classifications.py, safe/gui/tools/wizard/wizard_utils.py
* Ticket #3945 
* Description : fix another scrambling wizard and greyed out combobox besides EQ on pop
=> another scrambling kcw and greyed out combobox

safe/impact_function/impact_function.py
* Description : Do not display passwords in layer source
=> use publicSource instead of source on QgsMapLayer

safe/gis/raster/reclassify.py, safe/gui/tools/shake_grid/shake_grid.py
* Ticket #3953 
* Description : fix PR comment
=> use source instead of publicSource on reclassify function

safe/definitions/exposure.py, safe/definitions/post_processors.py, safe/definitions/units.py, safe/gis/vector/recompute_counts.py, safe/gis/vector/test/test_recompute_counts.py, safe/gis/vector/tools.py, safe/impact_function/postprocessors.py, safe/impact_function/test/test_postprocessors.py, safe/utilities/rounding.py, safe/utilities/test/test_rounding.py
* Ticket #3742 
* Description : Convert unit in size postprocessor if needed
@lucernae I noticed your were already displaying hectare. But values were never in hectare yet ;-)
We should read definitions.
=> convert unit, for landcover from square metres to hectare for instance

safe/definitions/exposure.py, safe/definitions/hazard.py, safe/definitions/hazard_classifications.py
=> Minor updates to affected status and notes

safe/definitions/hazard.py
* Ticket #3932 
All exposure for volcanic ash are enabled now.
=> Fix #3932 Re-enable all exposure for volcanic ash.

safe/definitions/hazard.py, safe/definitions/hazard_exposure_notes_actions.py, safe/impact_function/impact_function.py
* Ticket #3961
* Description : add notes and actions which are specific for a hazard and an exposure
=> add notes and actions which are specific for a hazard and an exposure

safe/definitions/exposure.py, safe/impact_function/style.py, safe/utilities/rounding.py
* Ticket #3742 
* Description : use kilometres if possible in the legend
I think we need to do the same in reporting. (cc @lucernae @myarjunar )
=> use kilometres if possible in the legend

safe/definitions/fields.py, safe/gis/vector/clip.py, safe/gis/vector/intersection.py, safe/gis/vector/union.py
* Ticket #3972 
* Description : Based on our discussion on zoom this morning, I noticed some papercuts.
=> small papercuts

safe/gui/tools/batch/batch_dialog.py, safe/gui/ui/batch_dialog_base.ui
=> handle json file on batch runner + ui polish

safe/utilities/styling.py
=> .. versionadded:: 4.0

safe/gui/ui/options_dialog_base.ui
* Ticket : Discussion from @Charlotte-Morgan and @hadighasemi 
* Description : update label about default EQ fatality function
=> update label about default EQ fatality function

safe/gis/vector/tools.py, safe/report/processors/default.py
* Ticket #3860
* Description : remove deprecated functions from the QGIS API
=> remove deprecated functions from the QGIS api

resources/report-templates/standard-template/jinja2/aggregation-result.html, safe/definitions/reports/components.py, safe/report/extractors/aggregate_result.py, safe/report/extractors/analysis_detail.py, safe/report/test/test_impact_report.py
* Ticket: quickfix
* Description : Added unit in table header
=> add unit for table header in analysis detail and aggregation result

safe/definitions/fields.py
* Ticket #
* Description : More checks to make sure long text goes in pop out area
=> Fix for fields help so that short text is visible long text is hidden

safe/definitions/reports/__init__.py, safe/report/extractors/action_notes.py, safe/report/extractors/aggregate_postprocessors.py, safe/report/extractors/aggregate_result.py, safe/report/extractors/analysis_detail.py, safe/report/extractors/analysis_question.py, safe/report/extractors/composer.py, safe/report/extractors/general_report.py, safe/report/extractors/impact_table.py, safe/report/extractors/infographic_elements/svg_charts.py, safe/report/extractors/infographics.py, safe/report/extractors/minimum_needs.py, safe/report/extractors/mmi_detail.py, safe/report/extractors/population_chart.py, safe/report/extractors/util.py, safe/report/impact_report.py, safe/report/processors/default.py, safe/report/report_metadata.py, safe/report/test/test_earthquake_report.py, safe/report/test/test_impact_report.py, safe/report/test/test_report_metadata.py
* Ticket: quickfix
* Description : Tidying up docstring.
=> tidying up docstring

safe/common/dynamic_translations.py, safe/utilities/keyword_io.py, safe/utilities/test/test_keyword_io.py
* Ticket #3887
* Funded by : World Bank
* Description : add some missing translations in dock
Can you merge this @ismailsunni and update transifex ? 
Thanks
Sorry for these last strings
=> add some missing translations in dock

safe/datastore/datastore.py, safe/gis/vector/summary_33_eq_raster_analysis.py, safe/impact_function/earthquake.py, safe/impact_function/impact_function.py
* Ticket #3803 
* Fix a unicode problem in French
* Fix some small inner rings in the analysis extent
=> Key error eq

safe/gui/widgets/dock.py
* Ticket #3972 
* Description : Make sure current selected exposure layer is used on current IF.
=> anticipate inactive exposure layer

safe/definitions/hazard_classifications.py
* Ticket #3762 
- Update displaced rate for cyclone
- Remove fatality rate for every hazard
=> Displaced rate

safe/definitions/exposure.py, safe/definitions/exposure_classifications.py
=> add landcover definition from badan geologi for volcanic ash

safe/gui/tools/wizard/step_kw33_multi_classifications.py, safe/gui/tools/wizard/test/test_keyword_wizard.py
* Ticket # No ticket number
- Clean invalid classification
=> Clean invalid classification before save the keywords.

CHANGELOG, metadata.txt
* Funded by :  DFAT
* Description : Updated changelog for release
=> Updated metadata.txt and CHANGELOG for 4.0 release

CHANGELOG, metadata.txt
=> Merge develop to master

safe/gui/tools/wizard/step_fc90_analysis.py, safe/gui/widgets/dock.py
* Ticket #3997 
* Description : Generate the map report in IFCW too
=> generate map report in IFCW too

safe/definitions/earthquake.py, safe/definitions/exposure.py, safe/definitions/fields.py, safe/definitions/hazard.py, safe/definitions/hazard_exposure_notes_actions.py, safe/gui/tools/help/definitions_help.py, safe/gui/tools/help_dialog.py, safe/impact_function/impact_function.py
* Ticket : a little bit in #3906
* Description : Notes which are EQ specifics were missing before.
I'm sorry Tim, I don't know too much how we can display these notes in the help.
=> add missing notes for EQ impact function

safe/definitions/styles.py, safe/impact_function/earthquake.py, safe/impact_function/impact_function.py
* Reported by @timlinux on gitter, also #3996 
* Fix no_data in displaced raster
* Fix title for the aggregation layer
* Fix analysis extent in displaced raster
* Display the displaced raster in PDF report
=> fix title and displaced raster in EQ IF

safe/report/extractors/aggregate_result.py, safe/test/data/gisv4/exposure/roads.xml
* Ticket #3887 
* Funded by : WordBank
* Description : Add translatations in the aggregation report
=> add missing translations in aggregation report

metadata.txt
* Ticket No ticket
Set back to alpha version for developer branch.
=> Set back to alpha version for develop branch

safe/definitions/concepts.py, safe/definitions/hazard_classifications.py, safe/gui/tools/wizard/wizard_utils.py, safe/gui/widgets/message.py
* Funded by : WorldBank
* Description : Add some missing translations in Transifex
=> missing translations

safe/utilities/rounding.py, safe/utilities/test/test_rounding.py
* Ticket #4033 
* Description : Fix the fatality range
=> fix fatality range

safe/gis/raster/rasterize.py
* Ticket #3980 
* Description : Disable the bash window
Can you try @timlinux on Windows® ?
=> disable GDAL bash window on windows

safe/gui/tools/options_dialog.py
* Ticket #3538 
- Make the default fields in order
=> Sort global default values in options dialog.

safe/definitions/styles.py, safe/gis/raster/clip_bounding_box.py, safe/gis/raster/test/test_clip_bounding_box.py, safe/gis/sanity_check.py, safe/gui/widgets/dock.py, safe/utilities/gis.py, safe/utilities/test/test_gis.py
* Ticket #4026 #3655 
* Description : Manage raster which are upside-down, make a buffer on the analysis raster
=> skip clip raster by extent if the layer is invalid

safe/impact_function/impact_function.py, safe/impact_function/test/test_impact_function.py, safe/metadata/exposure_summary_layer_metadata.py, safe/metadata/property/dictionary_property.py, safe/metadata/test/data/existing_impact.json, safe/metadata/test/data/existing_impact.xml, safe/utilities/metadata.py, safe/utilities/test/test_metadata.py
=> Fix 3632 xml not written

safe/gui/tools/options_dialog.py
* Ticket #4015 
- Add sum age ratio checker in option dialog
=> Add sum age ratio checker in option dialog.

safe/definitions/hazard_exposure_specifications.py, safe/impact_function/impact_function.py, safe/impact_function/provenance_utilities.py, safe/impact_function/test/test_impact_function.py, safe/impact_function/test/test_provenance_utilities.py
* Ticket #
* Funded by : WorldBank
=> Review provenance to have a better translation in French

safe/common/dynamic_translations.py, safe/definitions/minimum_needs.py, safe/report/extractors/minimum_needs.py
* Ticket #4039 
* Description : Increase length size in minimum needs fields
=> Allow QLongLong length 11 in minimum needs fields

safe/definitions/post_processors.py, safe/report/test/test_impact_report.py
* Ticket #3607 
* Description : change additional rice calculation
=> regarding issue #3607: change calculation of additional rice

safe/definitions/exposure_classifications.py
* Description : Add other group in Badan Geologi classification
=> add other group to Badan Geologi Landcover

safe/metadata/property/date_property.py, safe/utilities/metadata.py, safe/utilities/test/test_metadata.py
* Ticket #4049 
- Handle more types when converting type in metadata copying.
=> Fix #4049. Handle more types in metadata copying.

resources/css/InaSAFE.css, safe/definitions/reports/components.py, safe/report/extractors/infographics.py
* Ticket #
- Change fallback font to Arial in Windows
- Create fallback header if affected field not found
=> infographic fixes:

safe/definitions/hazard_classifications.py
* Ticket #4057 
* Description : Fix thresholds for SSHWS classification according to the ticket
=> fix SSHWS classification

safe/definitions/reports/components.py, safe/gui/widgets/dock.py, safe/utilities/utilities.py
* Funded by : DFAT/WorldBank
* Issues using InaSAFE in French
* Fix layer title not working
=> small issues: unicode, layer title

CHANGELOG, metadata.txt, safe/definitions/reports/components.py, safe/gui/widgets/dock.py, safe/utilities/utilities.py
- Add full CHANGELOG
- Add missing PR from @Gustry
=> Version 4.0.1 (update)
