inasafe/inasafe

safe/gui/tools/minimum_needs/needs_profile.py

We sorted out based on os environment. This is not good. QGIS is our proxy. User will more likely expect InaSAFE to be in the same locale as QGIS, not his/her os environment.

Sort minimum needs profiles based on QGIS' locale.

---

realtime/utilities.py

We don't use it anymore as the shakemaps should be exist on the same host as we run the assessment.

Remove shakemaps_cache reference.

---

realtime/shake_event.py
realtime/test/test_shake_event.py

The mmi-nearest.tif generated has no "No Data" value set.
* As we try to get the value of the mmi given a point, there might be a case when the point is not in the raster, or it lies on the pixel which value is "No Data".
* We don't assess population affected for each nearby cities. This commit changes the title from 'Places Affected' to 'Nearby Places' and from 'People Affected' to 'Population' for each nearby cities.

Fix for #1513 and change some wording in the report

---

safe/gui/widgets/dock.py
safe/gui/widgets/message_viewer.py

This commit addresses https://github.com/AIFDR/inasafe/issues/1488. By doing this, the report opened on the browser is the right report of the selected active layer.

Update impact path to the message viewer every time user changes the active layer

---

.gitattributes

Regarding Issue  #660
Add some attributes in .gitattributes.
The following are expected after this fix:
1. When Windows user doing a checkout, the line endings will follow the rule in their repository (core.autocrlf)
2. When Windows user doing a commit or push, the line endings will follow Unix style (LF), except for *.bat files (always CRLF)
3. Some of the files are set as binary to avoid falsely attributed as text, like images and fonts.

Line endings normalization rule in .gitattributes

---

safe/gis/qgis_interface.py
safe/gui/widgets/dock.py
safe/gui/widgets/test/test_dock.py
safe/utilities/qgis_utilities.py

fix #1423
When we use the "save as" function on a layer, .xml and .keywords are also saved
This branch rely on PR https://github.com/AIFDR/inasafe/pull/1652

fix #1423 save .xml and .keywords when using 'save as'

---

safe/gui/tools/osm_downloader_dialog.py
safe/gui/ui/osm_downloader_dialog_base.ui
safe/plugin.py
safe/utilities/gis.py

This allows the user to select an area by drawing a rectangle, in the OSM downloader.
Until you start drawing a rectangle, the extent is set to the map canvas when the window is showed.
You can click on a button to hide the window and start drawing a rectangle. If the rectangle is valid, the extent is changed.

fix #1225 : allow the user to select an area in the OSM downloader

---

safe/gui/tools/osm_downloader_dialog.py
safe/gui/ui/osm_downloader_dialog_base.ui

Add 'building points' to the osm downloader.
It will download buildings but as a point layer.
The "All" option will fetch : 
- buildings
- building points
- roads

Fix #1207 : add 'building points' to the osm downloader

---

safe/common/exceptions.py
safe/gui/tools/osm_downloader_dialog.py

fix #1732 : OSM downloader : skip a feature type if one is empty

fix #1732 : OSM downloader : skip a feature type if one is empty

---

safe/gui/tools/osm_downloader_dialog.py
safe/gui/tools/test/test_osm_downloader.py
safe/gui/ui/extent_selector_dialog_base.ui
safe/gui/ui/osm_downloader_dialog_base.ui

fix pep8 and fix #1730 : improvements on the OSM downloader : 
- fix horizontal layout on the OSM downloader
- fix horizontal layout on the extent selector dialog
- fix error message when no OSM data
- move the button down about "select on map"

fix pep8 and fix #1730 : improvements on the OSM downloader

---

safe/gui/tools/osm_downloader_dialog.py
safe/utilities/file_downloader.py

An ``CanceledImportDialogError`` is raised instead of ``DownloadError`` when a download is canceled.

fix #1739 exception about canceled download

---

safe/gui/tools/osm_downloader_dialog.py
safe/gui/tools/test/test_osm_downloader.py
safe/gui/ui/osm_downloader_dialog_base.ui

Add an option to overwrite or not existing files when using the OSM downloader.
The &output_prefix is not uploaded to the server any more because when extracting the zip, the process will generate a safe base path where to extract files.

fix #1679 : change how the zip is extracted, allow the user to overwrite or not

---

safe/gui/tools/extent_selector_dialog.py
safe/gui/ui/extent_selector_dialog_base.ui

This PR adds a new option to set the analysis area, see https://github.com/AIFDR/inasafe/issues/1764.
The user can select one of his bookmark by clicking on the checkbox.

fix #1764 : allow a user to select the area with a bookmark

---

safe/gui/tools/osm_downloader_dialog.py
safe/utilities/gis.py

fix #1770 check if the map canvas is using 4326 and enable OTF if necessary

fix #1770 check if the map canvas is using 4326 and enable OTF if necessary

---

safe/utilities/analysis.py

When we have errors in the IF run method, the cursor still displayed as busy, and ... it is annoying.
I analyzed that this is because the method to restore cursor is executed on run_postprocessor method. But since the impact layer is none, the postprocessor part is skipped but the cursor doesn't restored.

Bugfix related to #1675: Cursor still displayed as busy

---

safe/impact_functions/inundation/flood_polygon_roads/impact_function.py
safe/impact_functions/inundation/flood_vector_building_impact/impact_function.py

If you try to use Vector Flood on Buildings Impact (using the QGIS implementation) you get an error like:
```
Details
These additional details were reported when the problem occurred.
An exception occurred when calculating the results. Calculation error encountered:
There are no objects in the hazard layer with affected (Affected Field) = 1 (Affected Value). Please check the value or use a different extent.
Diagnostics (click for details)
In file "/Users/timlinux/.qgis2/python/plugins/,/safe/utilities/impact_calculator_thread.py", line 188, in run check_integrity=self._check_integrity)
In file "/Users/timlinux/.qgis2/python/plugins/,/safe/engine/core.py", line 184, in calculate_impact F = impact_function.run(layers)
In file "/Users/timlinux/.qgis2/python/plugins/,/safe/impact_functions/inu …
```

Fix #1857 - support OTFP for flood vector building impact

---

safe/gui/widgets/dock.py
safe/impact_functions/generic/classified_polygon_building/impact_function.py
safe/impact_functions/generic/continuous_hazard_population/impact_function.py
safe/impact_functions/inundation/flood_polygon_roads/impact_function.py
safe/impact_functions/inundation/flood_vector_building_impact/impact_function.py
safe/impact_functions/volcanic/volcano_polygon_population/metadata_definitions.py
safe/impact_statistics/aggregator.py
safe/impact_statistics/function_options_dialog.py
safe/utilities/analysis.py

Modify aggregation to use impact layer extent if aggregation layer is not provided.
This fix is used to handle cases where the hazard vector layer contains polygon which is outside the optimal extent but must be included in the postprocessor calculations.

Fix #1854: Modified aggregation to use impact layer extent 

---

safe/impact_functions/volcanic/volcano_polygon_population/metadata_definitions.py

If it is allowed to accept point hazard, the function can't handle it and raises exception.
@akbargumbira @ismailsunni if you are ok with this, just merge it.

fix volcano polygon population metadata to not accept hazard point layer

---

resources/osm/admin_level_per_country.json
safe/gui/tools/osm_downloader_dialog.py
safe/gui/tools/test/test_osm_downloader.py
safe/gui/ui/osm_downloader_dialog_base.ui

Add two options to download potential IDP and boundaries.
Shapefiles need to be improved on osm-reporter.
All options are checked by default, except boundary.
The combobox about the country is optional. That's why I put it in a sentence which is italic.

add IDP camp export and improve GUI

---

resources/osm/admin_level_per_country.json
safe/gui/tools/osm_downloader_dialog.py
safe/gui/tools/test/test_osm_downloader.py
safe/gui/ui/osm_downloader_dialog_base.ui

- Change the GUI about the political boundary.
- add the bbox to each country in the json file.
- detect if the center of the map canvas is in one of these countries.
- if yes, select this country in the combobox.

Improve the boundary export in the OSM downloader

---

safe/impact_functions/inundation/flood_vector_building_impact/impact_function.py

This is done by using spatial index to identify which flood polygons
will need exact intersection test (much faster than doing intersection
with one huge polygon)
A small extra optimization is to write features in batches as that is
more efficient than writing features one by one.
Measured speed improvement on Jakarta test data (2013 flood polygons
and OSM buildings) was ~40x (from 30min down to 40sec)
Fixes #1889

Make flood vector-building impact function faster

---

safe/gui/tools/wizard_dialog.py

After adding a layer with a different CRS, the overlap test goes faster than the signal that enables the OTFR.

[IFCWizard] Fix test for layer overlap. Fixes #1957

---

Makefile

This minimal change allows passing an argument to test_suite_quick so that we can use 
```make test_suite_quick PACKAGE=common```
to run tests only for that package

allow passing a PACKAGE arg to test_suite_quick

---

safe/common/utilities.py
safe/engine/interpolation_qgis.py
safe/engine/test/test_interpolation_qgis.py
safe/impact_functions/generic/classified_polygon_building/impact_function.py
safe/impact_functions/generic/classified_polygon_building/metadata_definitions.py
safe/impact_functions/generic/classified_polygon_building/test/test_classified_polygon_building.py

This PR makes the ClassifiedPolygonHazardBuildingFunction work by using QGIS API instead of using InaSAFE's own routines for geometry operations.
It has been discovered that InaSAFE's geometry operations do not handle polygons with holes correctly, the new functionality comes with unit tests that give slightly different results (differences were manually checked to confirm that the new results are correct).
This implementation may be faster than the original with many smaller hazard polygons, and slower than the original with few very complex polygons. The speed could be improved probably by using prepared geometries or by cutting complex polygons into smaller pieces.

Classified hazard vs polygon building with QGIS API

---

safe/gui/tools/impact_merge_dialog.py
safe/utilities/clipper.py
safe/utilities/test/test_clipper.py

What is being addressed #2229 and #2233:
See #2233 for reference
- Stuck in entire area mode if choosing aggregation layer without closing the dialog
- User should be able to merge in entire area mode, even if one of the layer is aggregated, both or none
- Hacky fix for naming bug in reports where it can't match unicode area names. Should be fine for ASCII
- Additional checks to make sure both layers are aggregated with the same aggregation layers with what the user choose.
- Additional checks to make sure that the user uses aggregated postprocessor in both layers if user choose aggregation layer

bugfix for issues #2229 and #2233.

---

safe/definitions.py
safe/gui/widgets/dock.py
safe/utilities/keyword_io.py
safe/utilities/test/test_keyword_io.py

Implementation for #2313 - let the keywords table keys be shown from definitions list rather. Also refactored the keywords table generation into keywords.io so that it can be re-used elsewhere...
I also made some other tidy ups to definitions.py

Better keywords table generation

---

docs/en/openstreetmap_downloader.html
docs/id/openstreetmap_downloader.html
safe/utilities/osm_downloader.py
safe/utilities/test/test_osm_downloader.py

This PR changes the upstream osm downloader server URL to one hosted on InaSAFE infrastructure.

fix #2343 - Use InaSAFE uri for osm downloader

---

safe_extras/parameters/qt_widgets/boolean_parameter_widget.py
safe_extras/parameters/qt_widgets/generic_parameter_widget.py
safe_extras/parameters/qt_widgets/group_parameter_widget.py
safe_extras/parameters/qt_widgets/parameter_container.py

fix #2355 - this fix:
* remove excess padding making parameters more compact
* removes zebra striping of widgets
* puts checkbox labels to the right of checkboxes
* hides frame borders to flatten everything out.
Here is the before view:
and here is what it looks like with my PR:

Make parameter widgets look more beautiful

---

realtime/shake_data.py

It can happen when the source wasn't finished yet copied.
So the extracted file is not finished.
This fix recopy the original file when the file is different.

Fix potential bug with realtime extract process:

---

i18n/inasafe_af.ts
i18n/inasafe_en.ts
i18n/inasafe_es_ES.ts
i18n/inasafe_fr.ts
i18n/inasafe_id.ts
safe/gui/ui/options_dialog_base.ui

Per subject.  Note that there binary files `i18n/inasafe_es_ES.qm` and `i18n/inasafe_id.qm` also need updating, but I'm not sure how to do that/whether that is done by some other automated process.  If there are docs on how to do this, I can add to this PR.

update label typo for ISO metadata (s/19155/19115/)

---

safe/gui/widgets/dock.py
safe/messaging/item/cell.py
safe/messaging/item/text.py
safe/utilities/keyword_io.py
safe/utilities/test/test_keyword_io.py

It takes care to wrap long filenames nicely (needs testing on Windows).
This was added to make it easier to know what CRS and file path a dataset has.

This PR adds data source and CRS to the keywords list in dock

---

safe/messaging/item/cell.py

Fix #2504 - exception raised when messaging cell contains nested table or bullet list due to slashes param not being accepted by table class to_html() method.
See also #2494 and #2506

Better fix for #2504 - exception when calling Table.to_html() method

---

safe/gui/tools/osm_downloader_dialog.py
safe/gui/tools/test/test_osm_downloader_dialog.py
safe/gui/ui/osm_downloader_dialog_base.ui

Ticket : https://github.com/inasafe/inasafe/issues/2469
* flood_prone as floodprone
* flood_rain
* flood_send
* flood_depth
* flood_duration
* flood_latest
* fire_hazard
* kab_name
* kec_name
* kel_name
* rt_number
* rw_number
The last 5 fields are not documented in OSM but I think they are linked to flood prone areas.

add flood prone to the OSM downloader

---

safe/gui/tools/test/test_wizard_dialog.py
safe/gui/tools/test/test_wizard_dialog_locale.py
safe/gui/tools/wizard_dialog.py
safe/gui/ui/wizard_dialog_base.ui
safe/messaging/item/table.py

1. Get rid of eval() statements. Fixes #2329
2. Use QgsDateTimeEdit for the `date` keyword. Fixes for #2499. 
In the existing test dataset I found the date keyword is usually missing, but when present, it's always stored as 'dd-MM-yyyy HH:mm'. So I made the wizard always using that format (no localisation!). I hope it's ok.
Please ignore the other reverted commits - I just didn't know how to squash commits that are already not on the top of the stack.

Use Date Picker in Keywords Wizard. Get rid of eval() statements.

---

metadata.txt
safe/gui/tools/test/test_wizard_dialog.py
safe/gui/tools/test/test_wizard_dialog_locale.py
safe/gui/tools/wizard_dialog.py
safe/gui/ui/wizard_dialog_base.ui
safe/gui/widgets/dock.py
safe/gui/widgets/test/test_dock.py
safe/messaging/item/cell.py
safe/messaging/item/table.py
safe/messaging/item/text.py
safe/plugin.py
safe/report/impact_report.py
safe/utilities/analysis_handler.py
safe/utilities/keyword_io.py
safe/utilities/test/test_keyword_io.py

Backport from develop branch. Contains from PR #2483, #2517, #2509, #2504, #2534, #2535, and #2525 
Fix some issues and small enhancements:
- adds data source and CRS to the keywords list in dock
- Keywords Wizard crashes on repeated use #2514 
- Crash Minidump when try to use InaSAFE keyword editor twice #2467
- Fix #2515 
- Fix serializing classified raster values
- Wizard: ged rid of eval() statements #2329
- Use Date Picker in Keywords Wizard #2499
- Fix #2504 - exception raised when messaging cell contains nested table or bullet list due to slashes param not being accepted by table class to_html() method.
- [BUG] Python error in PDF generator and Open in Composer using IFCW #2532
- Python bug when creating a pdf map #2523

Backport to  3.2.5

---

safe/gui/tools/test/test_wizard_dialog.py
safe/gui/tools/wizard_dialog.py

Previously, we use `name` from definition to store the value mapping. This PR use the `key`. The `name` is human friendly thing, and can be replaced several times, if needed.

Value mapping key

---

bin/inasafe
safe/gui/widgets/dock.py
safe/utilities/analysis.py
safe/utilities/analysis_handler.py

- Rename layers like in base.py
- Clip_parameters returned useless parameters (exposure, hazard and geoextent), so I've removed them.
- Use self.hazard, self.exposure and self.aggregation everywhere in analysis.py

Manage layers in analysis.py

---

safe/gui/tools/help/osm_downloader_help.py

Reviewed context help for OSM downloader dialog. Added new information about Political boundaries.

fix #2702 Reviewed context help for OSM downloader dialog.

---

safe/gui/tools/peta_jakarta_dialog.py

Peta Jakarta delivering python error
ValueError: Invalid format string
Traceback (most recent call last):
File "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\gui\tools\peta_jakarta_dialog.py", line 198, in accept
self.time_stamp = time.strftime('%d-%b-%G %H:%M:%S')
ValueError: Invalid format string
Windows
Changed ```self.time_stamp = time.strftime('%d-%b-%G %H:%M:%S')``` to ```self.time_stamp = time.strftime('%d-%b-%Y %H:%M:%S')```
@timlinux

Fix for Peta Jakarta Python error windows

---

safe/impact_statistics/aggregator.py

We need to write the layer first before creating the layer metadata file. If we create the metadata file, InaSAFE will assume that the layer is not file based, then the metadata will be stored in the database. However, after the layer is written to the disk, InaSAFE will assume that the layer is file based, which make InaSAFE try to find .xml for the metadata. InaSAFE doesn't find the xml, and generate default metadata (with keyword version only).
Hence, it will fail when there is a verification.
please review @timlinux

Fix #2724.

---

safe/impact_template/abstract_road_building_report_template.py
safe/impact_template/building_report_template.py
safe/impact_template/template_base.py

@Charlotte-Morgan I fixed the text alignment for the breakdown and for the postprocessing, like `closed buildings`.

fix #2849 building report, fix align right/left

---

safe/gui/widgets/dock.py
safe/gui/widgets/test/test_dock.py

Issue https://github.com/inasafe/inasafe/issues/2899
* If `hide the exposure layer` is checked : 
* The impact layer will be above the hazard layer
* The exposure layer will be unchecked
* If `hide the exposure layer` is not checked : 
* The impact layer will be above the hazard layer and the exposure layer
@Charlotte-Morgan Is-it the expected behaviour ?
For now in InaSAFE, we don't have any option to hide the hazard layer after the analysis, only the exposure layer, so the algorithm will always put the impact layer above the hazard.

fix #2899 impact layer should draw over the hazard layer

---

safe/gui/widgets/dock.py

Fix for #2945 
The issue comes up because whenever there is a change in the list layer, InaSAFE tries to update the combobox in the dock for the hazard, exposure, and aggregation layer.
So, I just pass if the metadata is out of update (just like layer with no keyword).

Pass when the metadata is outdated on loading to combo box.

---

safe/metadata/provenance/if_provenance_step.py

I couldn't launch an analysis if a layer has some accents (often in French)

use unicode if the layer name has some accents

---

safe/gui/tools/wizard/wizard_dialog.py
safe/gui/widgets/dock.py
safe/gui/widgets/test/test_dock.py
safe/utilities/analysis_handler.py
safe/utilities/qgis_utilities.py

* Make the layer added by the IFCW visible by default when we add a new hazard/exposure layer.
* When the analysis is finished, the dock is checking where to put the impact layer (above the hazard/exposure), enable the impact layer by default ,.... but these statements were not executed by the wizard. For now, I tried quickly to refactor common functions and I copy/paste some statements from the dock which were missing. I'm going to write a ticket to fix that later.
@NyakudyaA Can you try this PR ? Thanks to notice that the wizard does not have the same behaviour.
It's related to #2925

Layer visibility

---

safe/storage/layer.py
safe/storage/raster.py
safe/storage/test/test_io.py

fix #2804 - make checking the analysis environment more efficient by not reading the full raster each time you pan or zoom 
Ok I have made a fix (for rasters anyway):
Before optimisation: 15s to do a simple pan
After optimisation: 4s to do a simple pan

fix #2804 - make checking the analysis environment more efficient by not reading the full raster each time you pan or zoom

---

safe/definitions.py
safe/impact_functions/inundation/flood_polygon_roads/impact_function.py
safe/impact_statistics/postprocessor_manager.py
safe/postprocessors/abstract_building_road_type_postprocessor.py
safe/postprocessors/test/test_building_type_postprocessor.py

Problems:
- We use new keyword for aggregation to mark which field in exposure layer that should be aggregate. Meanwhile, post processor expects another keyword
- The checker is not really robust. Lowercasing one hand but not the other hand.
Fixes:
- Better setup for post processor keyword for building and road.
- Better checker.

Fix #2847 no aggregation table

---

safe/definitions.py

fix #3117 - Support citations for concepts. For the implementation, I have created a dictionary structure for all concepts - I think in future rich reporting work we can use it to produce a glossary of terms easily.

fix #3117 - Add citations to concept definitions in definitions.py

---

resources/img/wizard/keyword-subcategory-cyclone.svg
safe/common/exceptions.py
safe/definitionsv4/colors.py
safe/definitionsv4/hazard.py
safe/definitionsv4/hazard_classifications.py
safe/definitionsv4/test/scripts.py
safe/definitionsv4/test/test_utilities.py
safe/definitionsv4/units.py
safe/gisv4/raster/clip_bounding_box.py
safe/gui/tools/wizard/step_kw25_classification.py
safe/gui/tools/wizard/step_kw43_threshold.py
safe/gui/tools/wizard/wizard_strings.py
scripts/create_api_docs.py

This PR adds tropical cyclone support and multi unit hazard classifications. 
Tropical Cyclone is a metadata based impact calculation that classifies impacted building.
Classification can be done using the  Saffir–Simpson hurricane wind scale, the Australian Bureau of Metereology Tropical Cyclone or a generic high-medium-low scale 
Each classification can have default values in different units. to do this, add `'multiple_units': [unit_miles_per_hour, unit_kilometres_per_hour, unit_knots],` to the classification and 
```
'numeric_default_min': {
unit_knots['key']: 107,
unit_miles_per_hour['key']: 123,
unit_kilometres_per_hour['key']: 198
},
'numeric_default_max': 9999999999,
'citations': [
{
'text': None,
'link': None
}
```
if a value is common to all units (for example 0 or 99999999), you …

tropical cyclone support and multi unit hazard classifications

---

safe/gui/tools/wizard/step_kw43_threshold.py
safe/gui/tools/wizard/test/test_keyword_wizard.py

I set the min to 0 and max to 999999. Next time I set to the min max depends on the unit.

Fix min max for threshold in wizard per #3540

---

safe/gui/tools/help/definitions_help.py
safe/gui/tools/help_dialog.py
safe/plugin.py
safe/utilities/keyword_io.py

For fixing this error:
```
Problem
The following problem(s) were encountered whilst running the analysis.
KeyError
Suggestion
You can try the following to resolve the issue:
Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an …
```

Fix key error when name is not in the definitions.

---

safe/gui/tools/wizard/step_kw40_classify.py
safe/gui/tools/wizard/test/test_keyword_wizard.py

issue #3555
- add inasafe_field_for_the_layer function
- add condition to check if there are any fields on layer-purpose that can be the inasafe-field. if nothing were found, skip the inasafe-field step and set the next step to source step.

Skip inasafe-field step when there is no field found #3555

---

safe/definitionsv4/fields.py

Some data set use float / real number type for population count, so we need to set the population count to use float also.
cc @samnawi

Set pop count to use float also.

---

safe/definitionsv4/processing_steps.py
safe/gisv4/raster/rasterize.py
safe/gisv4/raster/write_raster.py
safe/impact_function/earthquake.py

- this is resurrection/rewrite of code from InaSAFE 3.5
- operations are done using QGIS API
- aggregation is now included in the algorithm
Not yet integrated into InaSAFE pipeline, just calculation functions...
A test script that can be run from QGIS to use the new code:
```
from qgis.core import QgsMapLayerRegistry, QgsRectangle
from inasafe.safe.impact_function.earthquake import calc_impact, itb_fatality_rates, pager_fatality_rates, bayesian_fatality_rates
from inasafe.safe.test.utilities import load_layer
path = "/home/martin/tmp/earthquake/West Sumatera"
layer_exp, _ = load_layer(path+"/02 Exposure Data/Sumatera_Population_WGS84.tif")
layer_haz, _ = load_layer(path+"/01 Hazard Data/Padang_EQ_2009_WGS84.tif")
layer_agg = None  # no aggregation
#layer_agg, _ = load_layer(path+"/03 …
```

Implementation of earthquake impact calculation

---

safe/gis/vector/assign_highest_value.py
safe/gis/vector/smart_clip.py

Low hanging fruits:
- cache exposure features instead of fetching them directly from layer by ID
- use prepared geometry for repeated intersection tests of hazard geometries
- in smart clip, only fetch layers within extent of mask layer
For a small analysis area, the time on my laptop went from 12.4s down to 6.1s

Optimize impact function for flooding on buildings

---

safe/definitions/exposure.py
safe/definitions/hazard_classifications.py
safe/impact_function/impact_function.py
safe/impact_function/style.py

Same hazard, but different exposure : 
CC : @Charlotte-Morgan @felix-yew

disable not_exposed in the map for landcover and population exposures

---

.travis.yml

As we often scroll to the bottom in travis to see which tests are failing, it's better to have the test pep8 at the end.

make pep8 at the end of travis

---

safe/common/test/test_utilities.py
safe/common/utilities.py
safe/gui/widgets/test/test_dock.py
safe/impact_function/style.py
safe/impact_function/test/test_impact_function.py
safe/test/utilities.py
safe/utilities/i18n.py
safe/utilities/osm_downloader.py
safe/utilities/rounding.py
safe/utilities/test/test_rounding.py

* FR
* EN
* ID
@lucernae You should be able to use `format_number` in the report. It adds the thousand separator and apply the rounding if needed.

add thousand separator

---

safe/definitions/default_settings.py
safe/gui/tools/options_dialog.py
safe/gui/ui/options_dialog_base.ui
safe/impact_function/style.py

* Description : Revamp of the hazard conditional styling.
As it breaks the alignment (bug in QGIS), it's not enabled by default. You need to go in inasafe settings to enable this feature.

revamp of the hazard conditional styling

---

safe/report/extractors/composer.py
safe/report/impact_report.py
safe/report/processors/default.py
safe/report/test/test_impact_report.py

Map report now auto zoom in to analysis extent only, instead of all included layers.

fix issue #3824 Map extent not properly used in Map Report

---

safe/definitions/report.py
safe/report/extractors/impact_table.py

* Description : Show notes in report provenance when aggregation layer is not used
Small fix. Please merge when passed.

add notes in report when aggregation layer is not used

---

safe/definitions/hazard.py
safe/gui/tools/wizard/step_kw33_multi_classifications.py
safe/gui/tools/wizard/test/test_keyword_wizard.py
safe/gui/tools/wizard/wizard_dialog.py
safe/gui/ui/wizard/step_kw33_multi_classifications.ui

* Ticket #3853 #3854 
- Filter out classification based on exposure
- Do special filter for EQ hazard
- Remove generic classification from tsunami hazard

Filter classification based on supported exposure.

---

safe/gui/tools/wizard/step_kw33_multi_classifications.py
safe/gui/tools/wizard/wizard_dialog.py

* Ticket #3853 (enhanced)
- Disable Earthquake Raster for Population (previously removed)

Disable EQ Raster Population classification.

---

safe/impact_function/impact_function.py
safe/impact_function/test/test_impact_function.py
safe/test/data/scenario/raster_continuous_on_raster_population.json

* Ticket #3851 
* Manage default ratios with a raster exposure
Wait for 3889 to be merged

manage default ratios with a raster exposure

---

safe/definitions/__init__.py
safe/definitions/reports/__init__.py
safe/definitions/reports/components.py
safe/gui/analysis_utilities.py
safe/gui/tools/batch/batch_dialog.py
safe/gui/widgets/dock.py
safe/report/extractors/impact_table.py
safe/report/impact_report.py
safe/report/processors/default.py
safe/report/report_metadata.py
safe/report/test/test_impact_report.py

* Ticket #3822 
QPT should be made available to user after report generations.
Changes:
- Different output now categorized:
- Template produced, with all string variable generated, default extent set, and images resolved.

fix issue #3822: QPT should be made available

---

safe/gui/tools/help/definitions_help.py

Displacement rates missing in help
* Ticket #3904 
* Funded by :  DFAT
* Description :  Adds displacement rates to definitions_help

Fix #3904 - add  displacement rates to definitions help. Funded by DFAT.

---

safe/gui/tools/help/definitions_help.py

Partial fix for #3906 - include earthquake specific notes in population exposure help. Funded by DFAT.

Partial fix for #3906 - include earthquake specific notes in population exposure help. Funded by DFAT.

---

safe/definitions/concepts.py
safe/definitions/exposure.py
safe/definitions/fields.py
safe/gui/tools/help/definitions_help.py
safe/messaging/item/cell.py
safe/report/test/test_impact_report.py

fix #3799 - clarify how roundings work in notes. fix #3916 - ensure that concepts are all shown nicely in definitions help. Improve reporting test to be less fragile. Funded by DFAT.
* Ticket #3799 #3916
* Funded by :  DFAT
* Description : See screenshots below for key changes:
Rounding explanation for #3799 (this is shown in IF report notes too)

Improvements to definitions help to add glossary and notes to explain roundings.

---

safe/datastore/datastore.py
safe/definitions/post_processors.py
safe/gis/vector/summary_3_analysis.py

* Ticket #3812 
* Description : Some layers become a multilinestring during the process. The size calculator can't handle this kind of geometry. It's better to compute the size part per part.

fix size calculator with a multi geometry

---

safe/definitions/default_settings.py
safe/gui/tools/options_dialog.py
safe/gui/ui/options_dialog_base.ui
safe/gui/widgets/dock.py
safe/impact_function/impact_function.py
safe/impact_function/test/test_impact_function.py
safe/report/extractors/composer.py
safe/report/extractors/util.py
safe/report/processors/default.py
safe/report/test/test_impact_report.py

* Ticket #3879
- Add new InaSAFE option: show only impact layer
- Add new provenance items: original hazard, exposure, and aggregation layer. This is needed to draw map. Since after analysis, hazard, exposure and aggregation were cleaned up, we can't show it using that layer.

fix issue #3879: Make maps showing all layer related with analysis

---

safe/gis/raster/zonal_statistics.py
safe/gis/vector/summary_2_aggregation.py

* Ticket #3778 
* Description : After zonal stats, some values were set to None. We need to fill them with 0 or it breaks the summary calculation.

fill None values after zonal stats algorithm

---

safe/common/parameters/default_select_parameter_widget.py

* Ticket #3813 
* Description : handle inasafe default wizard behaviour if layer has keywords

handle inasafe default wizard behaviour if layer has keywords

---

safe/gis/vector/default_values.py
safe/gis/vector/from_counts_to_ratios.py
safe/gis/vector/prepare_vector_layer.py
safe/gis/vector/recompute_counts.py
safe/impact_function/impact_function.py

* Ticket #3971 
It adds many logs which are very useful to see what happen with ratios and counts : 
```
2017-03-01T17:34:11	0	aggregation: Aggregation layer already in exposure CRS
2017-03-01T17:34:11	0	female_ratio_field field detected in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We will propagate this ratio to the exposure layer later when we combine these two layers.
2017-03-01T17:34:11	0	youth_ratio_field = 0.25 constant detected in the aggregation layer AND the equivalent count has not been detected in the exposure layer. We are adding this ratio to the exposure layer.
2017-03-01T17:34:11	0	adult_ratio_field is neither a constant nor a field AND the equivalent count has not been detected in the …
```

add many logs in the IF

---

safe/definitions/reports/components.py
safe/report/extractors/action_notes.py

* Ticket #3974 
* Description : add an affected note for affecting hazard class

fix issue #3974: add an affected note for affecting hazard class

---

metadata.txt

* InaSAFE 3 was available on QGIS 2.18 so users will never see this update to 4.0 and they will stick to InaSAFE 3. I don't think it's something we want.
* QGIS 2.18 will become the next LTR so we better fix it if we notice something wrong.
* I'm using QGIS 2.18 and InaSAFE is now disabled by default when I launch QGIS.

enable inasafe for QGIS 2.14, 2.16 and 2.18

---

safe/gui/tools/options_dialog.py

Previously it was like this (missing description)
Now it has description back

Fix description option dialog

---

safe/gis/raster/clip_bounding_box.py

* Ticket #4026 
* Description : Skip clip_by_extent if we have an exception.
This is not the best as we should fix why we have an exception,  but in the meantime, this step is not mandatory, it allows us to speed up the analysis.

skip clip_by_extent if we have an exception

---

safe/gui/tools/shake_grid/shakemap_converter_dialog.py
safe/gui/tools/shake_grid/test/test_shakemap_converter_dialog.py
safe/gui/ui/shakemap_importer_dialog_base.ui
safe/plugin.py

* Ticket #4040 
* Description : By launching the keyword wizard, the layer from shakemap importer would be version 4.0 ready keywords.

add option to launch keyword wizard on shakemap importer

---

safe/definitions/hazard_classifications.py
safe/definitions/reports/components.py
safe/report/extractors/general_report.py
safe/report/test/test_earthquake_report.py
safe/report/test/test_impact_report.py

* Ticket #3957 
classification unit added per hazard classification:
- generic_hazard_classes = 'hazard zone'
- earthquake_mmi_scale = 'MMI intensity'
- volcano_hazard_classes = 'hazard_zone'
- flood_hazard_classes = 'hazard_zone'
- flood_petabencana_hazard_classes = 'hazard_zone'
- ash_hazard_classes = 'hazard_zone'
- tsunami_hazard_classes = 'hazard_zone'
- tsunami_hazard_population_classes = 'hazard_zone'
- tsunami_hazard_classes_ITB = 'hazard_zone'
- tsunami_hazard_poopulation_classes_ITB = 'hazard_zone'
- cyclone_au_bom_hazard_classes = 'cyclone_category'
- cyclone_sshws_hazard_classes = 'cyclone_category'

add classification unit to hazard classification definition for general report title

---

safe/gui/tools/options_dialog.py
safe/gui/ui/options_dialog_base.ui

* Ticket : #4113 
- Tab name: Global Default ->Demographic Defaults
-  The whole tab content needs to go into a scrollbox widget

Fix 4113 polish option

---

safe/gui/tools/options_dialog.py
safe/gui/ui/options_dialog_base.ui

Added separate tab for earthquake in options and show definitions relating to earthquake for the selected model.
Signed-off-by: Tim Sutton <tim@kartoza.com>
* Ticket : #4130
* Description :  Added eq tab in options

Fix #4130 Earthquake help text - set default options

---

resources/report-templates/standard-template/jinja2/aggregation-postprocessors.html
safe/definitions/field_groups.py
safe/report/test/test_impact_report.py

* Ticket : #4069 
* Description : Add notes to the bottom of the demographic breakdown table. The notes came from description in concepts.py.

add notes based on concepts

---

safe/gui/tools/help/definitions_help.py

* Ticket : #4151
* Description : Show help text in field descriptions.

Partial fix for #4151 - show help_text in field definitions

---

resources/css/InaSAFE.css
resources/report-templates/standard-template/jinja2/general-report.html
safe/gui/widgets/message_viewer.py

* Ticket: #
* Description: Still cannot replicate table floats to right on the dock.
on save as pdf action:
BEFORE
AFTER

override bootstrap 4 style (font-size and table padding)

---

safe/definitions/reports/components.py
safe/gui/tools/help/definitions_help.py
safe/report/extractors/action_notes.py
safe/report/test/test_impact_report.py
safe/utilities/rounding.py
safe/utilities/utilities.py

* Ticket: #4093 
* Description: add fatality ratio to the note just like the displacement ratio. the rounding is the same as what displayed in the definition help.

add notes for fatality rates

---

resources/report-templates/standard-template/jinja2/general-report.html

* Ticket: #
* Description: Put the table in general report in different row to avoid table that randomly floats to right in mac and windows

make the tables in general report in different row

---

safe/gis/vector/prepare_vector_layer.py

* Ticket: #4248 
- The field name in the expression needs to be inside a double quote. But the test is also working without double quote.

Fix #4248. Expression.

---

safe/report/test/test_impact_report_earthquake.py

* Ticket: 
* Description: we change the filename so this test will run after test_impact_report because if not, this eq report test will break test_minimum_needs_ouputs. we can find the better way to fix this later.

rename test_earthquake_report to test_impact_report_earthquake

---

safe/report/processors/default.py

* Ticket: backport of #4280
This doesn't fix the problem. But at least, we don't have a python exception.
QGIS 2.18 is not officially supported by InaSAFE yet. Only in 3 months

fix composer in QGIS 2.18

---

metadata.txt
safe/gui/widgets/dock.py

* Description: do not refresh the IF we are using an aggregation layer
It seems I got some problems by trying to connect/disconnect. I just found that I could use one function always connected to pan/zoom. It makes it much easier now.

do not refresh the IF we are using an aggregation layer

---

metadata.txt
safe/definitions/test/test_utilities.py
safe/definitions/utilities.py
safe/gui/analysis_utilities.py
safe/gui/tools/batch/batch_dialog.py
safe/gui/widgets/dock.py
safe/report/test/test_impact_report.py

* Ticket: #4240 
- Scan `{QGIS Setting dir}/inasafe` first for custom map template
cc @timlinux 
Tested in my local:
I use custom template for the portrait one (change the color from blue to green):

Fix 4240 reporting styling

---

safe/common/test/test_utilities.py
safe/common/version.py
safe/gui/tools/batch/batch_dialog.py
safe/gui/tools/minimum_needs/needs_profile.py
safe/gui/tools/test/test_save_scenario.py

* Ticket: Partially fixing #4306
* Description: Remove some `str()` functions. I think these should be safe. QT is already giving us some unicode. No need to convert to str.
We should make `str` deprecated I think. Using the format `%s` is redundant.
Comments are welcome.

remove some str() functions

---

Makefile

* Ticket: N/A
Small PR
Tidying up docker translation tools
- Move makefile commands for translation to the right place. 
- Change docker image repository to kartoza.

Tidying up docker translation tools.

---

safe/gis/vector/clip.py

* Ticket: #4116 
* Description: I think these two lines will fix this ticket. But I have more to do about invalid geometries.

allow only the same geometry type in the output layer

---

safe/impact_function/impact_function.py

Travis is not happy because of too many logs.
This line is for each postprocessor, for each impact function that we launch, so it's a lot!
I'm thinking about a function logging messages only if we are not on travis

reduce logs

---

safe/datastore/datastore.py
safe/definitions/provenance.py
safe/gui/widgets/dock.py
safe/impact_function/impact_function.py
safe/impact_function/test/test_impact_function.py
safe/utilities/keyword_io.py

* Ticket: #4303 
- Adding output layer URI in the output layer metadata (e.g. aggregate_hazard_impacted in the image below)

Fix 4303 output layer metadata

---

safe/definitions/hazard.py
safe/gui/tools/wizard/test/test_keyword_wizard.py

this PR allows land cover analysis for cyclons hazards.
@timlinux, @Charlotte-Morgan why are exposure_place, exposure_road, exposure_population also disabled?

enable landcover analysis for cyclones

---

safe/report/extractors/analysis_detail.py

* Partial Fix Ticket: #4352
* Description: Add one debug line when an exception occurs
I will try to fix it @myarjunar but I wanted to focus on the first part of the ticket (which seems related to IF itself), so I would prefer to replicate the other issue.
Can we merge this one @myarjunar and if you have time to look at this issue? Thanks
It's failing on the `Field name affected_production_cost, field index -1`

add more debug info when an exception occurs in the analysis extractor

---

safe/gui/tools/wizard/step_kw30_field.py

* Ticket: #3786 
Show uniqueness in step KW field #3786.
Adding in the InaSAFE fields wizard is more complex.

Show uniqueness in step KW field #3786.

---

safe/gis/expressions.py
safe/gui/tools/help/definitions_help.py
safe/plugin.py
safe/report/expressions/infographic.py

* Ticket: #4252 
* Description: This PR brings expressions docstrings into the InaSAFE help dialog.
One limitation, on this, we can't have translations. I'm looking for a patch in QGIS 3 where we can provide our custom translated strings.
@timlinux I think we should add a 15.2 for `Element-ID` from https://github.com/inasafe/inasafe/wiki/Map-Composer-Templating, there is no help for these, except on line in this wiki. `Element Tokens` will be removed according to #4252 @myarjunar?

add help from docstrings for expressions

---

resources/report-templates/standard-template/jinja2/infographic-people-section-notes.html
safe/report/expressions/infographic.py
safe/report/expressions/map_report.py

Removes redundant logo white path expression
Fixes CRS expression.
* Ticket: #
* Funded by: WB/DFAT
* Description:

Expression fixes

---

metadata.txt
safe/definitions/versions.py
safe/gui/tools/wizard/step_kw65_summary.py
safe/gui/tools/wizard/wizard_dialog.py

* Ticket: No Ticket
Fixing this bug:
```
AttributeError: 'WizardDialog' object has no attribute 'step_fc_function'
Traceback (most recent call last):
File "C:/Users/aless/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\wizard_dialog.py", line 678, in on_pbnNext_released
new_step.set_widgets()
File "C:/Users/aless/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\step_kw65_summary.py", line 130, in set_widgets
im_func = self.parent.step_fc_function.selected_function()
AttributeError: 'WizardDialog' object has no attribute 'step_fc_function'
```
To replicate, assign keyword in a layer when working on IFCW.
The fix is just merely removing old code that's not longer relevant. Previously we need to set the IF that we want to use, but now, all IF is …

Fix bug step fc function

---

safe/gis/raster/test/test_zonal_statistics.py
safe/gis/raster/zonal_statistics.py

* Ticket: #4437
* Description: This will allow us to use a different projection in the zonal stats alg, without reprojecting the raster layer.

enable different projections in the zonal stats algorithm

---

safe/gui/widgets/dock.py
safe/gui/widgets/message.py
safe/utilities/test/test_utilities.py
safe/utilities/utilities.py

* Ticket: None
I could it better, but it's not my priority ;-)
The problem is if the plugin is enabled, it will even raise an exception in InaSAFE and FloodMapper will be loaded itself, so users think that the problem comes from InaSAFE:
No more InaSAFE toolbar, exception from InaSAFE, and FloodMapper is loaded.

display warning about conflicting plugin

---

safe/gui/widgets/dock.py

Fixing this error:
```
2017-09-28T16:01:15    1    Traceback (most recent call last):
File "C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe\safe\plugin.py", line 939, in layer_changed
keywords = KeywordIO().read_keywords(layer)
File "C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe\safe\utilities\keyword_io.py", line 80, in read_keywords
return read_iso19115_metadata(source, keyword)
File "C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe\safe\utilities\metadata.py", line 100, in read_iso19115_metadata
metadata = GenericLayerMetadata(layer_uri, xml_uri)
File "C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe\safe\metadata\generic_layer_metadata.py", line 63, in __init__
layer_uri, xml_uri, …
```

Avoid uninitialized variable.

---

safe/gui/tools/field_mapping_dialog.py
safe/gui/ui/field_mapping_dialog_base.ui
safe/gui/widgets/field_mapping_tab.py

From:
To:
I was trying to make the fix for the height, but still no luck.

Fix annoying behaviour when resizing Field Mapping Tool.

---

safe/gui/widgets/dock.py

* Ticket: None
* Description: We agreed with @ismailsunni to make autoconnect slots deprecated. I'm removing them in the dock. I quick search `def on_` in the project gives 54 matches. I will remove them step by step.

remove some autoconnect slots in the dock

---

safe/report/extractors/composer.py

* Ticket: #4477 
* Description: So there is a problem if we use a not transparent aggregation layer, the map report will put the aggregation layer on the top of impact layer. Now we want to put the aggregation layer anywhere below the impact layer.

change layer order - aggregation layer below impact layer

---

safe/impact_function/impact_function.py

Since I hacked the way to put profiling in the output layer and the hack only works on non debug mode, I use the hack only in non debug mode.

Only set profiling to provenance if not in debug mode.

---

Makefile
run-docker-test.sh
start-docker-test.sh

* Ticket: #
* Description: While my test environment is broken, I'm using docker.
Running all tests in local, I have one failing test, in 4 mins 30 seconds:
```
======================================================================
FAIL: test_minimum_needs_outputs (report.test.test_impact_report.TestImpactReport)
Test generate minimum needs section.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/tests_directory/safe/report/test/test_impact_report.py", line 1035, in test_minimum_needs_outputs
expected_context.strip(), actual_context.strip(), message)
AssertionError: For this analysis, the following displacement rates were used: Wet - 90%, Dry - 0%
For this analysis, the following displacement rates were …
```

add make command to run tests in docker

---

.flake8
.travis.yml
Makefile
safe/test/test_python_pep.py

* Ticket: #
* Description: We got a warning since a few days saying that pep8 is going to be removed and need to be replaced by pycodestyle.
I saw that already one year ago. Time to switch

switch from pep8 to pycodestyle

---

safe/common/custom_logging.py
safe/gui/tools/batch/batch_dialog.py
safe/gui/tools/osm_downloader_dialog.py
safe/gui/widgets/message_viewer.py
safe/impact_function/impact_function.py
safe/plugin.py
safe/utilities/i18n.py
safe/utilities/osm_downloader.py

* Ticket: #
* Description: One step forward to QGIS 3 as we will have to switch to QgsSettings. So we can do this change in our class to switch them all ;-)
@ismailsunni There is still a few. And some are using the QSettings for testing. I will let them or you can help. I was doing this as a break

use our internal settings class instead of QSettings

---

safe/gui/tools/batch/batch_dialog.py
safe/gui/tools/osm_downloader_dialog.py
safe/gui/widgets/profile_widget.py
safe/gui/widgets/test/test_profile_widget.py
safe/messaging/item/abstract_list.py
safe/messaging/item/bulleted_list.py
safe/messaging/item/cell.py
safe/messaging/item/emphasized_text.py
safe/messaging/item/horizontal_rule.py
safe/messaging/item/image.py
safe/messaging/item/important_text.py
safe/messaging/item/line_break.py
safe/messaging/item/link.py
safe/messaging/item/numbered_list.py
safe/messaging/item/row.py
safe/report/extractors/aggregate_postprocessors.py
safe/utilities/i18n.py
safe/utilities/pivot_table.py
safe/utilities/test/test_osm_downloader.py

From `""" ([a-zA-Z .]*)"""` to `"""$1"""`
From `"""([a-zA-Z ]*) ."""` to `"""$1."""`
From `"""([a-zA-Z ]*)"""` to `"""$1."""`
* Ticket: #
* Description: Cleaning docstrings with regexp

Clean one line docstrings

---

safe/definitions/layer_purposes.py
safe/impact_function/multi_exposure_wrapper.py
safe/impact_function/test/test_multi_exposure_impact_function.py

* Ticket: #4495 
* Description: To be able to know how many layers a multi exposure analysis will produce

add function to know layers provided by a multiexposure analysis

---

safe/common/exceptions.py
safe/metadata/test/test_metadata.py

* Ticket: #
* Funded by: 
* Description: I found another string not taken by the regex, the `'` was missing.
improve the regex ([a-zA-Z' ]*)

improve the regex ([a-zA-Z' ]*)

---

safe/definitions/test/test_utilities.py
safe/definitions/utilities.py
safe/gui/tools/options_dialog.py
safe/gui/ui/options_dialog_base.ui
safe/gui/widgets/profile_widget.py
safe/gui/widgets/test/profile_widget_example.py
safe/report/test/test_impact_report.py
safe/utilities/test/test_settings.py

- Move logo preview
- Use percentage properly in preference spin box
- Use `population_preference` to make it explicit in the QSetting (previously only `profile`)

Another Profile Polishing

---

safe/gui/tools/wizard/test/test_keyword_wizard.py
safe/gui/tools/wizard/wizard_dialog.py

* Ticket: #4601 
- Keep extra keywords when assigning keywords with wizard
- (Note) Perhaps we need another step to add extra keywords in the wizard. Not for current release of course.

Keep extra keywords fix #4601.

---

safe/impact_function/impact_function.py
safe/report/expressions/map_report.py

* Ticket: #4441
* Description: After the great work from @ivanbusthomi ;-)
The ordering is done by distance only on the layer itself before the end of the impact function.
It's like a quick hack, but I guess, as we don't have any other use case, I don't want to spend too much time on something cleaner.
Then some new expressions are introduced:
```
'Located ' || to_int(distance_to_nearest_place()) || 'm, ' ||  to_int(bearing_to_nearest_place()) || ' ˚ ' ||  direction_to_nearest_place() || ' of ' ||  name_of_the_nearest_place() 
```
it becomes
Some questions/todo:
* shouldn't we prefix all inasafe expressions by `inasafe_` to make a kind of namespace?
* The distance is always in meters for now. We need to improve this
* I guess we should remove layer_id from the project …

bearing/direction/distance/name of the nearest place in QGIS expressions

---

safe/gui/tools/shake_grid/shakemap_converter_dialog.py
safe/gui/ui/shakemap_importer_dialog_base.ui

* Ticket: #4614 
- Hide smoothing option in non developer mode

Hide smoothing option in non developer mode.

---

safe/plugin.py

* Ticket: Part of #4628 
- My silly mistake, removing important toobar.
In developer mode:
In non-developer mode

Silly mistake, removing OSM toolbar.

---

safe/gui/tools/multi_exposure_dialog.py
safe/impact_function/impact_function.py
safe/impact_function/multi_exposure_wrapper.py
safe/impact_function/test/test_impact_function.py
safe/test/data/scenario/earthquake_raster_on_raster_population.json
safe/test/data/scenario/earthquake_raster_on_vector_places.json
safe/test/data/scenario/earthquake_raster_on_vector_population.json
safe/test/data/scenario/polygon_classified_on_line.json
safe/test/data/scenario/polygon_classified_on_point.json
safe/test/data/scenario/polygon_classified_on_vector_population.json
safe/test/data/scenario/polygon_classified_on_vector_population_multi_fields.json
safe/test/data/scenario/polygon_continuous_on_line.json
safe/test/data/scenario/raster_classified_on_classified_raster.json
safe/test/data/scenario/raster_classified_on_indivisible_polygons_with_grid.json
safe/test/data/scenario/raster_classified_on_line_with_grid.json
safe/test/data/scenario/raster_classified_on_vector_population_multi_fields.json
safe/test/data/scenario/raster_continuous_on_divisible_polygons_with_grid.json
safe/test/data/scenario/raster_continuous_on_line.json
safe/test/data/scenario/raster_continuous_on_raster_population.json
safe/utilities/gis.py

* Ticket: #4638
* avoid two prepare steps in multi exposure
* use selected areas when we clone a layer
* improve output CRS in impact function

avoid two prepare steps in multiIF, use selected areas when we clone a layer

---

safe/gui/widgets/dock.py

* Ticket: #4649
* Description: fix dock when selecting multi-exposure IF output layers and disable print button when multi-exposure IF layer is being selected

Multi exposure with no keywords message

---

safe/gis/vector/summary_1_aggregate_hazard.py
safe/gis/vector/summary_2_aggregation.py
safe/gis/vector/summary_3_analysis.py
safe/gis/vector/summary_4_exposure_summary_table.py
safe/gis/vector/summary_tools.py

* Ticket: #4571
* Description: This is a scary PR. We have this bug since 4.0. The thing is I was using a `if not value`. But in the ticket #4571, the value was `0` so then it was converted to `Not exposed`, but 0 was right.
I'm just waiting for travis first.

fix if statement if value is 0

---

safe/impact_function/impact_function.py

* Ticket: #4652 
* Description: previously the requested extent provenance are stored as a wkt coordinates

set requested extent as wkt polygon

---

safe/gui/tools/multi_exposure_dialog.py
safe/gui/widgets/dock.py

* Ticket: Help #4695 
It's now displaying a warning at the end of the analysis if it's not generating reports.

add logger info about generating reports checkbox

---

safe/common/parameters/percentage_parameter_widget.py
safe/common/parameters/test/test_percentage_parameter_widget.py
safe/gui/tools/options_dialog.py
safe/gui/widgets/profile_widget.py

* Ticket: #4682 #4145 #4508 
- Use percentage widget for demographic default.

Use percentage spinbox for demographic default.

---

safe/definitions/exposure.py

* Ticket: #4592 
* Description: allow population exposure to be point dataset
I tested locally with a point datatset, it works.
@Charlotte-Morgan Is-it all fine?

allow population exposure to be point dataset

---

safe/plugin.py

* Ticket: #4734
The issue is after updating option for using hiden layer also, the dock is not immediately updated. We need to trigger it manually. This PR triggers it automatically.
Before applying my PR:
After applying my PR:

Fix #4734, update dock after updating option.

---

safe/utilities/metadata.py
safe/utilities/test/test_metadata.py

* Ticket: #4625 
- 3.5 use `generic` keyword for hazard key, but in 4.x we use `hazard_generic`, so I need to put an if.
- Based on my diagram https://docs.google.com/spreadsheets/d/1AhfYz5ynpmnsibTiACILDc-l5GK7SVsG_0ueByyds2g/edit#gid=0 the land_cover put the field in `structure_class_field`, so I need to put another if.

Use generic as key and special case for land cover exposure.

---

safe/gui/widgets/profile_widget.py

* Ticket: #4778 
- The population parameter doesn't show the hazard classification that doesn't `exposure` (it means it supports all exposures). So, it gets the wrong affected calculation.
- You need to restore default classification to fix this error first @felix-yew 
- Result:
Future works (perhaps):
- Make sure all hazard classification write the supported exposure
- Get the default from the default one (currently set to False)
- Make a button to "Add" missing classification to avoid removing current profile.

Fix #4778 also put missing hazard classification for all exposure.

---

safe/gui/ui/print_report_dialog.ui

* Ticket: #
* Description: Remove the `print report as PDF`. I'm not a UX designer, but it's less words in the UI
Before:
After:

avoid duplicate label in print dialog

---

safe/gui/tools/help/welcome_message.py
safe/gui/tools/options_dialog.py
safe/gui/ui/options_dialog_base.ui

* Ticket: #4787 
Address all (3) items from the ticket:
- Change text in welcome text from parameters to population parameters
- Make sure the button to open the logo do properly (only changed when the checbkbox is checked)
- Swap vetically the logo preview and the custom logo path
- Better tab order

Fix #4787 polish welcome message

---

safe/report/expressions/map_report.py

* Ticket: #4714 
- Use default north arrow and logo if the expression give not exist logo

Fix #4714 use default file for north arrow and logo expression.

---

safe/gis/vector/summary_3_analysis.py
safe/test/data/gisv4/intermediate/aggregate_classified_hazard_summary.xml

* Ticket: #4483 
- Add summarizer for extra attribute in for the analysis summary. This will make the report show correct number for total exposed for population in place.

Add summarizer in analysis summary.

---

safe/gui/tools/options_dialog.py
safe/gui/widgets/profile_widget.py

- Fix restore button (previously it will restore not from the default value)
- Use definition for the general content, and update the value based on the user's setting. Previously, it will directly use from the user one. It will make a problem if don't have a definition. Another feature by doing this, we can have the classes sorted like in definition.

Fix 4788 polish population parameter

---

safe/gui/ui/print_report_dialog.ui

Before:
After:
Please check how is it in Windows (@ivanbusthomi @samnawi @felix-yew @timlinux  ) and Ubuntu @myarjunar

Fix shrink text in print dialog in MacOS.

---

safe/definitions/provenance.py
safe/gis/generic_expressions.py
safe/gui/ui/dock_base.ui
safe/gui/widgets/dock.py
safe/impact_function/impact_function.py
safe/impact_function/style.py
safe/report/extractors/aggregate_postprocessors.py
safe/report/extractors/aggregate_result.py
safe/report/extractors/analysis_detail.py
safe/report/extractors/analysis_provenance_details.py
safe/report/extractors/general_report.py
safe/report/extractors/impact_table.py
safe/report/extractors/minimum_needs.py
safe/report/extractors/mmi_detail.py
safe/report/extractors/population_chart.py
safe/report/impact_report.py
safe/report/test/test_impact_report.py
safe/utilities/rounding.py

* Ticket: Working for #4828
Debug mode is very strict by running more tests and saving to disk all intermediate layers. By adding this new flag, we can run the impact function quickly without the rounding

add rounding flag if dev mode

---

safe/gui/widgets/dock.py

* Ticket: #
* add color warning if the user is debugging

add color warning if the user is debugging

---

safe/gui/widgets/dock.py

* Ticket: #
* Funded by: 
* Fix bug:
```
2018-01-15T09:15:43 1 Traceback (most recent call last):
File "C:/Users/fyanuar/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1318, in accept
self.use_rounding_action.isChecked())
AttributeError: 'Dock' object has no attribute 'use_rounding_action'
```

Fix bug in dock, missing attribute.

---

safe/definitions/hazard_classifications.py

* Ticket: #4875 
* Funded by: 
* Enable Earthquake MMI scale hazard classification to be used for place exposure.

enable earthquake_mmi_scale on place

---

safe/utilities/geonode/readme.md
safe/utilities/geonode/test/test_upload_layer_geonode.py
safe/utilities/geonode/upload_layer_requests.py

* Ticket: #
* Upload a layer to Geonode
```
from safe.utilities.upload_layer_geonode import upload, login_user
session = login_user('http://staging.geonode.kartoza.com/', 'login', 'password')
upload_layer = upload('http://staging.geonode.kartoza.com/', session, iface.activeLayer().source())
```
Still an issue with UTF-8 on some vector layers. But it seems working well for tiff, asc and some shp
@lucernae @ismailsunni FYI for realtime. We agreed with Tim that we will add a tool in InaSAFE desktop to publish layers easily
I need to try to port it with QgsNetWorkAccess manager. But I would like to keep it python generic so it can be easily copy/paster.

add function to upload a layer to a Geonode instance

---

safe/gui/tools/shake_grid/shake_grid.py

The old shake grid code directly uses tzinfo to replace timezone information.
However in pytz, the timezone offset being used depends on the actual datetime it applies to.
For example, in the old code:
2018-01-01 07:07:00 Waktu Indonesia Barat if applied with timezone Asia/Jakarta directly using tzinfo, will have timezone offset +0707 (Batavia timezone in the old days), which means the previous datetime means 2018-01-01 00:00:00 in UTC.
Apply the timezone using pytz localize method. With the following fix, the timezone offset will be correct: +0700 (Jakarta, modern times). Which means, the previous datetime will be correctly converted to UTC as 2018-01-01 00:07:00.
Needed for PR: https://github.com/inasafe/inasafe-realtime/pull/194

Fix timezone conversion for shake_grid

---

safe/common/exceptions.py
safe/gui/tools/osm_downloader_dialog.py
sideci.yml

https://stackoverflow.com/questions/1272138/baseexception-message-deprecated-in-python-2-6
* Ticket: #
* Description: A little step forward to Python 3 maybe
While I'm debugging, I have some python warnings.
We still have some `exception.message` where we write on our `Message` object. I guess it's not so good but I'm not sure how to remove these.
it seems the message is already included in the constructor.
I'm not sure about this.

trying to remove "message" from exception

---

safe/test/utilities.py

* Ticket: #
* add setting for inasafe default output directory when reinstantiating qgis application

add setting for inasafe output directory

---

safe/report/expressions/html_report.py
safe/report/extractors/action_notes.py
safe/report/extractors/aggregate_postprocessors.py
safe/report/extractors/aggregate_result.py
safe/report/extractors/analysis_detail.py
safe/report/extractors/analysis_provenance_details.py
safe/report/extractors/analysis_question.py
safe/report/extractors/general_report.py
safe/report/extractors/minimum_needs.py
safe/report/extractors/mmi_detail.py
safe/report/test/test_impact_report.py
safe/report/test/test_impact_report_earthquake.py
safe/resources/report-templates/standard-template/jinja2/action-note-categorized.html
safe/resources/report-templates/standard-template/jinja2/aggregation-postprocessors.html
safe/resources/report-templates/standard-template/jinja2/aggregation-result.html
safe/resources/report-templates/standard-template/jinja2/analysis-detail.html
safe/resources/report-templates/standard-template/jinja2/analysis-provenance-details-simplified.html
safe/resources/report-templates/standard-template/jinja2/analysis-provenance-details.html
safe/resources/report-templates/standard-template/jinja2/analysis-question.html
safe/resources/report-templates/standard-template/jinja2/base.html
safe/resources/report-templates/standard-template/jinja2/bullet-list-section.html
safe/resources/report-templates/standard-template/jinja2/general-report.html
safe/resources/report-templates/standard-template/jinja2/minimum-needs.html
safe/resources/report-templates/standard-template/jinja2/mmi-detail.html

* Ticket: fix #4964
* we are separating the analysis summary report into expression per section

add expressions for retrieving each sections of report

---

safe/definitions/exposure.py
safe/definitions/test/test_utilities.py

To represents things like powerlines...
* Ticket: #
* Funded by: 
* Accept lines layers for structure, which can be used to represent power lines (and probably some other structures as well, as bridges, pipelines, etc...).

Accept line layers for structures

---

metadata.txt
safe/impact_function/impact_function.py
safe/impact_function/postprocessors.py
safe/impact_function/test/test_impact_function.py
safe/impact_function/test/test_postprocessors.py
safe/processors/__init__.py
safe/processors/population_post_processors.py
safe/processors/post_processors.py

* Funded by: GA
* Description: This PR adds the possibility to allow running a postprocessors only for certain hazard and exposures combination.
The run_filter can be completely omitted to allow the postprocessor to always run. Also only one of the two filters can be defined to put limitation only the specific field.
```post_processor_filter_example = {
'key': 'post_processor_filter_test',
'name': tr('Should run filter Processor for tests'),
'description': tr(
'A post processor to demo how to use the should run filter. this '
'postrocessor would run only for flood or cyclone on structure. The '
'run_filter can be completely omitted to allow the postprocessor to '
'always run. Also only one of the two filters can be defined to put'
'limitation only the specific field.'
),
'run_filter': { …
```

Allow running postprocessors only for certain hazard and exposures

---

safe/gis/test/test_tools.py
safe/gis/tools.py
safe/impact_function/impact_function.py
safe/impact_function/multi_exposure_wrapper.py
safe/report/impact_report.py
safe/test/data/gisv4/aggregation/small_grid.qlr
safe/test/test_python_pep.py

In some cases, we might want to have a pre process exactly before the report generated. E.g, change QGIS composition context, change settings, etc.
Also handle QLR layer input for Impact Report.

Add customizability for impact report generation

---

safe/impact_function/test/test_impact_function.py
safe/report/test/test_impact_report.py
safe/report/test/test_impact_report_earthquake.py

Some of the unit test is stalling in QGIS 3.4
We don't know exactly why, yet.
The stalling code is inside qgis binary.
Running the unit test from inside QGIS Desktop works.
Running the unit test from QGIS 3.10 docker container works.

Skip stalling unit tests in QGIS 3.4
