inasafe/inasafe

- .github/PULL_REQUEST_TEMPLATE.md
- scripts/tag-release.sh
-  Make the output of tag-release prettier.
- Little fix on PR Template.
> Cosmetic in template and script

- safe/definitions/field_groups.py
- safe/utilities/test/test_metadata.py
* Ticket : #4077
- Make sure the metadata able to support field groups
- Add group in the field
> Fix 4077 metadata support

- .travis.yml
updating @timlinux PR.
* Ticket : PR #4075 
* Funded by :  DFAT
- Help @timlinux fix his PR
> Added webhook for travis to inasafe-notices matrix room, 

- safe/definitions/earthquake.py
- safe/definitions/hazard_classifications.py
- safe/gui/tools/help/definitions_help.py
- safe/gui/tools/options_dialog.py
- safe/gui/tools/wizard/wizard_dialog.py
- safe/gui/tools/wizard/wizard_utils.py
- safe/impact_function/earthquake.py
- safe/impact_function/impact_function.py
- safe/utilities/default_values.py
- safe/utilities/settings.py
- safe/utilities/test/test_settings.py
* Ticket : #4093
* Description : First PR to split the logic for the fatality rate
Adding fatality rate into definitions, according to the EQ fatality function used in your settings.
> Fatality rate

- metadata.txt
* Ticket : #
* Funded by : WB/GFDRR
* Description : 4.0.1 does not show in the plugin manager on 2.18.5
> Attempt to fix issue where plugin does not show up on QGIS 2.18

- safe/definitions/exposure.py
- safe/impact_function/style.py
- safe/utilities/rounding.py
- safe/utilities/test/test_rounding.py
* Ticket : part fix #4062
* Description : This will display the real value when it's not population and value <1000 in the legend only. For the report, @myarjunar (cc @lucernae ), can you have a look after this PR is merged?
> for not population, display real value if <1000

- metadata.txt
> Updated metadata

- safe/definitions/concepts.py
- safe/definitions/field_groups.py
- safe/definitions/fields.py
- safe/definitions/post_processors.py
- safe/test/data/scenario/polygon_classified_on_vector_population.json
* Ticket : #4069 
- More new fields, groups, and postprocessors.
> Metadata update 4069

- safe/definitions/exposure.py
- safe/definitions/hazard.py
- safe/definitions/layer_purposes.py
- safe/definitions/test/test_utilities.py
- safe/definitions/utilities.py
- safe/gui/tools/field_mapping_dialog.py
- safe/gui/tools/test/test_field_mapping_dialog.py
- safe/gui/widgets/field_mapping_widget.py
* Ticket : #4103 
- Filter out layer that doesn't have layer groups.
- Tidy up definitions.
> Fix 4103 polish field mapping

- safe/gui/tools/options_dialog.py
- safe/gui/tools/wizard/wizard_dialog.py
- safe/impact_function/impact_function.py
* Ticket : #4071 
* Description : Use global default which are set by the user, not from InaSAFE
Need to backport the commit to master
> Global default

- resources/report-templates/standard-template/jinja2/aggregation-postprocessors.html
- safe/definitions/field_groups.py
- safe/definitions/post_processors.py
- safe/definitions/reports/components.py
- safe/report/extractors/aggregate_postprocessors.py
- safe/report/test/test_impact_report.py
* Ticket : #4069 
We can add group notes in field groups definition.
> Reporting global default

- safe/definitions/field_groups.py
- Fix typos on naming
- Set dictionary to empty for count ratio mapping
> Make uniform naming.

- safe/report/extractors/aggregate_postprocessors.py
* Ticket : No ticket
- Fix failed test in develop (due to not update the PR)
> Fix failed test in develop.

- safe/common/parameters/group_select_parameter_widget.py
- safe/common/parameters/validators.py
- safe/definitions/default_values.py
- safe/definitions/field_groups.py
- safe/gui/tools/field_mapping_dialog.py
- safe/gui/tools/wizard/step_kw44_fields_mapping.py
- safe/gui/tools/wizard/wizard_dialog.py
- safe/gui/widgets/field_mapping_tab.py
- safe/plugin.py
- safe/test/data/gisv4/aggregation/small_grid_complex.xml
- safe/test/data/gisv4/exposure/population_multi_fields.xml
* Ticket : #4113
- Add feature to create validator in field group. Used in Field mapping tool and keywords wizard.
- Fix python error when select no keywords found layer
> Add dynamic validator for field group

- safe/gui/tools/field_mapping_dialog.py
- safe/gui/tools/test/test_field_mapping_dialog.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
- safe/gui/tools/wizard/wizard_dialog.py
- safe/gui/widgets/field_mapping_tab.py
- safe/gui/widgets/field_mapping_widget.py
- safe/impact_function/test/test_impact_function.py
* Ticket : #4128 
- Solution: make sure wizard and FMT always read from file, not from layer properties
> Fix 4128 keyword changed

- safe/definitions/versions.py
- safe/impact_function/impact_function.py
* Ticket : No ticket issue
- Update keyword version to 4.1
> Set keyword version to 4.1

- safe/gui/widgets/field_mapping_tab.py
- safe/gui/widgets/field_mapping_widget.py
* Ticket : #4137 
> Surprised that I have written TODO in the file because I was waiting for the description to be written.
cc @timlinux
> Fix 4137 add field group description

- resources/report-templates/standard-template/jinja2/general-report.html
> fix general report floats to right when open report in largest size

- resources/report-templates/standard-template/jinja2/analysis-detail.html
- safe/report/extractors/analysis_detail.py
- safe/report/test/test_impact_report.py
> Reporting column order

- safe/definitions/default_values.py
> Fix typo and tidy up code.

- safe/common/parameters/group_select_parameter_widget.py
- safe/gui/widgets/field_mapping_tab.py
* Ticket : #4151 
- Adding help text for field in field mapping
> Fix 4151 add help text field group

- safe/definitions/field_groups.py
- safe/gui/widgets/field_mapping_tab.py
* Ticket : #4157 
- We can put the same field into several field group.
cc @Charlotte-Morgan @samnawi
> Fix 4157 non exclusive field

- safe/utilities/test/test_rounding.py
* Ticket : No ticket.
- Remove random failed test.
> Remove random failed test.

- safe/gui/tools/field_mapping_dialog.py
- safe/gui/tools/options_dialog.py
- safe/gui/tools/test/test_options_dialog.py
- safe/plugin.py
* Ticket : No ticket
- Update Dock after Finish doing Field Mapping
- Remove dock dependency from option dialog
- Tidy up code
> Update Dock after Finish doing Field Mapping

- resources/report-templates/standard-template/jinja2/base.html
- safe/definitions/reports/components.py
- safe/report/impact_report.py
- safe/report/report_metadata.py
> make the report relocatable

- safe/impact_function/impact_function.py
- safe/utilities/settings.py
* Ticket : #3878 
-  Use ISO 19115 keywords from setting on analysis result.
> Fix #3878. Use ISO 19115 keywords from setting on analysis result.

- .github/PULL_REQUEST_TEMPLATE.md
- safe/gis/vector/prepare_vector_layer.py
- safe/gis/vector/summary_1_aggregate_hazard.py
- safe/gis/vector/summary_2_aggregation.py
- safe/gis/vector/summary_3_analysis.py
- safe/gis/vector/summary_4_exposure_summary_table.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/peta_bencana_dialog.py
- safe/gui/tools/wizard/wizard_step_browser.py
- safe/impact_function/create_extra_layers.py
- safe/impact_function/impact_function.py
* Description: Remove deprecated calls in the QGIS api
> remove deprecated calls in the QGIS api

- safe/definitions/default_settings.py
- safe/gui/tools/options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/impact_function/create_extra_layers.py
- safe/impact_function/impact_function.py
- safe/utilities/profiling.py
* Ticket: No
- Add option to disable memory profile
2x faster without profiling.
> Show memory profile setting

- safe/definitions/hazard_classifications.py
- safe/report/test/test_impact_report.py
update affected status and displacement rates for generic impact and …volcano KRB
* Ticket: #3847 
* Funded by: DMI
change affected status to false for low generic hazard and KRB I
change displacement rate to 100% for generic high and medium and KRB II and III
> part fix #3847

- safe/impact_function/create_extra_layers.py
- safe/impact_function/impact_function.py
- safe/utilities/profiling.py
* Ticket: No ticket reported by @gubuntu 
* Description: improve the profiling table
> improve the profiling table

- safe/report/extractors/aggregate_postprocessors.py
- safe/report/extractors/aggregate_result.py
- safe/report/extractors/analysis_detail.py
- safe/report/extractors/general_report.py
- safe/report/extractors/infographics.py
- safe/report/extractors/minimum_needs.py
- safe/report/extractors/mmi_detail.py
- safe/report/test/test_impact_report.py
- safe/utilities/rounding.py
* Ticket: #4062 
* Description:      Only round the number when it is population exposure and it is not in debug mode
> Report rounding

- safe/gis/raster/clip_bounding_box.py
* Ticket: #4067 
* Description: Fix Unboundlocalerror
@NyakudyaA It will not fix your error. You still have a problem with Processing, but at least, the analysis will continue without python exception. The analysis will be a little bit slower.
> fix unboundlocalerror

- safe/definitions/field_groups/age_field_group.py
* Ticket: No ticket number
- Remove sum of age ratio validation.
cc @samnawi
> Remove sum age ratio validation.

- safe/definitions/post_processors/__init__.py
- safe/test/data/scenario/earthquake_raster_on_raster_population.json
- safe/test/data/scenario/earthquake_raster_on_vector_population.json
- safe/test/data/scenario/polygon_classified_on_vector_population.json
- safe/test/data/scenario/polygon_classified_on_vector_population_multi_fields.json
- safe/test/data/scenario/raster_classified_on_vector_population_multi_fields.json
* Ticket: No ticket number
- Add missing post processor.
Please check @samnawi
> Add gender_vulnerability_postprocessors.

- safe/definitions/field_groups/field_groups.py
- safe/gui/tools/options_dialog.py
* Ticket: #4194 
- Add missing field groups that are missing
> Fix #4195, add missing field group options.

- safe/definitions/earthquake.py
- safe/gui/tools/options_dialog.py
- safe/gui/ui/options_dialog_base.ui
* Ticket: #4192 #4193
* Description: Improve the EQ selection in settings
> Improve the EQ selection in settings

- safe/gis/sanity_check.py
- safe/impact_function/impact_function.py
- safe/impact_function/test/test_impact_function.py
* Ticket: #4200
* Description: Check if inasafe_fields is correct before to run the IF
> check if layers have some inasafe_fields are up to date

- safe/gis/vector/prepare_vector_layer.py
* Ticket: #4200
* Description: Skip QGIS Expression if it's not needed
> skip qgis expression if we made a copy

- resources/css/InaSAFE.css
- resources/report-templates/standard-template/jinja2/analysis-provenance-details.html
- safe/definitions/reports/components.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/batch/batch_dialog.py
- safe/impact_function/impact_function.py
- safe/impact_function/test/test_impact_function.py
- safe/report/extractors/analysis_provenance_details.py
- safe/report/impact_report.py
- safe/report/test/fixtures/hello-world.html
- safe/report/test/hello_world_report.py
- safe/report/test/test_earthquake_report.py
- safe/report/test/test_impact_report.py
- safe/utilities/keyword_io.py
- safe/utilities/utilities.py
* Ticket : #4074 
It would be great if there is any feedback @timlinux @ivanbusthomi @Charlotte-Morgan
> add tree view analysis provenance details

- README.md
- safe/gui/ui/options_dialog_base.ui
- safe/impact_function/impact_function.py
- scripts/update-user-docs.sh
* Description: show busy in the memory profiling
> show busy in the memory profiling

- safe/gui/tools/shake_grid/shakemap_converter_dialog.py
- safe/gui/tools/shake_grid/test/test_shakemap_converter_dialog.py
- safe/gui/ui/needs_manager_dialog_base.ui
* Ticket: #4205
* Description: fix some small issues in the shakemap converter
CC : @gubuntu
> fix some small issues in the shakemap converter

- safe/metadata/property/dictionary_property.py
* Ticket: while trying to fix #4220
* Description: make a recursive call to serialize a dict
> make a recursive call to serialize a dict

- resources/report-templates/standard-template/jinja2/analysis-provenance-details-layout.html
- resources/report-templates/standard-template/jinja2/analysis-provenance-details-simplified.html
- resources/report-templates/standard-template/jinja2/impact-report-layout.html
- safe/definitions/reports/components.py
- safe/report/extractors/action_notes.py
- safe/report/extractors/analysis_provenance_details.py
- safe/report/test/test_impact_report.py
* Ticket: #
* Description: Separata provenance details tree to its own report and put the old provenance details in the main report
> Reporting separate provenance tree

- safe/impact_function/impact_function.py
- safe/impact_function/test/test_impact_function.py
- safe/report/extractors/composer.py
- safe/report/extractors/infographics.py
- Add duration of impact function in the provenance
> Add duration to impact function.

- safe/gis/vector/prepare_vector_layer.py
- safe/gis/vector/test/test_prepare_vector_layer.py
* Ticket: #
* Description: WIP
> use definition to create fields

- safe/test/data/gisv4/exposure/population_multi_fields.qml
- safe/test/data/gisv4/project.qgs
> add some missing lauers to gisv4 project

- safe/gis/vector/prepare_vector_layer.py
- safe/gui/tools/peta_bencana_dialog.py
* Description: Remove some deprecated calls from the QGIS api
> remove deprecated calls from QgsExpressions

- safe/definitions/default_settings.py
- safe/gui/tools/options_dialog.py
- safe/gui/tools/test/test_options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/impact_function/impact_function.py
- safe/test/data/gisv4/project.qgs
* Description: Since InaSAFE V4, we have many outputs. Having a text box in settings asking for the default analysis title doesn't make any sense no. I'm removing it from InaSAFE settings
> Fix impact function title

- safe/gui/widgets/message_viewer.py
* Ticket: #
* Description: roll back save as pdf logic
> use the first save as pdf logic

- safe/gui/tools/help/definitions_help.py
* Ticket: #4232
* Description: add table for exposure definitions
> add table for exposure definitions

- safe/definitions/fields.py
> add pregnant and lactating displaced to the count fields

- safe/definitions/exposure_classifications.py
* Ticket: #4246 
Changes the classification name from `water supply`  to `water`, and description for `water supply` to `water bodies`
> Update for Badan Geologi landcover classification

- safe/metadata/base_metadata.py
- safe/metadata/test/test_generic_metadata.py
* Ticket: #3857 
- Ignore filtering in layer when checking a layer is remote or local
> Fix #3857. Ignore filter in path.

- headless/tasks/inasafe_wrapper.py
- safe/definitions/default_settings.py
- safe/metadata/metadata_db_io.py
- safe/test/utilities.py
- safe/utilities/keyword_io.py
- safe/utilities/settings.py
- safe/utilities/test/test_keyword_io.py
* Ticket: #3751 
- Use default db path from definition
- Clean KeywordIO
> Fix #3751. Set to use default db path from definition.

- CHANGELOG
- metadata.txt
> Updated changelog and metadata for release

- safe/definitions/exposure.py
- safe/definitions/exposure_classifications.py
- safe/definitions/hazard.py
- safe/gis/vector/prepare_vector_layer.py
- safe/gui/tools/wizard/step_kw40_classify.py
- safe/report/processors/default.py
* Ticket: adresses #3626 
* Funded by: WB GFDRR
This PR introduces a new classification for exposure data. This classification is data driven, meaning that classes are automatically generated based on the unique values present in the dataset.
> Allow exposure data driven classification

- safe/plugin.py
* Ticket: #4284
* Funded by: WB/GFDRR
* Description:
> [BACKPORT] Fix issue where keywords wizard icon was not enabling

- metadata.txt
- safe/plugin.py
* Ticket: #
* Funded by: 
* Description:
> Backport fix for #4284 to master

- safe/impact_function/impact_function.py
- safe/test/data/scenario/polygon_continuous_on_line.json
* Ticket: #4289
* Description: do not use valuemap algo with continuous dataset
I expect travis to fail. We have already some scenarios running with continuous hazard data. I will check these tests.
> do not use valuemap algo with continuous dataset

- metadata.txt
- safe/report/extractors/infographic_elements/svg_charts.py
* Ticket: #4289
* Description: Fix division by zero in reporting
> fix python exception when doing a division by 0

- resources/qgis-composer-templates/a4-landscape-blue.qpt
- resources/qgis-composer-templates/a4-portrait-blue.qpt
* Ticket: #3998 #4047 
* Description: Only shoe legend with the feature that only appears in the map
> update map template with filtered legend

- safe/report/extractors/analysis_detail.py
* Ticket: #4258 
* Description:
> fix value in total row in analysis detail section

- safe/gui/tools/minimum_needs/needs_calculator_dialog.py
* Ticket: #4117 
* Description: create unique filename in the output directory so it will not overwrite the previous output with the same input
> fix minimum needs calculator output location (unique filename)

- metadata.txt
- safe/definitions/test/test_utilities.py
- safe/definitions/utilities.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/batch/batch_dialog.py
- safe/gui/widgets/dock.py
- safe/report/test/test_impact_report.py
* Ticket: #4240 
- Support custom map template
See #4298 for more detail.
> Backport 4240

- safe/gui/tools/wizard/step_kw20_unit.py
- Silly mistake, forget to remove pointer to deleted step.
I will make a unit test in the other PR
> Fix go to non existent wizard step.

- safe/gis/raster/polygonize.py
- safe/gis/raster/zonal_statistics.py
- safe/gui/tools/wizard/step_kw13_band_selector.py
- safe/test/data/gisv4/exposure/raster/population.xml
* Ticket: #4263 
* Description: Support multiband raster in the impact function
> use active band keyword in the GIS overlay analysis

- safe/common/parameters/default_select_parameter_widget.py
- safe/common/parameters/group_select_parameter.py
- safe/common/parameters/test/example.py
- safe/common/parameters/test/example_group_select.py
- safe/common/parameters/test/test_default_select_parameter.py
- safe/common/parameters/test/test_default_select_parameter_widget.py
- safe/common/parameters/test/test_default_value_parameter.py
- safe/common/parameters/test/test_default_value_parameter_widget.py
- safe/common/parameters/test/test_group_select_parameter.py
- safe/common/parameters/test/test_group_select_parameter_widget.py
- safe/definitions/constants.py
- safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
- safe/gui/tools/wizard/wizard_utils.py
- safe/gui/widgets/field_mapping_tab.py
* Ticket: #4127 
- Per @Charlotte-Morgan 's comment, change `do not use` to `do not report`.
> Change do not use to do not report. #4127

- safe/definitions/__init__.py
- safe/definitions/constants.py
- safe/definitions/keyword_properties.py
- safe/definitions/layer_purposes.py
- safe/metadata/base_metadata.py
- safe/metadata/test/data/existing_exposure_impacted.json
- safe/metadata/test/data/existing_exposure_impacted.xml
- safe/metadata/test/data/existing_generic.json
* Ticket: #4179 
- Adding definition for keyword's properties
> Adding definition of every keyword's property

- safe/gui/tools/save_scenario.py
- safe/gui/tools/wizard/step_kw43_threshold.py
* Ticket: #4306 not sure it fixes this one.
* Description: Review of the file `save_scenario.py`
> save scenario review

- safe/definitions/styles.py
- safe/gui/ui/options_dialog_base.ui
- safe/impact_function/impact_function.py
- safe/impact_function/style.py
* Ticket: #4216 issues 6 and 8
* Description: Update the style for the analysis and the aggregation layers.
> change analysis and aggregation styles, fix string about sentry

- safe/definitions/constants.py
- safe/gui/tools/extent_selector_dialog.py
- safe/gui/tools/wizard/step_fc70_extent.py
- safe/gui/tools/wizard/step_fc75_extent_disjoint.py
- safe/gui/tools/wizard/step_fc90_analysis.py
- safe/gui/ui/extent_selector_dialog_base.ui
- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
* Ticket: #2700 
* Description: This PR brings a new option to use all exposure extent:
> use exposure extent in an analysis

- safe/definitions/concepts.py
* Description: fix double demographic items in help window
> fix double demographic items in help window

- safe/report/processors/default.py
* Ticket: #4307 
* Description: Fix map report not showing if CRS is other than EPSG:4326.
> transform extent's crs to mapcomposer crs

- safe/gui/widgets/field_mapping_tab.py
* Ticket: #4127 
Small update from @Charlotte-Morgan
> Add more description to explain  #4127

- safe/definitions/concepts.py
- safe/definitions/fields.py
- safe/gui/tools/wizard/step_fc25_hazlayer_from_browser.py
- safe/gui/tools/wizard/step_fc55_agglayer_from_canvas.py
- safe/gui/tools/wizard/step_fc60_agglayer_from_browser.py
- safe/gui/tools/wizard/step_fc65_agglayer_disjoint.py
* Funded by: World Bank
* Description: Fix some strings from Transifex
> fix strings from Transifex

- safe/gui/widgets/dock.py
* Ticket: No ticket number
Previously, there is an error message since it gets QPyNullVariant when read the project variable. But, we can't write it back. I need to convert it to None.
> Change QPyNullVariant to None when store project variable.

- resources/report-templates/standard-template/jinja2/analysis-detail.html
- safe/definitions/fields.py
- safe/definitions/reports/components.py
- safe/report/extractors/analysis_detail.py
- safe/report/test/test_impact_report.py
* Ticket: #3626 
* Description: Add report for estimated land-cover productivity loss based on #3626. This report can be generic for any other type of exposure. 
cc @timlinux @Charlotte-Morgan @fredychandra
> Reporting landcover

- safe/definitions/fields.py
- safe/definitions/reports/components.py
- safe/report/extractors/aggregate_postprocessors.py
- safe/report/extractors/minimum_needs.py
- safe/report/test/test_impact_report.py
* Ticket: #4320 
* Description: Add the additional minimum needs back to the report.
cc @felix-yew @timlinux @Charlotte-Morgan
> Reporting additional needs

- safe/definitions/layer_purposes.py
- safe/gui/widgets/dock.py
- safe/test/data/impact/buildings_without_style.xml
* Ticket: #3726 
* Description: update terminology about output layers
> update terminology about output layers

- safe/definitions/field_groups/age_field_group.py
- safe/definitions/field_groups/gender_field_group.py
- safe/definitions/fields.py
- safe/definitions/hazard_classifications.py
- safe/gui/tools/help/developer_help.py
- safe/gui/tools/help/field_mapping_help.py
* Funded by: World Bank
* Description: Add some missing translations
> update some missing translations

- safe/definitions/concepts.py
- safe/definitions/fields.py
* Ticket: #3626 
- Update the definition of productivity of land cover, based on the diagram.
> Update the definition of productivity things.

- safe/definitions/provenance.py
- safe/definitions/units.py
- safe/gis/expressions.py
- safe/impact_function/impact_function.py
- safe/plugin.py
- safe/utilities/rounding.py
- safe/utilities/test/test_rounding.py
* Ticket: #4252 
* Description: add expression to fetch values from the analysis layer
> add expression to fetch values from the analysis layer

- safe/definitions/default_settings.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/help/options_help.py
- safe/gui/tools/options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/report/extractors/composer.py
- safe/report/processors/default.py
* Ticket: #4303 #3059 
* Description: Enable atlas generation.
[a4-landscape-blue.pdf](https://github.com/inasafe/inasafe/files/1197436/a4-landscape-blue.pdf)
[a4-landscape-blue.pdf](https://github.com/inasafe/inasafe/files/1197439/a4-landscape-blue.pdf)
> Enable atlas generation on reporting

- safe/gui/widgets/dock.py
- Fix not removed project variable from impact layer.
> Fix not removed variable.

- safe/report/extractors/analysis_detail.py
* Ticket: #4352 (partfix)
* Description:
> fix field not found error

- .travis.yml
- Makefile
- safe/common/exceptions.py
- safe/common/minimum_needs.py
- safe/common/parameters/default_select_parameter_widget.py
- safe/common/parameters/default_value_parameter.py
- safe/gis/vector/prepare_vector_layer.py
- safe/gui/tools/minimum_needs/needs_profile.py
- safe/gui/tools/osm_downloader_dialog.py
- safe/gui/tools/peta_bencana_dialog.py
- safe/gui/tools/wizard/step_fc40_explayer_from_browser.py
- safe/gui/tools/wizard/step_kw00_purpose.py
- safe/gui/tools/wizard/step_kw05_subcategory.py
- safe/gui/tools/wizard/step_kw10_hazard_category.py
- safe/gui/tools/wizard/step_kw15_layermode.py
- safe/gui/tools/wizard/step_kw25_classification.py
- safe/gui/tools/wizard/wizard_help.py
- safe/gui/tools/wizard/wizard_step.py
- safe/gui/tools/wizard/wizard_step_browser.py
- safe/metadata/base_metadata.py
- safe/metadata/metadata_db_io.py
- safe/test/qgis_legend_interface.py
- safe/test/test_python_pep.py
- safe/utilities/i18n.py
- safe/utilities/keyword_io.py
- safe/utilities/utilities.py
@inasafe/developers Since a long time, we are trying to have a good documentation in our code. It's time to add a check about our docstrings. We were trying to follow landscape.io these last few months.
Now, I'm adding PEP257 check on our docstrings. For now, a lot of tests are disabled according to the PEP.
I would like to enable more in the next few months. Like I would like to have D201, D202, D203 ...
These are very easy to fix every time you open a file.
http://pep257.readthedocs.io/en/latest/error_codes.html
* D400 First line should end with a period 😈
* D203 1 blank line required before class docstring
* D204 1 blank line required after class docstring etc ...
> make PEP 257 compulsory

- safe/report/processors/default.py
* Ticket: #
* Description: Quick PEP 257 on a file
> cleaning the default.py in reporting about PEP257

- resources/report-templates/standard-template/jinja2/general-report.html
- safe/definitions/field_groups/field_groups.py
- safe/definitions/reports/components.py
- safe/report/extractors/general_report.py
- safe/report/test/test_impact_report.py
- safe/report/test/test_impact_report_earthquake.py
* Ticket: #4334 
add exposed, affected, displaced people description in general report section
remove group description from this section's notes
> Reporting notes tweak

- resources/qgis-composer-templates/infographic.qpt
- safe/gis/expressions.py
* Ticket: #
* Description: fix no data placement value
> Infographic patch

- Makefile
- safe/common/exceptions.py
- safe/common/parameters/resource_parameter.py
- safe/common/parameters/resource_parameter_widget.py
- safe/common/utilities.py
- safe/gui/tools/rectangle_map_tool.py
- safe/gui/widgets/message_viewer.py
- safe/messaging/example/console_example.py
- safe/messaging/example/error_message_example.py
- safe/messaging/example/gui_example.py
- safe/messaging/item/brand.py
- safe/messaging/item/exceptions.py
- safe/metadata/property/boolean_property.py
- safe/metadata/property/character_string_property.py
- safe/metadata/property/date_property.py
- safe/metadata/property/float_property.py
- safe/metadata/property/integer_property.py
- safe/metadata/property/list_property.py
- safe/metadata/property/url_property.py
- safe/test/qgis_interface.py
- safe/test/utilities.py
- safe/utilities/file_downloader.py
* Ticket: #
* Description: add D204 check in PEP257
> add D204 check in PEP257

- safe/report/processors/default.py
* Ticket: #4271 
* Description: @wonder-sk gave me a snippet by email. It seems to work. @myarjunar can you try to see if it works.
I still don't have any map, but at least I have the north arrow!
@myarjunar we need to remove the deprecated call, also using this help it works for you:
```
composer_item = composition.getComposerItemById(item_id)
try:
html_element = composition.getComposerHtmlByItem(composer_item)
except:
pass
```
CC: @mbernasocchi
> fix how we fetch items in composer, problem with bindings

- MANIFEST.in
- setup.py
* Ticket: - 
* Description: Adding test data in the SAFE package.
> Add test data in the package.

- safe/report/processors/default.py
* Ticket: #4271 
@myarjunar Can you check it's still working for you?
For me, I have my two maps now, but the overview has still a problem with colors:
> add special case for me to have the map working

- MANIFEST.in
* Ticket: -
* Description: Adding shake grid converter data to safe package as they are needed for realtime.
> Add shake grid converter data to SAFE package.

- safe/report/expressions/infographic.py
* Ticket: #4371 
* Description:
> fix invalid expression error

- MANIFEST.in
* Ticket: - 
* Description: Adding metadata iso template and other fixtures to the SAFE package
> Add metadata iso template and other fixtures.

- safe/gui/widgets/field_mapping_tab.py
* Ticket: #4383 
- Fixing import error in @felix-yew and @samnawi computer
> Fix import error.

- safe/report/processors/default.py
* Ticket: #4047 
* Description: Adjust column size so the legend will fit the element
cc: @lrpower @felix-yew
> adjust legend column size to the template

- safe/definitions/reports/components.py
- safe/report/extractors/general_report.py
- safe/report/test/test_impact_report.py
* Ticket: #4376 
* Description: show definition notes depends on exposure type. 
cc: @lrpower @felix-yew
> General report notes

- scripts/release.sh
- Fix script release for making Nightly build working again
> Fix script release.

- resources/qgis-composer-templates/inasafe-map-report-landscape.qpt
- resources/qgis-composer-templates/inasafe-map-report-portrait.qpt
- safe/definitions/provenance.py
- safe/definitions/reports/map_report.py
- safe/impact_function/impact_function.py
- safe/plugin.py
- safe/report/expressions/map_report.py
* Ticket: #4252 
* Description: Replace token elements with qgis expression in map report
> Reporting - replace token elements

- .github/PULL_REQUEST_TEMPLATE.md
(review, test, feature collection).
- Adding checklist to the PR template (some are adapted from QGIS one)
- Should we put [FEATURE] or just directly add the feature to the metadata.txt ?
cc @timlinux @Gustry @myarjunar
> Update PR Template to help on the workflow 

- safe/definitions/utilities.py
* Ticket: #
- not generating default map report template in case hazard-exposure template was found
- we have a problem with showing the list of generated files in the dock because we need IF to be serialized
> templating update

- setup.py
* Ticket: -
* Description: Update setup.py to upload it to Pypi
> Update setup.py to upload it to pypi.

- metadata.txt
- safe/common/test/test_version.py
- safe/common/version.py
- safe/definitions/versions.py
- safe/plugin.py
- safe/utilities/osm_downloader.py
* Ticket: -
* Description: Add version and status in definitions.
> Add version and status in definitions.

- safe/gui/widgets/dock.py
* Ticket:
* Description: quick fix for print button with custom template
> fix print button with custom hazard-exposure template

- safe/definitions/reports/map_report.py
- safe/report/expressions/map_report.py
* Ticket: #
* Funded by:  DFAT
* Description:
> Fix image elements I broke and add missing black InaSAFE logo

- resources/report-templates/standard-template/jinja2/infographic-people-section-notes.html
> change notes in infographic people section

- resources/report-templates/standard-template/jinja2/infographic-people-section-notes.html
* Ticket: #
* Funded by: DFAT?DMI
* Description: Reapplying @myarjunar 's fix after fixing force update on develop branch
> change notes in infographic people section (#4407)

- safe/gis/generic_expressions.py
- safe/gui/tools/help/definitions_help.py
- safe/plugin.py
- safe/report/expressions/infographic.py
- safe/report/expressions/map_report.py
- safe/utilities/expressions.py
- safe/utilities/utilities.py
* Description: add translated expressions help
> add translated expressions help

- metadata.txt
- safe/definitions/versions.py
* Ticket: #
* Description: Bump to version 4.2.1
> Version 4.2.1

- metadata.txt
- safe/definitions/versions.py
* Ticket: #
* Description: Bump to 4.3
> bump to new 4.3

- metadata.txt
- safe/definitions/versions.py
- safe/gui/widgets/dock.py
* Ticket: #
* Description: remove method imported from test module
> remove test related method

- safe/gui/widgets/dock.py
* Ticket: #
* Description: fix error when try to install from plugin manager
> fix install from plugin manager

- safe/gui/tools/shake_grid/test/test_shake_grid.py
- safe/gui/tools/shake_grid/test/test_shakemap_converter_dialog.py
- safe/test/utilities.py
- scripts/release.sh
* Ticket: #1448
* Description: kill testdata
> kill testdata

- safe/definitions/fields.py
- safe/gis/vector/summary_3_analysis.py
- safe/gis/vector/test/test_summary.py
* Ticket: #4428 
* Description: Add total exposed field in the analysis layer
> add total exposed field

- safe/definitions/exposure.py
- safe/definitions/reports/components.py
- safe/gis/generic_expressions.py
- safe/report/extractors/aggregate_postprocessors.py
- safe/report/extractors/aggregate_result.py
- safe/report/extractors/general_report.py
- safe/report/test/test_impact_report.py
- safe/report/test/test_impact_report_earthquake.py
* Ticket: #4428 #4412 
* Description:
> aggregation specific report

- safe/gui/gui_utilities.py
- safe/gui/tools/save_scenario.py
- safe/gui/tools/test/test_save_scenario.py
- safe/gui/widgets/dock.py
- safe/utilities/utilities.py
* Ticket: None 
* Description: I'm going to use these functions in the multi exposure tool
> refactor functions in the dock about combo

- safe/definitions/reports/components.py
- safe/report/test/test_impact_report.py
* Ticket: #4428 
* Description:
> fix table title

- metadata.txt
- safe/definitions/versions.py
- safe/gui/tools/wizard/step_kw65_summary.py
- safe/gui/tools/wizard/wizard_dialog.py
* Ticket: Backport Fix from #4442 
See PR #4442
> Backport fix #4442

- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
* Ticket: #
* Description: Small bug about EQ model
> small tweaks, earthquake fatality model

- safe/report/processors/default.py
* Ticket: #4189
* Description:
> an attempt on removing the blank page at the end of the page

- metadata.txt
- safe/definitions/hazard_classifications.py
* Ticket: Backport #4456 
See PR #4456 for more detailed.
> Backport 4.2.3

- safe/definitions/reports/components.py
* Ticket: None
* Funded by: Me ;-)
* Description: fix unicode error in French
> fix unicode error in French

- safe/gui/ui/extent_selector_dialog_base.ui
> fix extent selector ui (margin, padding, etc)

- safe/test/test_python_pep.py
* Ticket: #
* Description: Make flake8 compulsory
> make flake8 compulsory

- safe/report/processors/default.py
> fix logic on checking whether the page is empty or not

- safe/definitions/keyword_properties.py
- safe/utilities/keyword_io.py
* Ticket: #4445
- Make the name in extra keywords are translatable.
> Make the extra keywords' names are translatable.

- safe/impact_function/impact_function.py
- safe/impact_function/test/test_impact_function.py
* Ticket: #4495
* Description: Just before my flight, I tried to do the request we talked this afternoon.
This is WIP, I need to take off ! ;-)
> get a list of expected layers before the IF is finished

- .flake8
- safe/common/parameters/group_select_parameter_widget.py
- safe/datastore/geopackage.py
- safe/definitions/post_processors/post_processor_functions.py
- safe/gis/vector/summary_1_aggregate_hazard.py
- safe/gis/vector/summary_2_aggregation.py
- safe/gis/vector/summary_4_exposure_summary_table.py
- safe/gis/vector/union.py
- safe/gui/tools/batch/batch_dialog.py
- safe/gui/tools/rectangle_map_tool.py
- safe/gui/tools/wizard/step_kw40_classify.py
- safe/gui/widgets/dock.py
- safe/gui/widgets/message_viewer.py
- safe/messaging/example/console_example.py
- safe/messaging/example/gui_example.py
- safe/report/extractors/aggregate_postprocessors.py
- safe/report/extractors/analysis_provenance_details.py
- safe/report/processors/default.py
- safe/test/qgis_interface.py
* Ticket: None
* Description: FIX F841 from flake8
> Fix F841 from flake8

- .travis.yml
- Makefile
- safe/common/custom_logging.py
- safe/common/test/test_custom_logging.py
* Ticket: #
* Description: disable logs on travis
> disable logs on travis

- safe/definitions/provenance.py
- safe/gui/widgets/dock.py
* Ticket: #4436 
- Remove too complex provenance from project variable. Fix #4436
> Remove too complex provenance from project variable. Fix #4436

- metadata.txt
- safe/gui/tools/wizard/step_kw30_field.py
- safe/gui/tools/wizard/step_kw65_summary.py
- safe/gui/tools/wizard/utilities.py
- safe/gui/tools/wizard/wizard_dialog.py
- safe/gui/tools/wizard/wizard_step_browser.py
* Ticket: #4485 
- Backport from PR #4489
> Backport Fix for #4485

- safe/gis/tools.py
- safe/gis/vector/reclassify.py
- safe/impact_function/impact_function.py
* Ticket: partial fix for #3469
* Description: make reclassify value public in the GIS package
> make reclassify value public in the GIS package

- safe/gis/tools.py
- safe/gui/tools/wizard/wizard_dialog.py
* Ticket: #
* Description: remove duplicate code about geometry type
> remove duplicate code about geometry type

- safe/definitions/constants.py
- safe/definitions/fields.py
- Add more field type for hazard_value field
> Add more field type for hazard_value.

- safe/definitions/constants.py
- safe/definitions/fields.py
> [Backport] Add more field type for hazard_value.

- safe/definitions/fields.py
- safe/gis/vector/summary_3_analysis.py
- safe/impact_function/create_extra_layers.py
* Ticket: #
* Description: The field is not used and the value was always one. Let's remove it for now.
Let's check what Travis is doing
> remove the analysis ID field in the analysis summary layer

- safe/definitions/reports/components.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/batch/batch_dialog.py
- safe/gui/tools/wizard/step_fc90_analysis.py
- safe/gui/widgets/dock.py
- safe/report/processors/default.py
* Ticket: #4486 
* Description: Previously, we have a logic of generating report written in each IF client with the same code just like in #3001, now we want to create only one method and write all logic to generate a report there and use only that function in each client of IF to generate report.
> Change logic for generating report to one function

- __init__.py
- safe/gis/vector/multi_buffering.py
- safe/gui/tools/peta_bencana_dialog.py
- safe/gui/tools/shake_grid/shake_grid.py
- safe/gui/tools/wizard/step_kw30_field.py
- safe/gui/tools/wizard/step_kw33_multi_classifications.py
- safe/gui/tools/wizard/step_kw40_classify.py
- safe/gui/tools/wizard/step_kw45_inasafe_fields.py
- safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py
- safe/gui/tools/wizard/utilities.py
- safe/gui/widgets/field_mapping_tab.py
* Ticket: #
* Funded by: 
* Description: No too much excitement. Just doing this quick task during the weekly sprint meeting.
> remove some dataProvider() calls

- safe/gui/analysis_utilities.py
- safe/report/extractors/action_notes.py
- safe/report/extractors/aggregate_postprocessors.py
- safe/report/extractors/aggregate_result.py
- safe/report/extractors/analysis_detail.py
- safe/report/extractors/general_report.py
- safe/report/extractors/infographics.py
- safe/report/extractors/mmi_detail.py
- safe/report/extractors/population_chart.py
- safe/report/extractors/util.py
- safe/report/test/test_util.py
> remove the usage of IF input attribute in reporting machine

- safe/report/report_metadata.py
- safe/report/test/test_impact_report.py
- safe/report/test/test_impact_report_earthquake.py
- Fixinig failed unit test in this PR https://github.com/inasafe/inasafe/pull/4529
- The reason is changed global object
```
----------------------------------------------------------------------
Ran 324 tests in 296.006s
OK (skipped=13, expected failures=10)
Finished running test test_suite.test_package.
```
> Fix changed components

- .travis.yml
- Makefile
- run-docker-test.sh
- safe/gui/tools/test/test_multi_buffer.py
- safe/test/test_python_pep.py
- start-docker-test.sh
* Ticket: #
* Description: improve the make command to run tests with docker
* One make command
* No more generated files
* Time at the end
> improve the make command to run tests with docker

- safe/impact_function/impact_function.py
- safe/impact_function/test/test_impact_function.py
- Part of impact function serialization, for testing. To get better error message.
> Better assertion for ImpactFunction

- safe/common/utilities.py
- safe/definitions/field_groups/field_groups.py
- safe/gui/tools/wizard/step_fc15_hazlayer_origin.py
- safe/gui/tools/wizard/step_fc20_hazlayer_from_canvas.py
- safe/gui/tools/wizard/step_fc25_hazlayer_from_browser.py
- safe/gui/tools/wizard/step_fc30_explayer_origin.py
- safe/gui/tools/wizard/step_fc35_explayer_from_canvas.py
- safe/gui/tools/wizard/utilities.py
- safe/messaging/error_message.py
- scripts/checkout_back_after_cleaning_from_pycharm.sh
* Ticket: #
* Description: The script I started yesterday
I already run it today @ismailsunni. It's sorting alphabetically your imports from this morning ;-)
We can use PyCharm from command line to run these process sometimes: https://www.jetbrains.com/help/pycharm/command-line-code-inspector.html
> pycharm cleaning imports and script to rollback

- safe/definitions/exposure_classifications.py
* Ticket: #
* Description: more exposure defaults strings
> more exposure defaults strings

- safe/definitions/exposure.py
- safe/gis/vector/prepare_vector_layer.py
- safe/gui/tools/wizard/step_kw40_classify.py
* Ticket: #4536 
- Do deep copy to avoid old value comes back.
> Fix #4536. Must reset data driven classification in keyword wizard.

- safe/gui/tools/options_dialog.py
- safe/gui/tools/test/test_options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- First step to have InaSAFE profile
- Reorder tab in the InaSAFE options and make it prettier
> Update Option Tabs

- safe/gui/analysis_utilities.py
- safe/gui/tools/batch/batch_dialog.py
- safe/gui/tools/wizard/step_fc90_analysis.py
- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
- safe/report/test/test_impact_report.py
* Ticket: #2670 
* Description: partfix of #4523
> create method for generating a report as a part of IF class

- safe/definitions/constants.py
- safe/utilities/settings.py
- safe/utilities/test/test_settings.py
- Basically, make the number of functions less, since there is no or 1 usage only.
> Refactor setting.

- .flake8
- safe/definitions/test/test_utilities.py
- safe/definitions/utilities.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/gui/widgets/profile_widget.py
- safe/gui/widgets/test/profile_widget_example.py
- safe/gui/widgets/test/test_profile_widget.py
- safe/utilities/settings.py
- safe/utilities/test/test_settings.py
- Create widget to edit InaSAFE profile, add it to options.
- Use the InaSAFE Profile to get displacement rate and affected
> InaSAFE Profile

- safe/definitions/fields.py
* Ticket: #
* Funded by: 
* Description:
> more explicit declaration of multiexposure fields

- safe/common/signals.py
- safe/gui/tools/multi_exposure_dialog.py
> improve error from multiexposure

- safe/definitions/utilities.py
- safe/gis/vector/prepare_vector_layer.py
- safe/gis/vector/recompute_counts.py
- safe/gis/vector/summary_1_aggregate_hazard.py
- safe/gis/vector/summary_3_analysis.py
- safe/gis/vector/summary_4_exposure_summary_table.py
- safe/gui/tools/help/definitions_help.py
- safe/gui/tools/minimum_needs/needs_calculator_dialog.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/options_dialog.py
- safe/gui/tools/wizard/step_kw40_classify.py
- safe/gui/widgets/message_viewer.py
- safe/gui/widgets/profile_widget.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/impact_function/postprocessors.py
- safe/post_processors/minimum_needs_post_processors.py
- safe/post_processors/population_post_processors.py
- safe/post_processors/post_processors.py
- safe/post_processors/productivity_post_processors.py
- safe/report/extractors/aggregate_postprocessors.py
- safe/utilities/i18n.py
- scripts/checkout_back_after_cleaning_from_pycharm.sh
* Ticket: #
* Description: Check that optimize imports from PyCharm doesn't break InaSAFE
> optimize imports with pycharm

- safe/definitions/default_settings.py
- safe/gui/tools/help/welcome_message.py
- safe/gui/tools/options_dialog.py
- safe/gui/tools/test/test_options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/plugin.py
* Ticket: Part of #4482 
- Adding welcome message when you run InaSAFE for the first time.
- It will check the setting for `inasafe/first_run`. If it's True, or not exist, it will show the welcome message. Currently, you can only get the message once. If you want to see it again, set `inasafe/first_run` setting in QGIS, and set it to True.
Of course I need you @timlinux to make a better message :D
> Welcome message

- safe/definitions/fields.py
- safe/impact_function/test/test_postprocessors.py
- safe/post_processors/productivity_post_processors.py
* Ticket: #4566 
- Update formula for productivity post processor (it use hectare)
- Add unit test.
> Update formula for productivity and add unit test for it.

- safe/gui/tools/options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/gui/widgets/profile_widget.py
- safe/gui/widgets/test/profile_widget_example.py
- safe/gui/widgets/test/test_profile_widget.py
- Sort preference (limited, based on the key)
- Tidy up organisation profile tab per @timlinux request
- Only load the content of the tree widget when restore the default in preference
> Profile Preference Polishing

- safe/gui/tools/options_dialog.py
- safe/utilities/settings.py
- safe/utilities/test/test_settings.py
- safe/utilities/utilities.py
- Add export and import functionality in the options
> Export import setting

- safe/gis/vector/summary_1_aggregate_hazard.py
- safe/gis/vector/summary_3_analysis.py
- safe/gis/vector/summary_4_exposure_summary_table.py
- safe/gis/vector/test/test_summary.py
- safe/impact_function/test/test_postprocessors.py
- safe/processors/post_processor_functions.py
- safe/processors/post_processors.py
- safe/report/extractors/action_notes.py
- safe/report/test/test_impact_report.py
- Use is_affected function for the affected post processor so that it will use the value from InaSAFE profile.
> Use is_affected for affected post processor.

- safe/definitions/default_settings.py
- safe/definitions/font.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/wizard/step_kw40_classify.py
- safe/gui/ui/multi_exposure_dialog_base.ui
- safe/impact_function/impact_function_utilities.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/plugin.py
* Ticket: #4495 for the multiexposure
* Description: Add a new panel in the multiexposure dialog to be able to set layer order in the report
Not the best UI, comments are welcome
@ismailsunni A review would be more than welcome ;-)
> Reporting options for the multi exposure

- safe/gis/sanity_check.py
- safe/impact_function/impact_function.py
- safe/report/test/test_impact_report.py
* Ticket: #
* Description: Remove warnings from PyCharm about variable not declared in init, vars in capital letters
> remove warnings from pycharm in impact_function.py

- safe/definitions/constants.py
- safe/gis/vector/summary_5_multi_exposure.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/multi_exposure_dialog.py
* Ticket: #4495 for the multiexposure
* Description: add custom order for layers provided by the multiexposure analysis
> add custom order for layers provided by the multiexposure analysis

- safe/gui/analysis_utilities.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/plugin.py
- safe/test/debug_helper.py
* Ticket: #
* Description: Adding a test for the custom order structure and for the UI
> multiexposure improvments

- safe/definitions/utilities.py
- safe/gui/tools/print_report_dialog.py
- safe/gui/ui/print_report_dialog.ui
- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
- safe/report/processors/default.py
* Ticket: #4523 #4240 
* Description: Add a print dialog for custom map report purpose.
> add print dialog to work with user's custom template

- safe/gui/tools/print_report_dialog.py
* Ticket: #
* Description: Fix python error when trying to generatae report from print dialog
> fix error with iface parameter

- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/ui/multi_exposure_dialog_base.ui
* Ticket: #4495
* Description: add template field and new status tab
@myarjunar `self.template_path.filePath()` to get the template file path. Is-it enough for you?
I will refine the UI later. Let's merge this one for @myarjunar
> add template field and new status tab

- safe/gis/vector/test/test_summary.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/test/test_multi_exposure.py
- safe/gui/widgets/test/profile_widget_example.py
- safe/test/utilities.py
- show_help.py
* Ticket: #
* Description: add test for multi exposure dialog
> add test for multi exposure dialog

- .gitignore
- test_suite.py
> add coverage

- safe/gui/ui/multi_exposure_dialog_base.ui
@Gustry I updated text for the multi-exposure dialog.
> Update for text on multi-exposure dialog

- safe/report/extractors/analysis_provenance_details.py
* Ticket: Partial fix #4605 
* Description: use provenance keys and hide password
> use provenance keys and hide password

- safe/impact_function/impact_function.py
* Ticket: #
* Description: a patch for print button dialog to fix pop up pdf / qpt output
> fix print pdf and qpt didn't pop up anything

- safe/definitions/extra_keywords.py
- safe/definitions/keyword_properties.py
- safe/definitions/provenance.py
- safe/definitions/reports/components.py
- safe/gis/vector/summary_5_multi_exposure.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/expressions/html_report.py
- safe/report/extractors/analysis_question.py
- safe/report/extractors/general_report.py
- safe/report/extractors/impact_table.py
- safe/report/impact_report.py
- safe/report/test/test_impact_report.py
- safe/report/test/test_impact_report_earthquake.py
- safe/resources/report-templates/standard-template/jinja2/analysis-question.html
- safe/resources/report-templates/standard-template/jinja2/general-report.html
- safe/resources/report-templates/standard-template/jinja2/multi-exposure-impact-report-layout.html
- safe/utilities/expressions.py
* Ticket: #4440 
a snippet of the general report
> Reporting for multi exposure

- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/test/test_multi_exposure.py
- safe/gui/ui/multi_exposure_dialog_base.ui
- safe/impact_function/impact_function.py
* Ticket: #4437 
* Description: improvements to the UI
> Multi exposure dialog

- safe/gis/tools.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
* Ticket: #4619
* Description: load all layers from registry when we deserialize an IF
> load all layers from registry when we deserialize an IF

- safe/definitions/reports/report_descriptions.py
- safe/definitions/utilities.py
* Ticket: #4617 
* Description: set page orientation as the orientation in the template
> fix map composer page orientation according to the template

- safe/gui/analysis_utilities.py
- safe/gui/tools/multi_exposure_dialog.py
* Ticket: #
* Description: improve button status, remove duplicate group when we have a custom ordering
@myarjunar I need your help after this merge. It still doesn't work. And I'm confused in what is needed for reporting.
Do you need all layers in the legend if the user sets a custom order?
Even if we are not generating PDF ? #4613 
Don't forget that Rizky will come with the multiexposure, so he will not use the multi_exposure_dialog so we shouldn't add too much logic in this file because he will use the web interface so better to use analysis_utilities.py to provide some helper
> improve button status, remove duplicate group

- safe/definitions/extra_keywords.py
* Ticket: #
* Description: fix display for HTML in extra_information
It looks like a mistake @myarjunar
> fix display for HTML in extra_information

- safe/definitions/provenance.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/impact_function/test/test_multi_exposure_impact_function.py
- safe/utilities/metadata.py
* Ticket: #
* Description: add provenance in multiexposure
> add provenance in multiexposure

- safe/definitions/constants.py
- safe/gis/test/test_tools.py
- safe/gis/tools.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/save_scenario.py
- safe/gui/tools/test/test_multi_exposure.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
- safe/impact_function/impact_function.py
- safe/impact_function/test/test_impact_function.py
- safe/report/extractors/analysis_provenance_details.py
- safe/utilities/keyword_io.py
- safe/utilities/metadata.py
- safe/utilities/test/test_keyword_io.py
* Ticket: #4605 
* Description: improve provider management
> improve provider management

- safe/report/test/test_expressions.py
* Ticket: #4582 
* Description: Here I try to add a simple unittest for map_report and infographic expressions first. html_report and other expressions that require parameters and legend in the app will come next because I still have no idea how to do it.
> add unittest for map report and infographic expressions

- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/print_report_dialog.py
- safe/gui/tools/wizard/step_fc90_analysis.py
- safe/gui/widgets/dock.py
- safe/report/impact_report.py
- safe/report/test/test_impact_report.py
* Ticket: #4613 
* Description:
> Reporting move pdf generation

- safe/gui/tools/multi_exposure_dialog.py
- safe/impact_function/multi_exposure_wrapper.py
* Ticket: #
* Description: manage multiexposure if no aggregation layer provided
> manage multiexposure if no aggregation layer provided

- metadata.txt
- safe/definitions/versions.py
* Ticket: #
* Funded by: 
* Description:
> Change version to final

- safe/impact_function/multi_exposure_wrapper.py
- safe/impact_function/test/test_multi_exposure_impact_function.py
- safe/utilities/utilities.py
* Ticket: #4612 
* Description: serialize a multiexposure IF
Kudos to @ismailsunni for his work in the single exposure serialization
> serialize a multiexposure IF

- safe/gui/ui/multi_exposure_dialog_base.ui
* Ticket: #4639 
* Description: Multi Exposure Tool polishing
> fix some wording in the multiexposure dialog

- metadata.txt
- safe/gui/widgets/dock.py
* Ticket: #4632 
- Backport uninitialized variable, see ticket for more detail
> Backport fix for uninitialized variable.

- safe/plugin.py
- Remove multi exposure and metadata converter from the toolbar.
> Remove multi exposure and metadata converter from the toolbar.

- metadata.txt
- safe/definitions/versions.py
> Set version to 4.2.5.

- safe/messaging/item/abstract_list.py
* Ticket: Partial #4638 
* Description: Small tweak when I'm was trying to fix #4638. Only partial fix to improve the error message
> make recursive call if it is a list in asbtract_list.py

- safe/definitions/reports/components.py
* Ticket: #4514 #4638 
* Description:  remove `img` from resources. actually, it was only `css` and `js` which has been being used.
> remove img from resources

- safe/gui/tools/help/metadata_converter_help.py
> Added help for keyword exporter

- metadata.txt
* Ticket: #
* Description: update changelog
> update changelog from Etienne

- metadata.txt
> Changelog from @ismailsunni.

- safe/gui/analysis_utilities.py
> fix index error on custom layer order

- safe/gui/widgets/dock.py
* Ticket: #
* Description: Fix error when we are trying to show the kwyqords in the dock
> fix dock error on showing keywords

- safe/gui/tools/help/welcome_message.py
- safe/gui/tools/options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/gui/widgets/profile_widget.py
- safe/gui/widgets/test/profile_widget_example.py
* Ticket: #4630 
- Update text
- Resize column
I address the other polishing in another PR.
> Polish welcome message

- safe/definitions/provenance.py
- safe/definitions/reports/components.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/print_report_dialog.py
- safe/gui/tools/test/test_multi_exposure.py
- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/extractors/composer.py
- safe/report/impact_report.py
- safe/report/processors/default.py
* Ticket: #4649 
* Description:
> map report for multi-exposure IF

- safe/gui/widgets/dock.py
* Ticket: #
* Description: open reports when we click the profiling table in the legend
> open reports when we click the profiling table in the legend

- safe/gis/tools.py
* Ticket: #4637 
* Description:
> fix adding un-symbolized impact layer on print button

- safe/gui/tools/multi_exposure_dialog.py
* Ticket: #4613 
* Description:
> remove pdf generation on multiexposure IF runtime

- safe/plugin.py
- safe/utilities/settings.py
- The welcome message is keep showing although it's already unchecked.
> Fix Welcome Message on Windows

- safe/definitions/default_settings.py
- safe/definitions/reports/map_report.py
- safe/gui/widgets/message.py
- safe/plugin.py
- safe/report/expressions/map_report.py
* Ticket: #4671 
- Use custom logo (from the setting)
> Use custom logo and north arrow. Fix #4671.

- safe/utilities/osm_downloader.py
* Ticket: #
* Description: disable the staging instance of OSM-Reporter
> disable the staging instance of OSM-Reporter

- safe/gui/tools/options_dialog.py
- Make it uniform, avoid future problem (mistype InaSAFE, default value, etc)
> Use settings utilities to store and retrieve setting.

- safe/report/extractors/composer.py
* Ticket: #
* Description: fix error when hide exposure flag is false
> fix error when hide exposure flag is false

- safe/gui/tools/print_report_dialog.py
> fix keywords not found error when trying to open pdf

- safe/gui/tools/osm_downloader_dialog.py
- safe/gui/tools/peta_bencana_dialog.py
- safe/gui/tools/test/test_osm_downloader_dialog.py
- safe/plugin.py
- safe/utilities/qgis_utilities.py
* Ticket: #
* OSM Downloader cleaning
* Allow temporary directory by default
> allow temporary directory in OSM Downloader

- safe/gui/analysis_utilities.py
* Ticket: #
* Description: unicode is not str, use basestring instead
PR to master
That's something we should take care of @ismailsunni @myarjunar
> unicode is not str, use basestring instead

- safe/gis/test/test_tools.py
- safe/gis/vector/test/test_summary.py
- safe/gui/tools/test/test_multi_exposure.py
- safe/gui/widgets/test/profile_widget_example.py
- safe/test/qgis_app.py
- safe/test/utilities.py
- show_help.py
* Ticket: #4701 
* Description: move mock to a dev file
> move mock to a dev file

- safe/gis/raster/zonal_statistics.py
- safe/gis/vector/prepare_vector_layer.py
- safe/gis/vector/tools.py
* Ticket: #3434 
* Description: use renameFields if available
Todo, check the `prepare_vector_layer` step. I'm not sure when we need to copy or where we can rename
> use renameFields if available

- safe/resources/qgis-composer-templates/inasafe-map-report-landscape.qpt
- safe/resources/qgis-composer-templates/inasafe-map-report-portrait.qpt
* Ticket: #2851 
* Description: set preview mode to Render by default in QPT
CC @NyakudyaA 
@myarjunar it seems pretty easy to fix this bug. Anything blocking you on this PR?
> set preview mode to Render by default in QPT

- safe/processors/__init__.py
- safe/test/data/scenario/earthquake_raster_on_vector_places.json
* Ticket: #
* Funded by: 
* Description:
> disable the preprocessor until we have contours

- test_suite.py
* Ticket: #
* Description: disable coverage until I fix it
> disable coverage until I fix it

- safe/definitions/utilities.py
- safe/gui/tools/options_dialog.py
- safe/gui/ui/options_dialog_base.ui
- safe/gui/widgets/profile_widget.py
- safe/gui/widgets/test/profile_widget_example.py
- safe/gui/widgets/test/test_profile_widget.py
* Ticket: #4630 
- Filter out non population classification
> Filter out non-population classification.

- safe/gui/tools/multi_exposure_dialog.py
* Ticket: #
* Description: avoid refresh reporting options if we come from the status panel
> avoid refresh reporting options if we come from the status panel

- safe/definitions/layer_purposes.py
- safe/gis/vector/summary_5_multi_exposure.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/widgets/dock.py
* Ticket: #4715 
* Description: add special name for layers coming from the multi IF
@myarjunar You are doing string comparison with the legend anymore, right?
It looks like a little bit hacky. Names won't match in the reporting options dialog
> add special name for layers coming from the multi IF

- metadata.txt
* Ticket: #
* Funded by: 
* Description:
> update changelog for dam break

- safe/common/parameters/group_select_parameter_widget.py
- safe/common/parameters/test/example_group_select.py
> Use percentage spin box in Field Mapping Tool

- safe/gis/vector/prepare_vector_layer.py
- safe/gis/vector/tools.py
* Ticket: #4721 
* Description: avoid renaming fields if they are used many times
> avoid renaming fields if they are used many times

- metadata.txt
- safe/definitions/exposure_classifications.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
* Ticket: #4370 
* Description: add evacuation centre to buildings and places classification
> add evacuation centre to buildings and places classification

- metadata.txt
- safe/definitions/utilities.py
- safe/plugin.py
* Ticket: #4738
- Fix key error in #4738. (loading old keywords).
>  Fix key error in #4738. (loading old keywords).

- safe/definitions/utilities.py
- safe/plugin.py
* Ticket: #4738 
- Backport from #4741
> Fix 4738 develop

- safe/gui/tools/wizard/step_kw44_fields_mapping.py
* Ticket: #4739 
- Do not save the empty field list. (the logic is already in FMT dialog, but not added in the wizard).
- Should I backport it to 4.2.5 ?
> Do not save the empty field list.

- metadata.txt
- safe/gui/tools/wizard/step_kw44_fields_mapping.py
* Ticket: #4739 
- Backport from issue #4739
> Backport 4739

- safe/gui/tools/metadata_converter_dialog.py
* Ticket: #4732 and #4746
- Hacky work around for fixing #4732.
This is the best that I can do:
Please check in your computer @Charlotte-Morgan
> Hacky work around for fixing #4732 (resize problem in metadata converter).

- metadata.txt
- safe/definitions/fields.py
- safe/definitions/post_processors/productivity_post_processors.py
- safe/gui/tools/metadata_converter_dialog.py
- safe/impact_function/test/test_postprocessors.py
* Ticket: #4569 #4732 
* Description:
> Backport #4569 #4732 

- safe/common/exceptions.py
- safe/gis/vector/clean_geometry.py
- safe/gis/vector/tools.py
- safe/impact_function/impact_function.py
* Ticket: #4304 or discussion on gitter https://gitter.im/inasafe/inasafe?at=5a2903d487680e6230e0359a
* Description: display an error if we can not create the spatial index
I would be happy to not display a message like this and to provide a suggestion. But I'm clueless for now @timlinux
> display an error if we can not create the spatial index

- safe/report/extractors/minimum_needs.py
* Ticket: #4737 
- Fix #4737, initialize variable.
I didn't test, but it should work. Or perhaps I am too confident.
> Fix #4737, initialize variable.

- safe/gui/tools/wizard/step_kw33_multi_classifications.py
* Ticket: #4718 
- Add restore default button for threshold in keyword wizard, see below:
> Add restore default button for threshold per #4718

- safe/definitions/osm_downloader.py
- safe/gui/tools/osm_downloader_dialog.py
- safe/gui/ui/osm_downloader_dialog_base.ui
- safe/utilities/osm_downloader.py
* Ticket: #
* Description: allow custom URL for OSM Downloader in the UI if dev mode
> allow custom URL for OSM Downloader in the UI if dev mode

- safe/gui/tools/test/test_metadata_converter.py
* Ticket: #4625 
- Add unit test for metadata converter dialog.
> Add unit test for metadata converter dialog.

- safe/definitions/reports/components.py
- safe/gui/tools/print_report_dialog.py
- safe/gui/ui/print_report_dialog.ui
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
* Ticket: #4705 
* Description:
> update print dialog ui and behaviour

- safe/definitions/hazard.py
- safe/definitions/units.py
- safe/utilities/keyword_io.py
- safe/utilities/test/test_keyword_io.py
- Make sure all is using name
- Put translation properly:
Before:
After:
> Better Dock in Showing Keywords

- safe/gis/generic_expressions.py
* Ticket: #4389
* Description:
> round down number below a thousand

- safe/gui/widgets/dock.py
> Put back dictionary project variable.

- safe/definitions/exposure.py
- safe/gui/tools/wizard/step_kw45_inasafe_fields.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
- safe/test/data/gisv4/exposure/places.xml
- safe/test/data/scenario/earthquake_raster_on_vector_places.json
* Ticket: #4483 
- Remove field mapping for population in place exposure. Encourage the user to use population point.
> Remove field mapping

- safe/gui/tools/batch/batch_dialog.py
* Ticket: partfix #4597
* Description: another fix will come from @ismailsunni for nested keywords variables
> fix batch runner not showing variables

- safe/gis/generic_expressions.py
* Ticket:  patch for #4765 
* Description: @felix-yew
> fix rounding down logic on value coefficient expression

- safe/report/test/test_expressions.py
I think the code is quite strange
> Fix small strange code.

- safe/definitions/hazard_exposure_specifications.py
* Ticket: #4744
* Description: update earthquake on population notes to describe reporting of fatality estimates in ranges
> Fix earthquake on population notes

- safe/definitions/reports/components.py
- safe/report/extractors/analysis_detail.py
* Ticket: #4483 
* Description: *still on discussion on how do we want the report looks like
> add population report on places with population exposure

- safe/definitions/exposure.py
- safe/definitions/hazard_exposure_specifications.py
* Ticket: #4744  and #4755
* Description: fix rounding for structures and fatalities
> Update notes on rounding for structures and fatalities - take 2

- safe/gui/tools/test/test_multi_buffer.py
- To make our development life better (at least until we fix the unit test in travis)
> Skip test for travis.

- safe/definitions/utilities.py
* Ticket: Part of #4778 
- Use default value in profile for default value.
> Use default value in profile for default value.

- safe/gui/tools/print_report_dialog.py
- safe/gui/ui/print_report_dialog.ui
* Ticket: #4776 
* Description:
> polish on print dialog

- safe/definitions/styles.py
- safe/gui/gui_utilities.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/ui/multi_exposure_dialog_base.ui
* Ticket: Screenshot from @ismailsunni https://files.gitter.im/inasafe/inasafe/1192/Screen-Shot-2017-12-14-at-15.08.17.png
* Description:
* increase width of aggregation and analysis summary
* Add padding and review words in the multiexposure dialog
* Show count of selected features in aggregation combobox if needed
> increase width of aggregation and analysis summary

- safe/definitions/fields.py
- safe/gis/vector/summary_4_exposure_summary_table.py
- safe/gis/vector/test/test_summary.py
- safe/processors/__init__.py
- safe/processors/post_processor_functions.py
- safe/processors/productivity_post_processors.py
- safe/test/data/scenario/raster_continuous_on_divisible_polygons_with_grid.json
* Ticket: #4816 
- Simpler implementation for fixing the bug. It's merely using summarizer method, not new post processors. Just make sure the affected column is set to correct value.
> Simpler implementation for calculating affected productivity.

- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/wizard/step_fc90_analysis.py
- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/utilities/utilities.py
This reverts commit ae2bead30c4ae2d01bec358d31a28e9896189b93.
- Sorry @Gustry , I can't run analysis properly with that commit. After reverting, I can run it normally.
> Revert "be sure that we have a Message instance"

- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/wizard/step_fc90_analysis.py
- safe/gui/widgets/dock.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/utilities/utilities.py
* Ticket: #
* Description: Two lines to fix it. I can't replicate your issue @ismailsunni 
IF working:
> be sure that we have a Message instance

- safe/gui/tools/print_report_dialog.py
* Ticket: #4089
* Description:
> fix bug on print dialog

- safe/impact_function/multi_exposure_wrapper.py
- safe/impact_function/provenance_utilities.py
- safe/impact_function/test/test_provenance_utilities.py
- safe/report/extractors/analysis_question.py
- safe/resources/qgis-composer-templates/inasafe-map-report-landscape.qpt
* Ticket: #4794 
* Description:
> update analysis question on multi-exposure report

- safe/processors/post_processor_functions.py
* Ticket: On our way to fix #4810 
* Description: Only updating docstring about the affected postprocessor
> update docstring about affected postprocessor

- safe/definitions/test/test_utilities.py
- safe/definitions/utilities.py
- safe/test/data/hazard/classified_generic_polygon.xml
* Ticket: #4810 
- Set default value for unknow hazard class to not exposed.
> Fix #4810, fix missing not exposed for population profile.

- safe/definitions/reports/components.py
- safe/report/extractors/analysis_detail.py
- safe/report/extractors/util.py
* Ticket: #4783 
* Description:
> update population place exposure report with exposed population

- safe/gui/tools/options_dialog.py
- safe/gui/widgets/profile_widget.py
* Ticket: #4788 
- Make the colum of population parameter not movable.
- Use sentence case for restore default button in option dialog
- Tidy up some code.
> Fix 4788 polish population parameter

- safe/definitions/constants.py
- safe/definitions/fields.py
- safe/gis/raster/contour.py
- safe/gis/vector/tools.py
- safe/gui/tools/shake_grid/test/test_shake_grid.py
- safe/processors/__init__.py
- safe/processors/pre_processors.py
* Ticket: #4832 
- Remove print, better import place, remove outdated comment.
> Addressing Etienne's Comment for Contour PR

- safe/gui/tools/help/impact_report_help.py
- safe/gui/tools/print_report_dialog.py
- safe/gui/ui/print_report_dialog.ui
- safe/impact_function/multi_exposure_wrapper.py
* Ticket: #4803 #4795 
* Description:
> Another print dialog polish

- safe/gis/tools.py
- safe/gui/widgets/dock.py
* Ticket: #4806 
* Description:
> add handler for invalid layer path

- safe/definitions/fields.py
> Review contour fields.

- safe/gui/ui/batch_dialog_base.ui
* Ticket: #4457 
* Description: add top margin to avoid shrink text in batch dialog
Not the best solution, but nothing else
> add top margin to avoid shrink text in batch dialog

- __init__.py
* Ticket: #4090
* Description: display a quick message warning about missing submodule
Feel free to merge and update transifex if possible.
> display a quick message warning about missing submodule

- safe/gui/tools/multi_exposure_dialog.py
- safe/utilities/extent.py
* Ticket: #4645 
* make Extent a singleton
* Multiexposure and Batch Runner dialog to use the Extent object
> make Extent a singleton and fix multiexposure dialog to use it

- safe/impact_function/style.py
* Ticket: None
* Description: Based on @ivanbusthomi's screenshot:
@ivanbusthomi Can you try this fix as I don't have this issue.
> make symbol in attribute table transparent

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
* Ticket: #
* Description: comments are invisible in view mode, only in editing mode
> add some comments to issue and PR templates

- safe/definitions/__init__.py
- safe/definitions/extra_keywords.py
- safe/definitions/hazard.py
- safe/definitions/test/test_utilities.py
- safe/gis/generic_expressions.py
- safe/gui/tools/wizard/step_fc25_hazlayer_from_browser.py
- safe/gui/tools/wizard/step_fc40_explayer_from_browser.py
- safe/gui/tools/wizard/step_kw55_source.py
- safe/gui/tools/wizard/step_kw57_extra_keywords.py
- safe/gui/tools/wizard/step_kw60_title.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
- safe/gui/tools/wizard/wizard_dialog.py
- safe/gui/tools/wizard/wizard_step_browser.py
- safe/gui/ui/wizard/step_kw57_extra_keywords.ui
- safe/gui/widgets/dock.py
- safe/test/data/hazard/ash_raster_wgs84.xml
- safe/utilities/keyword_io.py
* Ticket: #4805 
* Description:
> Fix 4805 volcanic ash keywords

- safe/definitions/reports/infographic.py
- safe/resources/report-templates/standard-template/jinja2/general-report.html
* Ticket: partfix #4792 #4797
* Description: added a gap between tables in general report (for windows users)
> Reporting patch

- safe/gui/tools/batch/batch_dialog.py
* Ticket: partfix #4486
* Description: fix missing value on infographic using batch runner cc @felix-yew
> fix infographic on batch runner

- safe/impact_function/multi_exposure_wrapper.py
* Ticket: fix #4853
* Fix python exception in multi exposure
> fix rounding attribute error multiexposure

- safe/definitions/extra_keywords.py
- safe/definitions/test/test_utilities.py
- safe/gis/generic_expressions.py
- safe/gui/tools/shake_grid/shake_grid.py
- safe/gui/tools/wizard/step_kw57_extra_keywords.py
- safe/gui/ui/wizard/step_kw57_extra_keywords.ui
- safe/processors/post_processors.py
- safe/test/data/gisv4/hazard/earthquake.xml
- safe/test/data/hazard/ash_raster_wgs84.xml
- safe/utilities/keyword_io.py
* Ticket: #4851 
- Use list of volcano to populate the volcano name from here : #2491 (comment) *User also needs to be able to input their own
- Add tooltip from the definition (or put it in the help for the step)
- Make sure we have all needed information for re-creating ash realtime / eq realtime
- Make sure we have proper definition for all extra keywords.
> Polish volcanic ash

- .github/PULL_REQUEST_TEMPLATE.md
* Ticket: None
* Funded by: 
* update submodule again
> update submodule again

- safe/definitions/extra_keywords.py
- safe/gui/tools/wizard/step_kw57_extra_keywords.py
- safe/test/data/hazard/ash_raster_wgs84.xml
* Ticket: #4857 
* Add ash event ID (generated automatically)
* Add volcano height extra keywords
> Fix 4857 missing realtime information

- safe/definitions/reports/components.py
* Ticket: #4797 partfix
* Description: change population chart from affected to exposed
*
> change chart label from Affected to Exposed

- safe/report/extractors/general_report.py
- safe/report/test/test_impact_report.py
* Ticket: fix #4855
* separate table per hazard classification when multi-classifications found
> multi-exposure multi-classifications general report

- __init__.py
- metadata.txt
- safe/definitions/versions.py
- scripts/release.sh
* Bump version, edit changelog.
> Bump version 4.3.

- CHANGELOG
* Ticket: No ticket number
* Update git changelog for 4.3
> Update git changelog.

- safe/gui/tools/help/definitions_help.py
* Ticket: #4872 
* add version number in the help doc
* not the best, but better than nothing
> add version number in the help doc

- safe/gui/tools/batch/batch_dialog.py
* Ticket: #
* fix the behaviour of batch runner output directory
> rework on batch runner output layers and reports directory

- safe/definitions/extra_keywords.py
- safe/definitions/hazard.py
- safe/gui/tools/wizard/step_kw57_extra_keywords.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
- safe/gui/tools/wizard/wizard_dialog.py
- safe/gui/ui/wizard/step_kw57_extra_keywords.ui
- setup.py
* Fix missing extra keywords after shakemap converter
* Much better extra keywords step
> Extra keywords fix

- safe/definitions/extra_keywords.py
- safe/definitions/hazard.py
- safe/gui/analysis_utilities.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
* Ticket: #4857 
* Add flood event ID and flood event date time
> Flood extra keywords

- metadata.txt
- safe/definitions/versions.py
- safe/gui/tools/multi_exposure_dialog.py
* Ticket: :point_up: [January 25, 2018 7:24 AM](https://gitter.im/inasafe/inasafe?at=5a695be6c95f22546de0714a)
* clear the output layers list when you close the multi dialog
* Bump to 4.3.2
>  clear the output layers list when you close the multi dialog

- safe/report/impact_report.py
> remove iface dependency on ImpactReport

- safe/gui/widgets/dock.py
Make the methods to set and remove provenance static so I can easily import them in inasafe-headless.
*
> Make set and remove provenance static method.

- safe/report/extractors/composer.py
* Ticket: #
* Fix a problem on inasafe-headless when generating report (only impact layer on map canvas)
> fix hazard, exposure, and aggregation layer id on IF serialization

- safe/definitions/extra_keywords.py
- safe/gui/tools/wizard/step_kw57_extra_keywords.py
- safe/utilities/test/test_osm_downloader.py
* Ticket: #4851 
* Add forecast duration extra keywords.
> Add forecast duration extra keywords.

- safe/utilities/test/test_osm_downloader.py
This reverts commit 7ee271c5380bad2abc278ecb41764d82ced1448f.
* Ticket: #
* Funded by: 
*
> Revert "Skip unit test until we fix osm.inasafe.org."

- safe/gui/analysis_utilities.py
- safe/gui/tools/print_report_dialog.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/extractors/composer.py
- safe/report/impact_report.py
- safe/report/processors/default.py
- safe/report/test/test_impact_report.py
* Ticket: #
* Headless needs a call for generating report where the client can give a parameter for layer order in the map report.
> Layers order parameter

- safe/gui/widgets/dock.py
* Ticket: #
* Log error instead of silently fail
> log exceptions in the dock

- safe/gui/tools/about_dialog.py
- safe/gui/tools/extent_selector_dialog.py
- safe/gui/tools/field_mapping_dialog.py
- safe/gui/tools/help_dialog.py
- safe/gui/tools/metadata_converter_dialog.py
- safe/gui/tools/minimum_needs/needs_calculator_dialog.py
- safe/gui/tools/minimum_needs/needs_manager_dialog.py
- safe/gui/tools/multi_buffer_dialog.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/options_dialog.py
- safe/gui/tools/osm_downloader_dialog.py
- safe/gui/tools/peta_bencana_dialog.py
- safe/gui/tools/save_scenario.py
- safe/gui/tools/shake_grid/shakemap_converter_dialog.py
- safe/gui/tools/wizard/wizard_dialog.py
* Ticket: #
* Add some missing icons
> add missing icons on windows

- safe/gui/gui_utilities.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/widgets/dock.py
* Ticket: #
* Add icons in QComboBox
Anything against this UI?
> add layer icon in qcombobox

- safe/gis/generic_expressions.py
- safe/resources/qgis-composer-templates/infographic.qpt
* Ticket: #4724 comment 
* The name of the expression was not 100% correct. I really don't like this kind of fix because our expressions are public in InaSAFE, so we shouldn't update them, some users might already use them and this will break their templates. But better to do it now than later.
Based on the layer purpose: https://github.com/inasafe/inasafe/blob/develop/safe/definitions/layer_purposes.py#L139
@ivanbusthomi @myarjunar We need to update templates.
> update expression name analysis summary layer

- safe/common/test/test_version.py
- setup.py
* Ticket: #4909 
* We need this fix for inasafe-headless also, since we want to get inasafe from pypi.
> Fix failed install pypi package due to unable to get version. Fix #4909

- safe/plugin.py
* Ticket: #
* avoid python exceptions when reading keywords on a postgis layer
> avoid python exceptions when reading keywords on a postgis layer

- safe/gis/vector/prepare_vector_layer.py
* Ticket: Realtime
* avoid python exception if no data in the IF
> avoid python exception if no data in the IF

- safe/definitions/reports/report_descriptions.py
- safe/definitions/utilities.py
* Ticket: #
* Funded by: 
* fix orientation on custom template
> fix orientation when using custom template

- safe/gui/tools/multi_exposure_dialog.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/impact_function/test/test_multi_exposure_impact_function.py
- safe/report/test/test_impact_report.py
* Ticket: #
* report the culprit exposure when a multi exposure failed
> report the culprit exposure when a multi exposure failed

- safe/definitions/provenance.py
- safe/gis/generic_expressions.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/expressions/map_report.py
* Ticket: #4724 
* Funded by: 
* fix expression so @ivanbusthomi can work with the case as mentioned in #4724
> add expression for multi exposure analysis specific

- safe/impact_function/multi_exposure_wrapper.py
- safe/report/extractors/composer.py
* Ticket: #
* another fix for raster on raster analysis type  when generating report (check #4907 )
> fix report when no exposure summary found

- safe/report/extractors/composer.py
* Ticket: #
* fix another no exposure summary error on generating report
> replace exposure summary with aggregate hazard summary for continuos raster exposure

- safe/impact_function/impact_function.py
* Ticket: #
* save default style to QML at the end of the IF
> save default style to QML at the end of the IF

- safe/gis/vector/clean_geometry.py
- safe/gis/vector/tools.py
* Ticket: #4304
* 
@ismailsunni Can you try this branch and check if you have this geometric error?
DO NOT MERGE THIS PR, WIP
> insert feature one per one in the spatial index

- safe/gis/generic_expressions.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/extractors/composer.py
* Ticket: #
* fix unevaluated expressions in inasafe realtime
* fix duplicated impact layer on the map report for multi-exposure
> Headless report

- safe/gis/tools.py
* Ticket: #
* loading a layer from qgis registry (style purpose)
> fix loading a layer from qgis registry

- safe/plugin.py
* Ticket: #
* Funded by: 
* @ismailsunni Should we release 4.3.3 after that?
> hide geoode uploader button

- safe/gis/generic_expressions.py
- safe/report/expressions/map_report.py
* Ticket: #
* add expression to get the values of exposure summary
> Aggregate expressions

- safe/gis/tools.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/extractors/composer.py
- safe/report/impact_report.py
- safe/report/processors/default.py
- safe/report/test/test_impact_report.py
* Ticket: #
* add legend layers parameter for ImpactReport
> add legend layers parameter for ImpactReport

- safe/utilities/test/test_metadata.py
> add more tests to copy metadata

- safe/impact_function/multi_exposure_wrapper.py
* Ticket: #
* I don't like this hack, but it's necessary for Celery. This bug doesn't show up in desktop, I couldn't figure out where/when these variables are the same.
@myarjunar It should solve your issue. Feel free to merge and update inasafe-headless submodule if needed
> hacky way to fix wrong hazard keywords in Celery

- metadata.txt
> Update metadata for v4.3.2.

- safe/plugin.py
* Ticket:
* enable geonode uploader
> enable geonode uploader

- metadata.txt
- safe/definitions/versions.py
- safe/gis/vector/clean_geometry.py
- safe/gis/vector/prepare_vector_layer.py
* Ticket: #
* Funded by: 
* bump to version 4.4.0
I hope I'm not wrong. As we decided to release 4.4. InaSAFE 4.4.X will be the last on QGIS 2 I think with some features.
> bump to version 4.4.0

- safe/gis/raster/clip_bounding_box.py
- safe/gis/raster/polygonize.py
- safe/gis/raster/reclassify.py
- safe/gis/raster/zonal_statistics.py
- safe/gis/vector/assign_highest_value.py
- safe/gis/vector/clean_geometry.py
- safe/gis/vector/clip.py
- safe/gis/vector/default_values.py
- safe/gis/vector/from_counts_to_ratios.py
- safe/gis/vector/intersection.py
- safe/gis/vector/prepare_vector_layer.py
- safe/gis/vector/reclassify.py
- safe/gis/vector/recompute_counts.py
- safe/gis/vector/smart_clip.py
- safe/gis/vector/summary_1_aggregate_hazard.py
- safe/gis/vector/summary_2_aggregation.py
- safe/gis/vector/summary_3_analysis.py
- safe/gis/vector/summary_4_exposure_summary_table.py
- safe/gis/vector/union.py
- safe/gis/vector/update_value_map.py
* Ticket: #3245
* remove unnecessary code from gis package
> remove unnecessary code from gis package

- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/impact_function/test/test_multi_exposure_impact_function.py
* Ticket: fix #4942 
* update layer id whenever IF is being serialized
> update layer id whenever IF is being serialized

- safe/common/custom_logging.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/tools/wizard/step_fc90_analysis.py
- safe/gui/widgets/dock.py
- safe/utilities/gis.py
* Ticket: #
* add `HOSTNAME_SENTRY` to customize the hostname in sentry
> add HOSTNAME_SENTRY to customize the hostname in sentry

- safe/datastore/datastore.py
- safe/datastore/folder.py
- safe/datastore/geopackage.py
- safe/datastore/test/test_folder.py
- safe/impact_function/impact_function.py
- safe/processors/pre_processors.py
- safe/resources/converter_data/mmi-contours.qml
* Ticket: :point_up: [March 16, 2018 12:22 AM](https://gitter.im/inasafe/inasafe?at=5aab00383fe1be3704c9d7c9) by @lucernae 
* save default style in datastore
> fix save default style in datastore

- safe/gis/vector/summary_1_aggregate_hazard.py
- safe/gis/vector/summary_2_aggregation.py
- safe/gis/vector/summary_3_analysis.py
- safe/gis/vector/summary_tools.py
* Ticket: Linked to #4070 
* allow to add many dynamic fields when summing layers in the waterfall
> allow to add many dynamic fields when summing layers in the waterfall

- safe/impact_function/multi_exposure_wrapper.py
- safe/report/expressions/html_report.py
> Html report expression

- metadata.txt
- safe/definitions/versions.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/impact_function/test/test_multi_exposure_impact_function.py
- safe/report/expressions/html_report.py
- safe/report/processors/default.py
> Bump up version 4.3.3

- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/impact_report.py
- safe/report/processors/default.py
* Ticket: #
* add property for using template extent, inasafe desktop will have this property as `False` and flood realtime will set this property to `True` because flood realtime has its own template setting
> add impact report property for template extent setting

- safe/impact_function/impact_function.py
* Ticket: #
* docstring update
> update missing docstring on generate report

- metadata.txt
- safe/definitions/versions.py
- safe/impact_function/impact_function.py
- safe/impact_function/multi_exposure_wrapper.py
- safe/report/impact_report.py
- safe/report/processors/default.py
* Ticket: #
* Description:   
* Fix bug with map report extent (turns out default template also has extent setting on it)
* Move the option for using template extent as an Impact Report property
> Bump up version 4.3.4

- safe/impact_function/multi_exposure_wrapper.py
* Ticket: #
* fix https://github.com/inasafe/inasafe/pull/4961#issuecomment-374476652
> fix infographic not showning any expressions on multi-exposure

- safe/impact_function/multi_exposure_wrapper.py
* Ticket: #
* Merge master to develop
> Merge master to develop

- safe/gui/tools/minimum_needs/needs_manager_dialog.py
* Ticket: #4900 
* Funded by: 
* 
cc @samnawi
> Set precision to 6 decimal for minimum needs.

- safe/gui/tools/minimum_needs/needs_manager_dialog.py
> Set minimum value to 0.0

- safe/gis/raster/contour.py
* Ticket: #4832 #4893 
- In InaSAFE Realtime 3.5
- Before bug fixed
- After bug fixed
cc: @lucernae @myarjunar I am sure that you guys don't use contour creation in inasafe-realtime / inasafe-headless directly (besides in unit test of inasafe-headless). So, ping you here to change that part of the code also.
> Contour fix

- safe/definitions/reports/infographic.py
- safe/report/expressions/infographic.py
- safe/report/test/test_expressions.py
* Ticket: #4970 
*  fix capitalisation formatting issue in expressions used in Infographic reports
* does not fix capitalisation formatting issue in html text in Infographic reports
> part fix_#4970

- safe/gui/widgets/dock.py
* Ticket: #
* if aggregation layer, the extent should be aggregation CRS or mapcanvas
> if aggregation layer, the extent should be aggregation CRS or mapcanvas

- safe/utilities/geonode/upload_layer_requests.py
> Check the status code first before parsing the content of request result

- safe/common/exceptions.py
- safe/gis/vector/convert_geojson_to_shapefile.py
- safe/gis/vector/test/test_geojson_to_shapefile.py
- safe/test/utilities.py
- safe/utilities/geonode/test/test_geonode_uploaded.py
- safe/utilities/geonode/upload_layer_requests.py
> Upload geonode handling

- metadata.txt
* Funded by DFAT
* Update metadata for releasing 4.4
> Update metadata/changelog for 4.4

- metadata.txt
- safe/definitions/versions.py
> Bump version number to 4.4 final.

- metadata.txt
> Update changelog for v4.4

- safe/utilities/metadata.py
* Ticket: #
* somehow in an attempt to fix the segmentation fault, after I debugged thoroughly through the code, I found that these line of codes caused the `QgsApplication` instance to be destroyed. It's a duplicated code though, so we can just remove it.
> remove duplicate metadata initialisation

- safe/gui/tools/geonode_uploader.py
- safe/gui/ui/geonode_uploader.ui
* Funded by DFAT
* Show better error message when failed to upload to geonode
> Better exception handling in GeoNode uploader.

- CHANGELOG
> Update CHAGELOG for 4.4 (again).

- safe/utilities/geonode/upload_layer_requests.py
> [Port to Master] Handle json extension for geojson file.

- safe/gis/tools.py
- safe/utilities/utilities.py
* Ticket: #
* Funded by: Kartoza
* `monkey_patch_keywords()` duplicate the logic that we've done on the previous code (reading the keywords)
> update logic so it doesnt read keywords twice

- metadata.txt
> Set minimum QGIS version to 3.2

- safe/common/utilities.py
- safe/common/version.py
- safe/test/test_python_pep.py
- scripts/missing_translations.py
Fixes exceptions when communicating with processes
> Set encoding when calling Popen

- safe/datastore/test/test_folder.py
- safe/gis/vector/test/test_count_to_ratio.py
- safe/gui/tools/geonode_uploader.py
- safe/gui/tools/metadata_converter_dialog.py
- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/widgets/dock.py
- safe/gui/widgets/test/test_dock.py
- safe/impact_function/test/test_multi_exposure_impact_function.py
- safe/impact_function/test/test_style.py
- safe/utilities/qgis_utilities.py
It always gives None in some place.
* Ticket: #
* Funded by: 
*
> Add iface variable.

- safe/gis/processing_tools.py
- safe/gis/vector/clean_geometry.py
- safe/gis/vector/tools.py
Trying to update https://github.com/inasafe/inasafe/pull/5007
* Ticket: #
* Funded by: Kartoza
*
> Fix geom repair

- safe/utilities/file_downloader.py
- setup.py
- test_suite.py
Set parameter version to the correct one.
* Ticket: #
* Funded by: Kartoza
*
> Set parameter version to 2.0.0

- metadata.txt
- safe/definitions/versions.py
- scripts/windows-install-builder.nsi
Update win installer to work on QGIS3.
Notes:
- Only install for the default profile
- The user will need to enable it manually
* Ticket: #
* Funded by: 
* 
Update win installer to work on QGIS3.
Notes:
- Only install for the default profile
- The user will need to enable it manually
* Ticket: #
* Funded by: 
*
> Win installer

- scripts/windows-install-builder.nsi
> Fix wrong English sentence.

- Makefile
> update comment about docker-test

- __init__.py
* Ticket: #5033 
* Funded by: 
* Description: updates user warning message to help people with first installation
*
> Update user warning

- .travis.yml
- safe/common/parameters/test/example_group_select.py
- safe/gis/raster/test/test_contour.py
- safe/gui/tools/wizard/test/test_keyword_wizard.py
- safe/impact_function/test/test_impact_function.py
- safe/report/test/hello_world_report.py
- safe/test/test_python_pep.py
- safe/utilities/test/test_osm_downloader.py
- safe/utilities/utilities.py
- test_suite.py
use the official QGIS docker base image for travis
WIP:
> use the official QGIS docker base image for travis

- safe/gui/tools/multi_exposure_dialog.py
- safe/gui/widgets/dock.py
* Ticket: #5045 
* Funded by: myself
* improve error message when reports are not going to be generated
> improve error message when reports are not going to be generated

- Makefile
- run-docker-test.sh
> update local docker test configuration

- safe/gis/raster/clip_bounding_box.py
- safe/impact_function/test/test_impact_function.py
We now fixed the minimum needs calculation and bug on the unit test.
Probably this PR #5059 will succeed.
> Follow up on PR #5059

- .env
- .travis.yml
- CHANGELOG
- docker-compose.yml
- metadata.txt
- safe/definitions/versions.py
- safe/gui/tools/minimum_needs/test/test_minimum_needs_tool.py
- scripts/docker/inasafe-test-pre-scripts.sh
- scripts/docker/qgis-testing-entrypoint.sh
- test_suite.py
Metadata update for release 5.0.1
> Update release metadata to 5.0.1

- README.md
> Fix broken link, add history, remove PyCharm

- safe/gis/vector/assign_highest_value.py
- safe/gis/vector/tools.py
Fix https://github.com/inasafe/inasafe/issues/5092 by using QGIS own sorting API.
Fix https://github.com/inasafe/inasafe/issues/5089 by using standard osgeo import.
> Aggregate sort
